/**
 * bindgen_tests.ts — Phase 50 Test Suite
 *
 * Tests the bindgen TypeScript host binding generator.
 * Covers: WIT parsing, binding generation (unit), and end-to-end integration
 * (compile fixture → bindgen → run generated binding host).
 *
 * Usage:
 *   deno run --allow-read --allow-write --allow-run --allow-env tests/bindgen_tests.ts
 */

import { join, toFileUrl } from "jsr:@std/path";
import { bold, cyan, green, magenta, red, yellow } from "jsr:@std/fmt/colors";
import { generateBindings, parseWit } from "../src/bindgen.ts";

const FIXTURES = join(import.meta.dirname!, "bindgen_fixtures");
const WASMTK_BIN = "wasmtk";

// ── Assertion harness ────────────────────────────────────────────────────────

let passed = 0;
let failed = 0;

function ok(desc: string, cond: boolean) {
  if (cond) {
    console.log(green(`  ✓ ${desc}`));
    passed++;
  } else {
    console.log(red(`  ✗ ${desc}`));
    failed++;
  }
}

function contains(desc: string, haystack: string, needle: string) {
  ok(desc, haystack.includes(needle));
}

// ── Helper: run subprocess ───────────────────────────────────────────────────

async function run(
  cmd: string,
  args: string[],
): Promise<{ success: boolean; stdout: string; stderr: string }> {
  const result = await new Deno.Command(cmd, {
    args,
    stdout: "piped",
    stderr: "piped",
  }).output();
  const dec = new TextDecoder();
  return {
    success: result.success,
    stdout: dec.decode(result.stdout),
    stderr: dec.decode(result.stderr),
  };
}

// ── 1. parseWit — basic math (exports only) ──────────────────────────────────

function testParseWitMath() {
  console.log(yellow(bold("\n── parseWit — math exports")));

  const wit = `// Generated by wasmtk wasic — do not edit manually
package local:math-50;

world math-50 {
  export add: func(a: s32, b: s32) -> s32;
  export multiply: func(a: f64, b: f64) -> f64;
  export square: func(x: s32) -> s32;
}
`;
  const p = parseWit(wit);
  ok("packageName", p.packageName === "local:math-50");
  ok("worldName", p.worldName === "math-50");
  ok("no imports", p.imports.length === 0);
  ok("3 exports", p.exports.length === 3);
  ok("add: name", p.exports[0].name === "add");
  ok("add: tsName", p.exports[0].tsName === "add");
  ok("add: param a s32", p.exports[0].params[0].type === "s32");
  ok("add: result s32", p.exports[0].result === "s32");
  ok("multiply: f64 return", p.exports[1].result === "f64");
  ok("square: tsName", p.exports[2].tsName === "square");
}

// ── 2. parseWit — bool functions ─────────────────────────────────────────────

function testParseWitBool() {
  console.log(yellow(bold("\n── parseWit — bool functions")));

  const wit = `package local:booleans-50;

world booleans-50 {
  export is-positive: func(x: f64) -> bool;
  export in-range: func(v: f64, lo: f64, hi: f64) -> bool;
  export is-even: func(n: s32) -> bool;
}
`;
  const p = parseWit(wit);
  ok("3 exports", p.exports.length === 3);
  ok("isPositive tsName", p.exports[0].tsName === "isPositive");
  ok("isPositive result bool", p.exports[0].result === "bool");
  ok("inRange tsName", p.exports[1].tsName === "inRange");
  ok("inRange 3 params", p.exports[1].params.length === 3);
  ok("isEven tsName", p.exports[2].tsName === "isEven");
  ok("isEven param s32", p.exports[2].params[0].type === "s32");
}

// ── 3. parseWit — string functions ───────────────────────────────────────────

function testParseWitStrings() {
  console.log(yellow(bold("\n── parseWit — string functions")));

  const wit = `package local:strings-50;

world strings-50 {
  export greet: func(name: string) -> string;
  export shout: func(msg: string) -> string;
  export str-len: func(s: string) -> s32;
}
`;
  const p = parseWit(wit);
  ok("3 exports", p.exports.length === 3);
  ok("greet: param type string", p.exports[0].params[0].type === "string");
  ok("greet: result string", p.exports[0].result === "string");
  ok("shout: result string", p.exports[1].result === "string");
  ok("strLen: tsName", p.exports[2].tsName === "strLen");
  ok("strLen: result s32", p.exports[2].result === "s32");
}

// ── 4. parseWit — with imports ────────────────────────────────────────────────

function testParseWitImports() {
  console.log(yellow(bold("\n── parseWit — with imports")));

  const wit = `package local:imports-50;

world imports-50 {
  import env-mul: func(a: f64, b: f64) -> f64;
  import env-add: func(a: s32, b: s32) -> s32;
  export scale: func(x: f64, factor: f64) -> f64;
  export combine: func(a: s32, b: s32) -> s32;
}
`;
  const p = parseWit(wit);
  ok("2 imports", p.imports.length === 2);
  ok("2 exports", p.exports.length === 2);
  ok("envMul import tsName", p.imports[0].tsName === "envMul");
  ok("envMul import name (kebab)", p.imports[0].name === "env-mul");
  ok("envAdd import result s32", p.imports[1].result === "s32");
  ok("scale export f64 return", p.exports[0].result === "f64");
}

// ── 5. generateBindings — math interface ─────────────────────────────────────

function testGenBindingsMath() {
  console.log(yellow(bold("\n── generateBindings — math module")));

  const wit = `package local:math-50;
world math-50 {
  export add: func(a: s32, b: s32) -> s32;
  export multiply: func(a: f64, b: f64) -> f64;
  export square: func(x: s32) -> s32;
}
`;
  const ts = generateBindings(wit);
  ok("has auto-generated comment", ts.includes("auto-generated by wasmtk bindgen"));
  contains("exports ModuleExports", ts, "export interface ModuleExports {");
  contains("add signature", ts, "add(a: number, b: number): number;");
  contains("multiply signature", ts, "multiply(a: number, b: number): number;");
  contains("square signature", ts, "square(x: number): number;");
  contains("loadModule exported", ts, "export async function loadModule(");
  ok("no ModuleImports (no imports)", !ts.includes("ModuleImports"));
  ok("no _writeStr (no string params)", !ts.includes("_writeStr"));
  ok("no _readStr (no string return)", !ts.includes("_readStr"));
  // WASM export names are camelCase (original TS names), not kebab→snake
  contains("add wasm call", ts, `exp["add"]`);
}

// ── 6. generateBindings — bool conversions ───────────────────────────────────

function testGenBindingsBool() {
  console.log(yellow(bold("\n── generateBindings — bool module")));

  const wit = `package local:booleans-50;
world booleans-50 {
  export is-positive: func(x: f64) -> bool;
  export in-range: func(v: f64, lo: f64, hi: f64) -> bool;
}
`;
  const ts = generateBindings(wit);
  contains("isPositive returns boolean", ts, "isPositive(x: number): boolean");
  contains("inRange returns boolean", ts, "inRange(v: number, lo: number, hi: number): boolean");
  contains("bool return conversion !== 0", ts, "!== 0");
  ok("no string helpers", !ts.includes("_writeStr"));
}

// ── 7. generateBindings — string ABI ─────────────────────────────────────────

function testGenBindingsStrings() {
  console.log(yellow(bold("\n── generateBindings — string module")));

  const wit = `package local:strings-50;
world strings-50 {
  export greet: func(name: string) -> string;
  export str-len: func(s: string) -> s32;
}
`;
  const ts = generateBindings(wit);
  contains("greet(name: string): string", ts, "greet(name: string): string");
  contains("strLen(s: string): number", ts, "strLen(s: string): number");
  contains("_writeStr helper", ts, "function _writeStr(s: string)");
  contains("cabi_realloc accessed", ts, `exp["cabi_realloc"]`);
  contains("_writeStr called in greet", ts, "_writeStr(name)");
  // Canonical return convention: the callee allocates the return area, so the host no longer
  // allocates an 8-byte area; instead it reads the returned pointer and calls cabi_post_<name>.
  ok("no host-side return-area alloc", !ts.includes(`_cabi_realloc(0, 0, 4, 8)`));
  contains("cabi_post called for greet", ts, `exp["cabi_post_greet"]`);
  contains("DataView used for string return", ts, "DataView");
  contains("TextEncoder used", ts, "TextEncoder");
  contains("TextDecoder used", ts, "TextDecoder");
  ok("no __malloc (replaced by cabi_realloc)", !ts.includes(`exp["__malloc"]`));
  ok("no __str_ret_ptr in host glue", !ts.includes(`__str_ret_ptr`));
  ok("no _readStr (replaced by inline DataView)", !ts.includes(`function _readStr`));
}

// ── 8. generateBindings — import section ─────────────────────────────────────

function testGenBindingsImports() {
  console.log(yellow(bold("\n── generateBindings — import section")));

  const wit = `package local:imports-50;
world imports-50 {
  import env-mul: func(a: f64, b: f64) -> f64;
  import env-add: func(a: s32, b: s32) -> s32;
  export scale: func(x: f64, factor: f64) -> f64;
}
`;
  const ts = generateBindings(wit);
  contains("ModuleImports interface", ts, "export interface ModuleImports {");
  contains("env optional", ts, "env?: {");
  contains("envMul in imports interface", ts, "envMul?:");
  contains("envAdd in imports interface", ts, "envAdd?:");
  contains("imports param in loadModule", ts, "imports?: ModuleImports");
  contains("env wired up in importObj", ts, `env["env_mul"]`);
  contains("env_add wired up", ts, `env["env_add"]`);
}

// ── 9. Integration: compile math fixture → modc → bindgen → run host ─────────

async function testIntegrationMath() {
  console.log(yellow(bold("\n── Integration: math_50 compile + bindgen + host")));

  const fixtureSrc = join(FIXTURES, "math_50.ts");
  const fixtureWasm = join(FIXTURES, "math_50.wasm");
  const fixtureWit = join(FIXTURES, "math_50.wit");
  const fixtureBinding = join(FIXTURES, "math_50.bindings.ts");
  const hostRunner = join(FIXTURES, "math_50_host.ts");

  // Step 1: compile TypeScript to WASM library
  const compileResult = await run(WASMTK_BIN, ["modc", fixtureSrc, "-n", fixtureWasm]);
  ok("modc compile succeeded", compileResult.success);
  if (!compileResult.success) {
    console.log(red("    stderr: " + compileResult.stderr.slice(0, 300)));
    return;
  }

  // Step 2: verify WIT file was generated
  let witSrc = "";
  try {
    witSrc = await Deno.readTextFile(fixtureWit);
  } catch { /**/ }
  ok(".wit file generated", witSrc.length > 0);
  ok(".wit has export add", witSrc.includes("export add:"));
  ok(".wit has export multiply", witSrc.includes("export multiply:"));

  // Step 3: generate bindings directly from WIT
  const ts = generateBindings(witSrc);
  await Deno.writeTextFile(fixtureBinding, ts);
  ok("binding written", true);

  // Step 4: write and run host test script
  const bindingUrl = toFileUrl(fixtureBinding).href;
  const wasmUrl = toFileUrl(fixtureWasm).href;
  const hostSrc = `
// auto-generated host runner for math_50 bindgen test
import { loadModule } from "${bindingUrl}";

const wasmBytes = await Deno.readFile(new URL("${wasmUrl}"));
const m = await loadModule(wasmBytes);
console.log(m.add(3, 4));
console.log(m.multiply(2.5, 4.0));
console.log(m.square(5));
`;
  await Deno.writeTextFile(hostRunner, hostSrc);
  const hostResult = await run("deno", ["run", "--allow-read", hostRunner]);
  ok("host runner succeeded", hostResult.success);
  if (!hostResult.success) {
    console.log(red("    stderr: " + hostResult.stderr.slice(0, 300)));
  }
  const lines = hostResult.stdout.trim().split("\n");
  ok("add(3,4) = 7", lines[0]?.trim() === "7");
  ok("multiply(2.5,4.0) = 10", lines[1]?.trim() === "10");
  ok("square(5) = 25", lines[2]?.trim() === "25");
}

// ── 10. Integration: bool fixture ────────────────────────────────────────────

async function testIntegrationBool() {
  console.log(yellow(bold("\n── Integration: booleans_50 compile + bindgen + host")));

  const fixtureSrc = join(FIXTURES, "booleans_50.ts");
  const fixtureWasm = join(FIXTURES, "booleans_50.wasm");
  const fixtureWit = join(FIXTURES, "booleans_50.wit");
  const fixtureBinding = join(FIXTURES, "booleans_50.bindings.ts");
  const hostRunner = join(FIXTURES, "booleans_50_host.ts");

  const compileResult = await run(WASMTK_BIN, ["modc", fixtureSrc, "-n", fixtureWasm]);
  ok("modc compile succeeded", compileResult.success);
  if (!compileResult.success) {
    console.log(red("    stderr: " + compileResult.stderr.slice(0, 300)));
    return;
  }

  let witSrc = "";
  try {
    witSrc = await Deno.readTextFile(fixtureWit);
  } catch { /**/ }
  ok(".wit file generated", witSrc.length > 0);
  ok(".wit has bool return", witSrc.includes("-> bool"));

  const ts = generateBindings(witSrc);
  await Deno.writeTextFile(fixtureBinding, ts);

  const bindingUrl2 = toFileUrl(fixtureBinding).href;
  const wasmUrl2 = toFileUrl(fixtureWasm).href;
  const hostSrc = `
import { loadModule } from "${bindingUrl2}";
const wasmBytes = await Deno.readFile(new URL("${wasmUrl2}"));
const m = await loadModule(wasmBytes);
console.log(m.isPositive(1.0));
console.log(m.isPositive(-1.0));
console.log(m.inRange(5.0, 1.0, 10.0));
console.log(m.inRange(0.0, 1.0, 10.0));
console.log(m.isEven(4));
console.log(m.isEven(3));
`;
  await Deno.writeTextFile(hostRunner, hostSrc);
  const hostResult = await run("deno", ["run", "--allow-read", hostRunner]);
  ok("host runner succeeded", hostResult.success);
  if (!hostResult.success) {
    console.log(red("    stderr: " + hostResult.stderr.slice(0, 300)));
  }
  const lines = hostResult.stdout.trim().split("\n");
  ok("isPositive(1.0) = true", lines[0]?.trim() === "true");
  ok("isPositive(-1.0) = false", lines[1]?.trim() === "false");
  ok("inRange(5,1,10) = true", lines[2]?.trim() === "true");
  ok("inRange(0,1,10) = false", lines[3]?.trim() === "false");
  ok("isEven(4) = true", lines[4]?.trim() === "true");
  ok("isEven(3) = false", lines[5]?.trim() === "false");
}

// ── 11. Integration: strings fixture ─────────────────────────────────────────

async function testIntegrationStrings() {
  console.log(yellow(bold("\n── Integration: strings_50 compile + bindgen + host")));

  const fixtureSrc = join(FIXTURES, "strings_50.ts");
  const fixtureWasm = join(FIXTURES, "strings_50.wasm");
  const fixtureWit = join(FIXTURES, "strings_50.wit");
  const fixtureBinding = join(FIXTURES, "strings_50.bindings.ts");
  const hostRunner = join(FIXTURES, "strings_50_host.ts");

  const compileResult = await run(WASMTK_BIN, ["modc", fixtureSrc, "-n", fixtureWasm]);
  ok("modc compile succeeded", compileResult.success);
  if (!compileResult.success) {
    console.log(red("    stderr: " + compileResult.stderr.slice(0, 300)));
    return;
  }

  let witSrc = "";
  try {
    witSrc = await Deno.readTextFile(fixtureWit);
  } catch { /**/ }
  ok(".wit file generated", witSrc.length > 0);
  ok(".wit has string param", witSrc.includes("name: string"));
  ok(".wit has string return", witSrc.includes("-> string"));

  const ts = generateBindings(witSrc);
  await Deno.writeTextFile(fixtureBinding, ts);
  contains("binding has _writeStr", ts, "_writeStr");
  contains("binding has cabi_realloc", ts, "_cabi_realloc");

  const bindingUrl3 = toFileUrl(fixtureBinding).href;
  const wasmUrl3 = toFileUrl(fixtureWasm).href;
  const hostSrc = `
import { loadModule } from "${bindingUrl3}";
const wasmBytes = await Deno.readFile(new URL("${wasmUrl3}"));
const m = await loadModule(wasmBytes);
console.log(m.greet("World"));
console.log(m.shout("hi"));
console.log(m.strLen("hello"));
`;
  await Deno.writeTextFile(hostRunner, hostSrc);
  const hostResult = await run("deno", ["run", "--allow-read", hostRunner]);
  ok("host runner succeeded", hostResult.success);
  if (!hostResult.success) {
    console.log(red("    stderr: " + hostResult.stderr.slice(0, 300)));
  }
  const lines = hostResult.stdout.trim().split("\n");
  ok("greet('World') = 'Hello, World!'", lines[0]?.trim() === "Hello, World!");
  ok("shout('hi') = 'hihi'", lines[1]?.trim() === "hihi");
  ok("strLen('hello') = 5", lines[2]?.trim() === "5");
}

// ── 12. Integration: imports fixture ─────────────────────────────────────────

async function testIntegrationImports() {
  console.log(yellow(bold("\n── Integration: imports_50 compile + bindgen + host")));

  const fixtureSrc = join(FIXTURES, "imports_50.ts");
  const fixtureWasm = join(FIXTURES, "imports_50.wasm");
  const fixtureWit = join(FIXTURES, "imports_50.wit");
  const fixtureBinding = join(FIXTURES, "imports_50.bindings.ts");
  const hostRunner = join(FIXTURES, "imports_50_host.ts");

  const compileResult = await run(WASMTK_BIN, ["modc", fixtureSrc, "-n", fixtureWasm]);
  ok("modc compile succeeded", compileResult.success);
  if (!compileResult.success) {
    console.log(red("    stderr: " + compileResult.stderr.slice(0, 300)));
    return;
  }

  let witSrc = "";
  try {
    witSrc = await Deno.readTextFile(fixtureWit);
  } catch { /**/ }
  ok(".wit file generated", witSrc.length > 0);
  ok(".wit has import section", witSrc.includes("import "));

  const ts = generateBindings(witSrc);
  await Deno.writeTextFile(fixtureBinding, ts);
  contains("binding has ModuleImports", ts, "ModuleImports");
  contains("envMul in interface", ts, "envMul?:");

  const bindingUrl4 = toFileUrl(fixtureBinding).href;
  const wasmUrl4 = toFileUrl(fixtureWasm).href;
  const hostSrc = `
import { loadModule } from "${bindingUrl4}";
const wasmBytes = await Deno.readFile(new URL("${wasmUrl4}"));
const m = await loadModule(wasmBytes, {
  env: {
    envMul: (a, b) => a * b,
    envAdd: (a, b) => a + b,
  }
});
console.log(m.scale(3.0, 4.0));
console.log(m.combine(10, 7));
`;
  await Deno.writeTextFile(hostRunner, hostSrc);
  const hostResult = await run("deno", ["run", "--allow-read", hostRunner]);
  ok("host runner succeeded", hostResult.success);
  if (!hostResult.success) {
    console.log(red("    stderr: " + hostResult.stderr.slice(0, 300)));
  }
  const lines = hostResult.stdout.trim().split("\n");
  ok("scale(3.0, 4.0) = 12", lines[0]?.trim() === "12");
  ok("combine(10, 7) = 17", lines[1]?.trim() === "17");
}

// ── 13. CLI: wasmtk bindgen command ──────────────────────────────────────────

async function testCli() {
  console.log(yellow(bold("\n── CLI: wasmtk bindgen")));

  // Use the math_50.wit from the integration test (generated above)
  const fixtureWit = join(FIXTURES, "math_50.wit");
  const cliBinding = join(FIXTURES, "math_50_cli.bindings.ts");

  let hasWit = false;
  try {
    await Deno.stat(fixtureWit);
    hasWit = true;
  } catch { /**/ }

  if (!hasWit) {
    ok("CLI test skipped (no .wit — run integration tests first)", true);
    return;
  }

  const result = await run(WASMTK_BIN, ["bindgen", fixtureWit, "-n", cliBinding]);
  ok("wasmtk bindgen succeeded", result.success);
  if (!result.success) {
    console.log(red("    stderr: " + result.stderr.slice(0, 300)));
    return;
  }
  let content = "";
  try {
    content = await Deno.readTextFile(cliBinding);
  } catch { /**/ }
  ok("binding file written", content.length > 0);
  contains("CLI binding has loadModule", content, "loadModule");
  contains("CLI binding has ModuleExports", content, "ModuleExports");
}

// ── Main ─────────────────────────────────────────────────────────────────────

console.log(cyan(bold("\nwasmtk Phase 50 — bindgen test suite\n")));

// Unit tests (synchronous)
testParseWitMath();
testParseWitBool();
testParseWitStrings();
testParseWitImports();
testGenBindingsMath();
testGenBindingsBool();
testGenBindingsStrings();
testGenBindingsImports();

// Integration tests (async — require wasmtk binary)
await testIntegrationMath();
await testIntegrationBool();
await testIntegrationStrings();
await testIntegrationImports();
await testCli();

// ── Summary ───────────────────────────────────────────────────────────────────

console.log(magenta(bold(`\n── Summary ────────────────────────────────────────`)));
console.log(`  Total:  ${passed + failed}`);
console.log(green(`  Passed: ${passed}`));
if (failed > 0) console.log(red(`  Failed: ${failed}`));
console.log(magenta(bold(`───────────────────────────────────────────────────\n`)));
if (failed > 0) Deno.exit(1);
