/**
 * jstyper_tests.ts — Phase 39 Test Suite
 *
 * Tests the jstyper .d.ts-based JS import pre-processor.
 * Covers: JS parsing, .d.ts parsing, skeleton generation,
 *         type mapping, any-policy modes, dry-run, full pipeline.
 *
 * Usage:
 *   deno run --allow-read --allow-write tests/jstyper_tests.ts
 */

import { join } from "jsr:@std/path";
import { bold, cyan, green, magenta, red, yellow } from "jsr:@std/fmt/colors";
import {
  generateSkeletonDts,
  generateTypedTs,
  parseJsFunctions,
  parseDtsFunctions,
  runJstyper,
} from "../src/jstyper.ts";

const FIXTURES = join(import.meta.dirname!, "jstyper_fixtures");

// ── Minimal assertion harness ─────────────────────────────────────────────────

let passed = 0;
let failed = 0;

function ok(desc: string, cond: boolean) {
  if (cond) {
    console.log(green(`  ✓ ${desc}`));
    passed++;
  } else {
    console.log(red(`  ✗ ${desc}`));
    failed++;
  }
}

// ── parseJsFunctions ─────────────────────────────────────────────────────────

function testParseJsFunctions() {
  console.log(yellow(bold("\n── parseJsFunctions")));

  const src = `
export function add(a, b) {
  return a + b;
}

function square(x) {
  return x * x;
}

export const lerp = (a, b, t) => {
  return a + (b - a) * t;
};
`;
  const fns = parseJsFunctions(src);
  ok("finds 3 functions", fns.length === 3);
  ok("add: exported, name correct", fns[0].isExported && fns[0].name === "add");
  ok("add: params [a, b]", JSON.stringify(fns[0].params) === '["a","b"]');
  ok("add: body contains return", fns[0].body.includes("return a + b"));
  ok("square: not exported", !fns[1].isExported && fns[1].name === "square");
  ok("lerp: exported arrow", fns[2].isExported && fns[2].name === "lerp");
  ok("lerp: params [a, b, t]", JSON.stringify(fns[2].params) === '["a","b","t"]');
  ok("lerp: body is braced block", fns[2].body.startsWith("{") && fns[2].body.endsWith("}"));
}

function testParseJsFunctionsArrowExpr() {
  console.log(yellow(bold("\n── parseJsFunctions — expression-body arrow")));

  const src = `export const double = (x) => x * 2;\n`;
  const fns = parseJsFunctions(src);
  ok("finds arrow expr function", fns.length === 1 && fns[0].name === "double");
  ok("body wrapped in braces", fns[0].body.includes("{") && fns[0].body.includes("return x * 2"));
}

function testParseJsFunctionsNested() {
  console.log(yellow(bold("\n── parseJsFunctions — nested braces")));

  const src = `
export function clamp(v, lo, hi) {
  if (v < lo) { return lo; }
  if (v > hi) { return hi; }
  return v;
}
`;
  const fns = parseJsFunctions(src);
  ok("finds clamp", fns.length === 1 && fns[0].name === "clamp");
  ok("body includes all branches", fns[0].body.includes("return lo") && fns[0].body.includes("return hi") && fns[0].body.includes("return v"));
}

// ── parseDtsFunctions ─────────────────────────────────────────────────────────

function testParseDtsFunctions() {
  console.log(yellow(bold("\n── parseDtsFunctions")));

  const dts = `
export declare function add(a: i32, b: i32): i32;
export declare function area(w: f64, h: f64): f64;
declare function secret(x: string): void;
`;
  const fns = parseDtsFunctions(dts);
  ok("finds 3 declarations", fns.length === 3);
  ok("add: i32 params", fns[0].params[0].type === "i32" && fns[0].params[1].type === "i32");
  ok("add: i32 return", fns[0].returnType === "i32");
  ok("area: f64 params", fns[1].params[0].type === "f64" && fns[1].params[1].type === "f64");
  ok("area: f64 return", fns[1].returnType === "f64");
  ok("secret: string param", fns[2].params[0].type === "string");
  ok("secret: void return", fns[2].returnType === "void");
}

function testParseDtsFunctionsNumberType() {
  console.log(yellow(bold("\n── parseDtsFunctions — number type")));

  const dts = `export declare function compute(x: number, y: number): number;\n`;
  const fns = parseDtsFunctions(dts);
  ok("finds 1 declaration", fns.length === 1);
  ok("params typed as number", fns[0].params[0].type === "number" && fns[0].params[1].type === "number");
  ok("return typed as number", fns[0].returnType === "number");
}

// ── generateSkeletonDts ───────────────────────────────────────────────────────

function testGenerateSkeletonDts() {
  console.log(yellow(bold("\n── generateSkeletonDts")));

  const fns = parseJsFunctions(`
export function foo(a, b) { return a; }
function bar(x) { return x; }
`);
  const dts = generateSkeletonDts(fns);
  ok("has @auto-generated header", dts.includes("@auto-generated by jstyper"));
  ok("foo: export declare with number params", dts.includes("export declare function foo(a: number, b: number): number;"));
  ok("bar: declare (no export)", dts.includes("declare function bar(x: number): number;"));
  ok("no extra i32/f64 in skeleton", !dts.includes("i32") && !dts.includes("f64"));
}

function testGenerateSkeletonDtsNoParams() {
  console.log(yellow(bold("\n── generateSkeletonDts — zero-param function")));

  const fns = parseJsFunctions(`export function getPI() { return 3.14159; }\n`);
  const dts = generateSkeletonDts(fns);
  ok("zero-param declaration correct", dts.includes("export declare function getPI(): number;"));
}

// ── generateTypedTs ───────────────────────────────────────────────────────────

function testGenerateTypedTsBasic() {
  console.log(yellow(bold("\n── generateTypedTs — basic i32/f64")));

  const jsFns = parseJsFunctions(`
export function add(a, b) {
  return a + b;
}
`);
  const dtsFns = parseDtsFunctions(`export declare function add(a: i32, b: i32): i32;\n`);
  const { source, warnings } = generateTypedTs(jsFns, dtsFns, "warn");
  ok("no warnings", warnings.length === 0);
  ok("signature has i32 types", source.includes("function add(a: i32, b: i32): i32"));
  ok("body preserved", source.includes("return a + b"));
  ok("export keyword present", source.includes("export function add"));
}

function testGenerateTypedTsNumberMapping() {
  console.log(yellow(bold("\n── generateTypedTs — number→f64 mapping")));

  const jsFns = parseJsFunctions(`export function area(w, h) { return w * h; }\n`);
  const dtsFns = parseDtsFunctions(`export declare function area(w: number, h: number): number;\n`);
  const { source, warnings } = generateTypedTs(jsFns, dtsFns, "warn");
  ok("params mapped to f64", source.includes("w: f64") && source.includes("h: f64"));
  ok("return mapped to f64", source.includes("): f64"));
  ok("no warnings for number type", warnings.length === 0);
}

function testGenerateTypedTsMissingDeclaration() {
  console.log(yellow(bold("\n── generateTypedTs — missing .d.ts entry")));

  const jsFns = parseJsFunctions(`
export function known(a) { return a; }
export function unknown(b) { return b; }
`);
  const dtsFns = parseDtsFunctions(`export declare function known(a: i32): i32;\n`);
  const { source, warnings } = generateTypedTs(jsFns, dtsFns, "warn");
  ok("known: included", source.includes("function known"));
  ok("unknown: excluded", !source.includes("function unknown"));
  ok("warning for missing declaration", warnings.some((w) => w.includes("no declaration") && w.includes("unknown")));
}

// ── any-policy modes ──────────────────────────────────────────────────────────

function testAnyPolicySkip() {
  console.log(yellow(bold("\n── any-policy=skip")));

  const jsFns = parseJsFunctions(`
export function safe(a, b) { return a + b; }
export function hasAnyParam(x, data) { return x; }
export function hasAnyReturn(x) { return x; }
`);
  const dtsFns = parseDtsFunctions(`
export declare function safe(a: i32, b: i32): i32;
export declare function hasAnyParam(x: i32, data: any): i32;
export declare function hasAnyReturn(x: i32): any;
`);
  const { source, warnings } = generateTypedTs(jsFns, dtsFns, "skip");
  ok("safe: included", source.includes("function safe"));
  ok("hasAnyParam: excluded", !source.includes("function hasAnyParam"));
  ok("hasAnyReturn: excluded", !source.includes("function hasAnyReturn"));
  ok("skip warnings emitted", warnings.filter((w) => w.includes("skipping")).length === 2);
}

function testAnyPolicyWarn() {
  console.log(yellow(bold("\n── any-policy=warn")));

  const jsFns = parseJsFunctions(`export function process(x, data) { return x; }\n`);
  const dtsFns = parseDtsFunctions(`export declare function process(x: i32, data: any): i32;\n`);
  const { source, warnings } = generateTypedTs(jsFns, dtsFns, "warn");
  ok("function included", source.includes("function process"));
  ok("any param mapped to i32", source.includes("data: i32"));
  ok("warning emitted", warnings.some((w) => w.includes("data") && w.includes("any")));
}

function testAnyPolicyDefault() {
  console.log(yellow(bold("\n── any-policy=default")));

  const jsFns = parseJsFunctions(`export function process(x, data) { return x; }\n`);
  const dtsFns = parseDtsFunctions(`export declare function process(x: i32, data: any): i32;\n`);
  const { source, warnings } = generateTypedTs(jsFns, dtsFns, "default");
  ok("function included", source.includes("function process"));
  ok("any param mapped to i32", source.includes("data: i32"));
  ok("no warnings with default policy", warnings.length === 0);
}

// ── File I/O tests ────────────────────────────────────────────────────────────

async function testDryRun() {
  console.log(yellow(bold("\n── runJstyper --dry-run")));

  const jsPath = join(FIXTURES, "basicmath.js");
  const wouldWrite = jsPath.replace(/\.js$/, ".ts");
  try { await Deno.remove(wouldWrite); } catch { /* ok */ }

  await runJstyper(jsPath, { dryRun: true });

  let exists = false;
  try { await Deno.stat(wouldWrite); exists = true; } catch { /* expected */ }
  ok("dry-run: .ts file not written", !exists);
}

async function testDtsOnlyMode() {
  console.log(yellow(bold("\n── runJstyper --dts-only")));

  const jsPath = join(FIXTURES, "basicmath.js");
  const dtsOut = join(FIXTURES, "basicmath_gen.d.ts");
  try { await Deno.remove(dtsOut); } catch { /* ok */ }

  await runJstyper(jsPath, { dtsOnly: true, outPath: dtsOut });

  let content = "";
  try { content = await Deno.readTextFile(dtsOut); } catch { /* */ }

  ok("skeleton .d.ts written", content.length > 0);
  ok("contains @auto-generated", content.includes("@auto-generated by jstyper"));
  ok("add declaration present", content.includes("function add(a: number, b: number): number;"));
  ok("multiply declaration present", content.includes("function multiply(a: number, b: number): number;"));
  ok("square declaration present", content.includes("function square(a: number): number;"));

  try { await Deno.remove(dtsOut); } catch { /* */ }
}

async function testDtsOnlyDryRun() {
  console.log(yellow(bold("\n── runJstyper --dts-only --dry-run")));

  const jsPath = join(FIXTURES, "basicmath.js");
  const dtsOut = join(FIXTURES, "basicmath_dtsonly_dry.d.ts");
  try { await Deno.remove(dtsOut); } catch { /* ok */ }

  await runJstyper(jsPath, { dtsOnly: true, dryRun: true, outPath: dtsOut });

  let exists = false;
  try { await Deno.stat(dtsOut); exists = true; } catch { /* expected */ }
  ok("dts-only dry-run: file not written", !exists);
}

async function testFullPipelineBasicmath() {
  console.log(yellow(bold("\n── runJstyper full pipeline (basicmath)")));

  const jsPath = join(FIXTURES, "basicmath.js");
  const tsOut = join(FIXTURES, "basicmath_out.ts");
  try { await Deno.remove(tsOut); } catch { /* ok */ }

  await runJstyper(jsPath, { outPath: tsOut });

  let content = "";
  try { content = await Deno.readTextFile(tsOut); } catch { /* */ }

  ok(".ts file written", content.length > 0);
  ok("add: i32 signature", content.includes("function add(a: i32, b: i32): i32"));
  ok("multiply: f64 signature", content.includes("function multiply(a: f64, b: f64): f64"));
  ok("square: i32 signature", content.includes("function square(a: i32): i32"));
  ok("bodies preserved (add)", content.includes("return a + b"));
  ok("bodies preserved (multiply)", content.includes("return a * b"));
  ok("bodies preserved (square)", content.includes("return a * a"));

  try { await Deno.remove(tsOut); } catch { /* */ }
}

async function testFullPipelineNumberTypes() {
  console.log(yellow(bold("\n── runJstyper full pipeline (numbertypes — number→f64)")));

  const jsPath = join(FIXTURES, "numbertypes.js");
  const tsOut = join(FIXTURES, "numbertypes_out.ts");
  try { await Deno.remove(tsOut); } catch { /* ok */ }

  await runJstyper(jsPath, { outPath: tsOut });

  let content = "";
  try { content = await Deno.readTextFile(tsOut); } catch { /* */ }

  ok(".ts file written", content.length > 0);
  ok("area: f64 (number→f64)", content.includes("function area(w: f64, h: f64): f64"));
  ok("perimeter: f64 (number→f64)", content.includes("function perimeter(w: f64, h: f64): f64"));
  ok("hypotenuse: f64 (number→f64)", content.includes("function hypotenuse(a: f64, b: f64): f64"));

  try { await Deno.remove(tsOut); } catch { /* */ }
}

async function testAnyPolicySkipPipeline() {
  console.log(yellow(bold("\n── runJstyper --any-policy=skip pipeline")));

  const jsPath = join(FIXTURES, "anypolicy.js");
  const tsOut = join(FIXTURES, "anypolicy_skip_out.ts");
  try { await Deno.remove(tsOut); } catch { /* ok */ }

  await runJstyper(jsPath, { anyPolicy: "skip", outPath: tsOut });

  let content = "";
  try { content = await Deno.readTextFile(tsOut); } catch { /* */ }

  ok(".ts file written", content.length > 0);
  ok("safe function included", content.includes("function safe"));
  ok("hasAnyParam excluded (any param)", !content.includes("function hasAnyParam"));
  ok("hasAnyReturn excluded (any return)", !content.includes("function hasAnyReturn"));

  try { await Deno.remove(tsOut); } catch { /* */ }
}

async function testAnyPolicyWarnPipeline() {
  console.log(yellow(bold("\n── runJstyper --any-policy=warn pipeline")));

  const jsPath = join(FIXTURES, "anypolicy.js");
  const tsOut = join(FIXTURES, "anypolicy_warn_out.ts");
  try { await Deno.remove(tsOut); } catch { /* ok */ }

  await runJstyper(jsPath, { anyPolicy: "warn", outPath: tsOut });

  let content = "";
  try { content = await Deno.readTextFile(tsOut); } catch { /* */ }

  ok(".ts file written", content.length > 0);
  ok("safe included", content.includes("function safe"));
  ok("hasAnyParam included (any→i32)", content.includes("function hasAnyParam") && content.includes("data: i32"));
  ok("hasAnyReturn included (any→i32)", content.includes("function hasAnyReturn") && content.includes("): i32"));

  try { await Deno.remove(tsOut); } catch { /* */ }
}

// ── Entry point ───────────────────────────────────────────────────────────────

async function main() {
  console.log(magenta(bold("\n🔬 Phase 39 jstyper Test Suite\n")));

  // Unit tests (pure functions — no file I/O)
  testParseJsFunctions();
  testParseJsFunctionsArrowExpr();
  testParseJsFunctionsNested();
  testParseDtsFunctions();
  testParseDtsFunctionsNumberType();
  testGenerateSkeletonDts();
  testGenerateSkeletonDtsNoParams();
  testGenerateTypedTsBasic();
  testGenerateTypedTsNumberMapping();
  testGenerateTypedTsMissingDeclaration();
  testAnyPolicySkip();
  testAnyPolicyWarn();
  testAnyPolicyDefault();

  // File I/O tests
  await testDryRun();
  await testDtsOnlyMode();
  await testDtsOnlyDryRun();
  await testFullPipelineBasicmath();
  await testFullPipelineNumberTypes();
  await testAnyPolicySkipPipeline();
  await testAnyPolicyWarnPipeline();

  // Summary
  const bar = "=".repeat(42);
  console.log("\n" + magenta(bold(bar)));
  console.log(magenta(bold("       PHASE 39 TEST SUMMARY")));
  console.log(magenta(bold(bar)));
  console.log(`${green("  Passed:")} ${bold(String(passed))}`);
  console.log(
    failed > 0
      ? `${red("  Failed:")} ${bold(String(failed))}`
      : `${cyan("  Failed:")} ${bold(String(failed))}`,
  );
  console.log(magenta(bold(bar)));

  if (failed > 0) Deno.exit(1);
}

main();
