;; mathlib.wat — Phase 38 extended Math library for wasic
;; Exports: sin, cos, tan, asin, acos, atan, atan2,
;;          exp, log, log2, log10, cbrt,
;;          sinh, cosh, tanh, asinh, acosh, atanh,
;;          expm1, log1p, random
;;
;; All functions operate on f64. random() uses a module-level xorshift64 PRNG.
;; This module is compiled to mathlib.wasm and auto-bundled by wasic when any
;; of these Math.* functions appear in the compiled TypeScript source.
;;
;; To regenerate mathlib.wasm:
;;   wasmtk convert src/wasm/mathlib.wat  (output goes to src/wasm/mathlib.wasm)
;; To regenerate mathlib_bytes.ts:
;;   deno run --allow-read --allow-write scripts/gen_mathlib_bytes.ts
(module
  ;; ── RNG state (xorshift64 seed) ─────────────────────────────────────────────
  (global $__rng_state (mut i64) (i64.const 0x6C62272E07BB0142))
  ;; ── trig argument-reduction output (r, rt) — see $__trig_reduce ─────────────
  (global $__tr  (mut f64) (f64.const 0.0))
  (global $__trt (mut f64) (f64.const 0.0))

  ;; ── Math.random — xorshift64, returns f64 in [0, 1) ────────────────────────
  (func $random (export "random") (result f64)
    (local $s i64)
    (local.set $s (global.get $__rng_state))
    (local.set $s (i64.xor (local.get $s) (i64.shl  (local.get $s) (i64.const 13))))
    (local.set $s (i64.xor (local.get $s) (i64.shr_u (local.get $s) (i64.const 7))))
    (local.set $s (i64.xor (local.get $s) (i64.shl  (local.get $s) (i64.const 17))))
    (global.set $__rng_state (local.get $s))
    (f64.sub
      (f64.reinterpret_i64
        (i64.or (i64.shr_u (local.get $s) (i64.const 12)) (i64.const 0x3FF0000000000000)))
      (f64.const 1.0))
  )

  ;; ── fdlibm trig: __kernel_sin/__kernel_cos + Veltkamp-split argument reduction ──
  ;; Reduction: n = rint(x * 2/pi); r + rt = x - n*(pi/2) accumulated in double-double
  ;; using the 7 fdlibm PIo2[] 24-bit chunks. n is Veltkamp-split (nhi<=24 sig bits +
  ;; nlo) so every nhi*PIo2[i] / nlo*PIo2[i] product is EXACT, and each subtraction is
  ;; Sterbenz-exact — so r is accurate to full precision. Result matches V8 to <=1 ULP
  ;; for |x| < ~1e12 (and stays ~14 sig-figs out to 1e15). Pure arithmetic: no table
  ;; lookup, no linear memory, no Payne-Hanek — safe to splice into the merged module.
  ;; ── Correctly-rounded sin/cos via double-double (dd) arithmetic ─────────────
  ;; Matches the IEEE-754 correctly-rounded result (validated bit-for-bit vs a
  ;; BigInt fixed-point oracle over |x| < 1e12). This is the canonical value every
  ;; correct libm agrees on — max accuracy + max cross-language compatibility.
  ;; All dd helpers use Veltkamp two-product (no FMA needed) and return (hi, lo)
  ;; via WASM multi-value. Argument reduction is the table-free Veltkamp n-split
  ;; producing a dd remainder r; the dd Taylor kernels then round to nearest.
  (func $__hiw (param $x f64) (result i32)
    (i32.and (i32.wrap_i64 (i64.shr_u (i64.reinterpret_f64 (local.get $x)) (i64.const 32)))
             (i32.const 0x7fffffff)))
  ;; twoSum(a,b) -> (s, err)  [exact:  a+b = s+err]
  (func $__ts (param $a f64) (param $b f64) (result f64 f64)
    (local $s f64) (local $bb f64)
    (local.set $s (f64.add (local.get $a) (local.get $b)))
    (local.set $bb (f64.sub (local.get $s) (local.get $a)))
    (local.get $s)
    (f64.add (f64.sub (local.get $a) (f64.sub (local.get $s) (local.get $bb)))
             (f64.sub (local.get $b) (local.get $bb))))
  ;; twoProd(a,b) -> (p, err)  via Veltkamp split (exact:  a*b = p+err)
  (func $__tp (param $a f64) (param $b f64) (result f64 f64)
    (local $p f64) (local $c f64) (local $ah f64) (local $al f64) (local $bh f64) (local $bl f64)
    (local.set $p (f64.mul (local.get $a) (local.get $b)))
    (local.set $c (f64.mul (f64.const 134217729.0) (local.get $a)))
    (local.set $ah (f64.sub (local.get $c) (f64.sub (local.get $c) (local.get $a))))
    (local.set $al (f64.sub (local.get $a) (local.get $ah)))
    (local.set $c (f64.mul (f64.const 134217729.0) (local.get $b)))
    (local.set $bh (f64.sub (local.get $c) (f64.sub (local.get $c) (local.get $b))))
    (local.set $bl (f64.sub (local.get $b) (local.get $bh)))
    (local.get $p)
    (f64.add (f64.add (f64.add
      (f64.sub (f64.mul (local.get $ah) (local.get $bh)) (local.get $p))
      (f64.mul (local.get $ah) (local.get $bl)))
      (f64.mul (local.get $al) (local.get $bh)))
      (f64.mul (local.get $al) (local.get $bl))))
  ;; ddAdd((ah,al),(bh,bl)) -> (hi,lo)
  (func $__dda (param $ah f64) (param $al f64) (param $bh f64) (param $bl f64) (result f64 f64)
    (local $s f64) (local $e f64)
    (call $__ts (local.get $ah) (local.get $bh)) (local.set $e) (local.set $s)
    (local.set $e (f64.add (local.get $e) (f64.add (local.get $al) (local.get $bl))))
    (call $__ts (local.get $s) (local.get $e)))
  ;; ddMul((ah,al),(bh,bl)) -> (hi,lo)
  (func $__ddm (param $ah f64) (param $al f64) (param $bh f64) (param $bl f64) (result f64 f64)
    (local $p f64) (local $e f64)
    (call $__tp (local.get $ah) (local.get $bh)) (local.set $e) (local.set $p)
    (local.set $e (f64.add (local.get $e)
      (f64.add (f64.mul (local.get $ah) (local.get $bl)) (f64.mul (local.get $al) (local.get $bh)))))
    (call $__ts (local.get $p) (local.get $e)))
  ;; ddRecipInt(d) -> (hi,lo)  ~ 1/d in dd
  (func $__ddri (param $d f64) (result f64 f64)
    (local $h f64) (local $p f64) (local $e f64) (local $res f64)
    (local.set $h (f64.div (f64.const 1.0) (local.get $d)))
    (call $__tp (local.get $h) (local.get $d)) (local.set $e) (local.set $p)
    (local.set $res (f64.sub (f64.sub (f64.const 1.0) (local.get $p)) (local.get $e)))
    (call $__ts (local.get $h) (f64.mul (local.get $res) (local.get $h))))
  ;; ddMulD((ah,al), b) -> (hi,lo)
  (func $__ddmd (param $ah f64) (param $al f64) (param $b f64) (result f64 f64)
    (local $p f64) (local $e f64)
    (call $__tp (local.get $ah) (local.get $b)) (local.set $e) (local.set $p)
    (local.set $e (f64.add (local.get $e) (f64.mul (local.get $al) (local.get $b))))
    (call $__ts (local.get $p) (local.get $e)))
  ;; ddDiv((ah,al),(bh,bl)) -> (hi,lo)   3-step dd quotient
  (func $__dddiv (param $ah f64) (param $al f64) (param $bh f64) (param $bl f64) (result f64 f64)
    (local $q1 f64) (local $q2 f64) (local $q3 f64)
    (local $ph f64) (local $pl f64) (local $rh f64) (local $rl f64) (local $h f64) (local $l f64)
    (local.set $q1 (f64.div (local.get $ah) (local.get $bh)))
    (call $__ddmd (local.get $bh) (local.get $bl) (local.get $q1)) (local.set $pl) (local.set $ph)
    (call $__dda (local.get $ah) (local.get $al) (f64.neg (local.get $ph)) (f64.neg (local.get $pl))) (local.set $rl) (local.set $rh)
    (local.set $q2 (f64.div (local.get $rh) (local.get $bh)))
    (call $__ddmd (local.get $bh) (local.get $bl) (local.get $q2)) (local.set $pl) (local.set $ph)
    (call $__dda (local.get $rh) (local.get $rl) (f64.neg (local.get $ph)) (f64.neg (local.get $pl))) (local.set $rl) (local.set $rh)
    (local.set $q3 (f64.div (local.get $rh) (local.get $bh)))
    (call $__ts (local.get $q1) (local.get $q2)) (local.set $l) (local.set $h)
    (local.set $l (f64.add (local.get $l) (local.get $q3)))
    (call $__ts (local.get $h) (local.get $l)))
  ;; ddsin(r) -> (hi,lo)   dd Taylor, |r| <= pi/4
  (func $__ddsin (param $rh f64) (param $rl f64) (result f64 f64)
    (local $r2h f64) (local $r2l f64) (local $th f64) (local $tl f64) (local $sh f64) (local $sl f64)
    (local $ch f64) (local $cl f64) (local $k i32) (local $d f64)
    (call $__ddm (local.get $rh) (local.get $rl) (local.get $rh) (local.get $rl)) (local.set $r2l) (local.set $r2h)
    (local.set $th (local.get $rh)) (local.set $tl (local.get $rl))
    (local.set $sh (local.get $rh)) (local.set $sl (local.get $rl))
    (local.set $k (i32.const 1))
    (block $done (loop $lp
      (br_if $done (i32.gt_u (local.get $k) (i32.const 11)))
      (call $__ddm (local.get $th) (local.get $tl) (local.get $r2h) (local.get $r2l)) (local.set $tl) (local.set $th)
      (local.set $d (f64.convert_i32_s (i32.mul (i32.const -1)
        (i32.mul (i32.mul (i32.const 2) (local.get $k)) (i32.add (i32.mul (i32.const 2) (local.get $k)) (i32.const 1))))))
      (call $__ddri (local.get $d)) (local.set $cl) (local.set $ch)
      (call $__ddm (local.get $th) (local.get $tl) (local.get $ch) (local.get $cl)) (local.set $tl) (local.set $th)
      (call $__dda (local.get $sh) (local.get $sl) (local.get $th) (local.get $tl)) (local.set $sl) (local.set $sh)
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (br $lp)))
    (local.get $sh) (local.get $sl))
  ;; ddcos(r) -> (hi,lo)   dd Taylor, |r| <= pi/4
  (func $__ddcos (param $rh f64) (param $rl f64) (result f64 f64)
    (local $r2h f64) (local $r2l f64) (local $th f64) (local $tl f64) (local $sh f64) (local $sl f64)
    (local $ch f64) (local $cl f64) (local $k i32) (local $d f64)
    (call $__ddm (local.get $rh) (local.get $rl) (local.get $rh) (local.get $rl)) (local.set $r2l) (local.set $r2h)
    (local.set $th (f64.const 1.0)) (local.set $tl (f64.const 0.0))
    (local.set $sh (f64.const 1.0)) (local.set $sl (f64.const 0.0))
    (local.set $k (i32.const 1))
    (block $done (loop $lp
      (br_if $done (i32.gt_u (local.get $k) (i32.const 11)))
      (call $__ddm (local.get $th) (local.get $tl) (local.get $r2h) (local.get $r2l)) (local.set $tl) (local.set $th)
      (local.set $d (f64.convert_i32_s (i32.mul (i32.const -1)
        (i32.mul (i32.sub (i32.mul (i32.const 2) (local.get $k)) (i32.const 1)) (i32.mul (i32.const 2) (local.get $k))))))
      (call $__ddri (local.get $d)) (local.set $cl) (local.set $ch)
      (call $__ddm (local.get $th) (local.get $tl) (local.get $ch) (local.get $cl)) (local.set $tl) (local.set $th)
      (call $__dda (local.get $sh) (local.get $sl) (local.get $th) (local.get $tl)) (local.set $sl) (local.set $sh)
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (br $lp)))
    (local.get $sh) (local.get $sl))
  ;; reduce |x| -> dd remainder (r in $__tr/$__trt), return quadrant n&3
  (func $__trig_reduce (param $x f64) (result i32)
    (local $n f64) (local $c f64) (local $nhi f64) (local $nlo f64)
    (local $h f64) (local $l f64) (local $p f64) (local $s f64) (local $i i32) (local $pio f64)
    (local.set $n (f64.nearest (f64.mul (local.get $x) (f64.const 6.36619772367581382433e-01))))
    (local.set $c (f64.mul (f64.const 536870913.0) (local.get $n)))
    (local.set $nhi (f64.sub (local.get $c) (f64.sub (local.get $c) (local.get $n))))
    (local.set $nlo (f64.sub (local.get $n) (local.get $nhi)))
    (local.set $h (local.get $x))
    (local.set $l (f64.const 0.0))
    (local.set $i (i32.const 0))
    (block $done (loop $lp
      (br_if $done (i32.ge_u (local.get $i) (i32.const 7)))
      (local.set $pio
        (select (f64.const 1.57079625129699707031e+00)
        (select (f64.const 7.54978941586159635335e-08)
        (select (f64.const 5.39030252995776476554e-15)
        (select (f64.const 3.28200341580791294123e-22)
        (select (f64.const 1.27065575308067607349e-29)
        (select (f64.const 1.22933308981111328932e-36)
                (f64.const 2.73370053816464559624e-44)
                (i32.eq (local.get $i) (i32.const 5)))
                (i32.eq (local.get $i) (i32.const 4)))
                (i32.eq (local.get $i) (i32.const 3)))
                (i32.eq (local.get $i) (i32.const 2)))
                (i32.eq (local.get $i) (i32.const 1)))
                (i32.eqz (local.get $i))))
      (local.set $p (f64.mul (local.get $nhi) (local.get $pio)))
      (local.set $s (f64.sub (local.get $h) (local.get $p)))
      (local.set $l (f64.add (local.get $l) (f64.sub (f64.sub (local.get $h) (local.get $s)) (local.get $p))))
      (local.set $h (local.get $s))
      (local.set $p (f64.mul (local.get $nlo) (local.get $pio)))
      (local.set $s (f64.sub (local.get $h) (local.get $p)))
      (local.set $l (f64.add (local.get $l) (f64.sub (f64.sub (local.get $h) (local.get $s)) (local.get $p))))
      (local.set $h (local.get $s))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $lp)))
    (call $__ts (local.get $h) (local.get $l))
    (global.set $__trt)
    (global.set $__tr)
    (i32.and (i32.wrap_i64 (i64.trunc_f64_s (local.get $n))) (i32.const 3)))
  ;; ── Math.sin ────────────────────────────────────────────────────────────────
  (func $sin (export "sin") (param $x f64) (result f64)
    (local $ix i32) (local $q i32) (local $sh f64) (local $sl f64)
    (local.set $ix (call $__hiw (local.get $x)))
    (if (i32.le_u (local.get $ix) (i32.const 0x3fe921fb))
      (then (call $__ddsin (local.get $x) (f64.const 0.0)) (local.set $sl) (local.set $sh)
            (return (f64.add (local.get $sh) (local.get $sl)))))
    (if (i32.ge_u (local.get $ix) (i32.const 0x7ff00000))
      (then (return (f64.sub (local.get $x) (local.get $x)))))
    (local.set $q (call $__trig_reduce (local.get $x)))
    (if (i32.and (local.get $q) (i32.const 1))
      (then (call $__ddcos (global.get $__tr) (global.get $__trt)) (local.set $sl) (local.set $sh))
      (else (call $__ddsin (global.get $__tr) (global.get $__trt)) (local.set $sl) (local.set $sh)))
    (if (result f64) (i32.ge_u (local.get $q) (i32.const 2))
      (then (f64.neg (f64.add (local.get $sh) (local.get $sl))))
      (else (f64.add (local.get $sh) (local.get $sl)))))
  ;; ── Math.cos ────────────────────────────────────────────────────────────────
  (func $cos (export "cos") (param $x f64) (result f64)
    (local $ix i32) (local $q i32) (local $sh f64) (local $sl f64)
    (local.set $ix (call $__hiw (local.get $x)))
    (if (i32.le_u (local.get $ix) (i32.const 0x3fe921fb))
      (then (call $__ddcos (local.get $x) (f64.const 0.0)) (local.set $sl) (local.set $sh)
            (return (f64.add (local.get $sh) (local.get $sl)))))
    (if (i32.ge_u (local.get $ix) (i32.const 0x7ff00000))
      (then (return (f64.sub (local.get $x) (local.get $x)))))
    (local.set $q (call $__trig_reduce (local.get $x)))
    (if (i32.and (local.get $q) (i32.const 1))
      (then (call $__ddsin (global.get $__tr) (global.get $__trt)) (local.set $sl) (local.set $sh))
      (else (call $__ddcos (global.get $__tr) (global.get $__trt)) (local.set $sl) (local.set $sh)))
    ;; cos negates for quadrants 1 and 2
    (if (result f64) (i32.or (i32.eq (local.get $q) (i32.const 1)) (i32.eq (local.get $q) (i32.const 2)))
      (then (f64.neg (f64.add (local.get $sh) (local.get $sl))))
      (else (f64.add (local.get $sh) (local.get $sl)))))
  ;; ── Math.tan — correctly-rounded: dd sin(r)/cos(r) with quadrant sign ────────
  (func $tan (export "tan") (param $x f64) (result f64)
    (local $ix i32) (local $q i32) (local $rh f64) (local $rl f64)
    (local $sh f64) (local $sl f64) (local $ch f64) (local $cl f64) (local $th f64) (local $tl f64)
    (local.set $ix (call $__hiw (local.get $x)))
    (if (i32.ge_u (local.get $ix) (i32.const 0x7ff00000))
      (then (return (f64.sub (local.get $x) (local.get $x)))))
    (if (i32.le_u (local.get $ix) (i32.const 0x3fe921fb))
      (then (local.set $rh (local.get $x)) (local.set $rl (f64.const 0.0)) (local.set $q (i32.const 0)))
      (else (local.set $q (call $__trig_reduce (local.get $x)))
            (local.set $rh (global.get $__tr)) (local.set $rl (global.get $__trt))))
    (call $__ddsin (local.get $rh) (local.get $rl)) (local.set $sl) (local.set $sh)
    (call $__ddcos (local.get $rh) (local.get $rl)) (local.set $cl) (local.set $ch)
    (if (result f64) (i32.and (local.get $q) (i32.const 1))
      (then ;; odd quadrant: tan = -(cos/sin)
        (call $__dddiv (local.get $ch) (local.get $cl) (local.get $sh) (local.get $sl)) (local.set $tl) (local.set $th)
        (f64.neg (f64.add (local.get $th) (local.get $tl))))
      (else ;; even quadrant: tan = sin/cos
        (call $__dddiv (local.get $sh) (local.get $sl) (local.get $ch) (local.get $cl)) (local.set $tl) (local.set $th)
        (f64.add (local.get $th) (local.get $tl)))))

  ;; ── Math.atan — two-stage range reduction + fdlibm aT[0..10] minimax poly ─────
  (func $atan (export "atan") (param $x f64) (result f64)
    (local $s i32)
    (local $z f64)
    (local $z2 f64)
    (local $r f64)
    (local $t f64)
    (local $comp i32)
    (local $mid i32)
    (local.set $s (i32.const 1))
    (local.set $z (local.get $x))
    (local.set $comp (i32.const 0))
    (local.set $mid (i32.const 0))
    ;; Handle negative input
    (if (f64.lt (local.get $x) (f64.const 0.0))
      (then
        (local.set $s (i32.const -1))
        (local.set $z (f64.neg (local.get $x)))))
    ;; Stage 1: complement reduction for z > 1: atan(z) = pi/2 - atan(1/z)
    (if (f64.gt (local.get $z) (f64.const 1.0))
      (then
        (local.set $z (f64.div (f64.const 1.0) (local.get $z)))
        (local.set $comp (i32.const 1))))
    ;; Stage 2: mid-range reduction for z > tan(pi/8): atan(z) = pi/4 + atan((z-1)/(z+1))
    (if (f64.gt (local.get $z) (f64.const 0.4142135623730951))
      (then
        (local.set $z (f64.div
          (f64.sub (local.get $z) (f64.const 1.0))
          (f64.add (local.get $z) (f64.const 1.0))))
        (local.set $mid (i32.const 1))))
    (local.set $z2 (f64.mul (local.get $z) (local.get $z)))
    ;; Horner from innermost aT[10] to aT[0]
    (local.set $t (f64.const  1.62858201153657823623e-2))
    (local.set $t (f64.add (f64.const -3.65315727442169155270e-2) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const  4.97687214484516269815e-2) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const -5.83357013380200465019e-2) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const  6.66107313738753491996e-2) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const -7.69187620504482999330e-2) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const  9.09088713343650656196e-2) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const -1.11111104054623557880e-1) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const  1.42857142725034663711e-1) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const -1.99999999998764832476e-1) (f64.mul (local.get $z2) (local.get $t))))
    (local.set $t (f64.add (f64.const  3.33333333333329318027e-1) (f64.mul (local.get $z2) (local.get $t))))
    ;; r = z - z³ * t
    (local.set $r (f64.sub (local.get $z)
      (f64.mul (f64.mul (local.get $z) (local.get $z2)) (local.get $t))))
    ;; Adjust for which reductions were applied
    (if (i32.and (local.get $comp) (local.get $mid))
      (then (local.set $r (f64.sub (f64.const 0.7853981633974483) (local.get $r))))
      (else
        (if (local.get $comp)
          (then (local.set $r (f64.sub (f64.const 1.5707963267948966) (local.get $r))))
          (else
            (if (local.get $mid)
              (then (local.set $r (f64.add (f64.const 0.7853981633974483) (local.get $r)))))))))
    ;; Apply sign
    (if (i32.eq (local.get $s) (i32.const -1))
      (then (local.set $r (f64.neg (local.get $r)))))
    (local.get $r)
  )

  ;; ── Math.atan2(y, x) ─────────────────────────────────────────────────────────
  (func $atan2 (export "atan2") (param $y f64) (param $x f64) (result f64)
    (local $r f64)
    ;; Special case: x = 0
    (if (f64.eq (local.get $x) (f64.const 0.0))
      (then
        (if (f64.gt (local.get $y) (f64.const 0.0))
          (then (return (f64.const 1.5707963267948966))))
        (if (f64.lt (local.get $y) (f64.const 0.0))
          (then (return (f64.const -1.5707963267948966))))
        (return (f64.const 0.0))))
    (local.set $r (call $atan (f64.div (local.get $y) (local.get $x))))
    ;; Adjust for x < 0 quadrants
    (if (f64.lt (local.get $x) (f64.const 0.0))
      (then
        (if (f64.ge (local.get $y) (f64.const 0.0))
          (then (local.set $r (f64.add (local.get $r) (f64.const 3.141592653589793))))
          (else (local.set $r (f64.sub (local.get $r) (f64.const 3.141592653589793)))))))
    (local.get $r)
  )

  ;; ── Math.asin — atan(x/sqrt(1-x²)) for |x|<=0.7, complement otherwise ───────
  (func $asin (export "asin") (param $x f64) (result f64)
    (local $neg i32)
    (local $a f64)
    (local $r f64)
    (local.set $neg (i32.const 0))
    (local.set $a (local.get $x))
    (if (f64.lt (local.get $x) (f64.const 0.0))
      (then
        (local.set $neg (i32.const 1))
        (local.set $a (f64.neg (local.get $x)))))
    (if (f64.le (local.get $a) (f64.const 0.7))
      (then
        (local.set $r (call $atan
          (f64.div (local.get $a)
            (f64.sqrt (f64.sub (f64.const 1.0) (f64.mul (local.get $a) (local.get $a))))))))
      (else
        (local.set $r (f64.sub (f64.const 1.5707963267948966)
          (f64.mul (f64.const 2.0)
            (call $asin
              (f64.sqrt (f64.mul (f64.const 0.5)
                (f64.sub (f64.const 1.0) (local.get $a))))))))))
    (if (i32.eq (local.get $neg) (i32.const 1))
      (then (local.set $r (f64.neg (local.get $r)))))
    (local.get $r)
  )

  ;; ── Math.acos = pi/2 - asin(x) ───────────────────────────────────────────────
  (func $acos (export "acos") (param $x f64) (result f64)
    (f64.sub (f64.const 1.5707963267948966) (call $asin (local.get $x)))
  )

  ;; scalbn(x, n) = x * 2^n, correctly rounded (musl-style, safe for subnormal/overflow)
  (func $__scalbn (param $x f64) (param $n i32) (result f64)
    (local $y f64)
    (local.set $y (local.get $x))
    (if (i32.gt_s (local.get $n) (i32.const 1023))
      (then
        (local.set $y (f64.mul (local.get $y) (f64.const 0x1p1023)))
        (local.set $n (i32.sub (local.get $n) (i32.const 1023)))
        (if (i32.gt_s (local.get $n) (i32.const 1023))
          (then
            (local.set $y (f64.mul (local.get $y) (f64.const 0x1p1023)))
            (local.set $n (i32.sub (local.get $n) (i32.const 1023)))
            (if (i32.gt_s (local.get $n) (i32.const 1023)) (then (local.set $n (i32.const 1023))))))))
    (if (i32.lt_s (local.get $n) (i32.const -1022))
      (then
        (local.set $y (f64.mul (local.get $y) (f64.const 0x1p-969)))
        (local.set $n (i32.add (local.get $n) (i32.const 969)))
        (if (i32.lt_s (local.get $n) (i32.const -1022))
          (then
            (local.set $y (f64.mul (local.get $y) (f64.const 0x1p-969)))
            (local.set $n (i32.add (local.get $n) (i32.const 969)))
            (if (i32.lt_s (local.get $n) (i32.const -1022)) (then (local.set $n (i32.const -1022))))))))
    (f64.mul (local.get $y)
      (f64.reinterpret_i64 (i64.shl (i64.extend_i32_s (i32.add (local.get $n) (i32.const 1023))) (i64.const 52)))))
  ;; crRound(hi, lo, k) = correctly-rounded (hi+lo) * 2^k  (normal + subnormal + overflow)
  (func $__cr (param $hi f64) (param $lo f64) (param $k i32) (result f64)
    (local $neg i32) (local $m f64) (local $probe f64)
    (local $whi f64) (local $wlo f64) (local $fl f64) (local $frac f64) (local $mm f64)
    (if (f64.eq (local.get $hi) (f64.const 0)) (then (return (f64.const 0))))
    (if (f64.lt (local.get $hi) (f64.const 0))
      (then (local.set $neg (i32.const 1)) (local.set $hi (f64.neg (local.get $hi))) (local.set $lo (f64.neg (local.get $lo)))))
    (local.set $probe (call $__scalbn (local.get $hi) (local.get $k)))
    (if (f64.eq (local.get $probe) (f64.const inf))
      (then (return (select (f64.const -inf) (f64.const inf) (local.get $neg)))))
    (if (f64.ge (local.get $probe) (f64.const 0x1p-1022))
      (then
        (local.set $m (call $__scalbn (f64.add (local.get $hi) (local.get $lo)) (local.get $k))))
      (else
        (local.set $whi (call $__scalbn (local.get $hi) (i32.add (local.get $k) (i32.const 1074))))
        (local.set $wlo (call $__scalbn (local.get $lo) (i32.add (local.get $k) (i32.const 1074))))
        (local.set $fl (f64.floor (local.get $whi)))
        (local.set $frac (f64.add (f64.sub (local.get $whi) (local.get $fl)) (local.get $wlo)))
        (block $d1 (loop $a1 (br_if $d1 (f64.lt (local.get $frac) (f64.const 1)))
          (local.set $frac (f64.sub (local.get $frac) (f64.const 1))) (local.set $fl (f64.add (local.get $fl) (f64.const 1))) (br $a1)))
        (block $d2 (loop $a2 (br_if $d2 (f64.ge (local.get $frac) (f64.const 0)))
          (local.set $frac (f64.add (local.get $frac) (f64.const 1))) (local.set $fl (f64.sub (local.get $fl) (f64.const 1))) (br $a2)))
        (local.set $mm (local.get $fl))
        (if (f64.gt (local.get $frac) (f64.const 0.5))
          (then (local.set $mm (f64.add (local.get $fl) (f64.const 1))))
          (else (if (f64.eq (local.get $frac) (f64.const 0.5))
            (then (if (f64.ne (f64.mul (f64.floor (f64.mul (local.get $fl) (f64.const 0.5))) (f64.const 2)) (local.get $fl))
                    (then (local.set $mm (f64.add (local.get $fl) (f64.const 1)))))))))
        (local.set $m (f64.mul (local.get $mm) (f64.const 0x1p-1074)))))
    (if (result f64) (local.get $neg) (then (f64.neg (local.get $m))) (else (local.get $m))))
  ;; ── Math.exp — correctly-rounded: dd Cody-Waite reduction + dd Taylor + crRound ─
  (func $exp (export "exp") (param $x f64) (result f64)
    (local $k i32) (local $kf f64) (local $klh f64) (local $kll f64) (local $rh f64) (local $rl f64)
    (local $th f64) (local $tl f64) (local $sh f64) (local $sl f64) (local $ch f64) (local $cl f64) (local $n i32)
    (if (f64.ne (local.get $x) (local.get $x)) (then (return (local.get $x))))
    (if (f64.eq (local.get $x) (f64.const inf)) (then (return (f64.const inf))))
    (if (f64.eq (local.get $x) (f64.const -inf)) (then (return (f64.const 0))))
    (if (f64.ge (local.get $x) (f64.const 709.7827128933841)) (then (return (f64.const inf))))
    (if (f64.le (local.get $x) (f64.const -745.1332191019413)) (then (return (f64.const 0))))
    (local.set $kf (f64.nearest (f64.mul (local.get $x) (f64.const 1.4426950408889634))))
    (local.set $k (i32.trunc_f64_s (local.get $kf)))
    (call $__ddmd (f64.const 0.6931471805599453) (f64.const 2.3190468138462996e-17) (local.get $kf)) (local.set $kll) (local.set $klh)
    (call $__dda (local.get $x) (f64.const 0) (f64.neg (local.get $klh)) (f64.neg (local.get $kll))) (local.set $rl) (local.set $rh)
    (local.set $th (f64.const 1)) (local.set $tl (f64.const 0))
    (local.set $sh (f64.const 1)) (local.set $sl (f64.const 0))
    (local.set $n (i32.const 1))
    (block $done (loop $lp
      (br_if $done (i32.gt_u (local.get $n) (i32.const 22)))
      (call $__ddm (local.get $th) (local.get $tl) (local.get $rh) (local.get $rl)) (local.set $tl) (local.set $th)
      (call $__ddri (f64.convert_i32_s (local.get $n))) (local.set $cl) (local.set $ch)
      (call $__ddm (local.get $th) (local.get $tl) (local.get $ch) (local.get $cl)) (local.set $tl) (local.set $th)
      (call $__dda (local.get $sh) (local.get $sl) (local.get $th) (local.get $tl)) (local.set $sl) (local.set $sh)
      (local.set $n (i32.add (local.get $n) (i32.const 1)))
      (br $lp)))
    (call $__cr (local.get $sh) (local.get $sl) (local.get $k)))

  ;; __logdd(x) -> dd natural log; assumes x finite > 0 (x==1 yields (0,0))
  (func $__logdd (param $x f64) (result f64 f64)
    (local $b i64) (local $exp i32) (local $e i32) (local $m f64)
    (local $nh f64) (local $nl f64) (local $dh f64) (local $dl f64) (local $sh f64) (local $sl f64)
    (local $s2h f64) (local $s2l f64) (local $th f64) (local $tl f64) (local $ph f64) (local $pl f64)
    (local $k i32) (local $lmh f64) (local $lml f64) (local $elh f64) (local $ell f64)
    (local.set $b (i64.reinterpret_f64 (local.get $x)))
    (local.set $exp (i32.wrap_i64 (i64.and (i64.shr_u (local.get $b) (i64.const 52)) (i64.const 0x7ff))))
    (if (i32.eqz (local.get $exp))
      (then
        (local.set $x (f64.mul (local.get $x) (f64.const 0x1p54)))
        (local.set $b (i64.reinterpret_f64 (local.get $x)))
        (local.set $exp (i32.wrap_i64 (i64.and (i64.shr_u (local.get $b) (i64.const 52)) (i64.const 0x7ff))))
        (local.set $e (i32.sub (i32.sub (local.get $exp) (i32.const 1023)) (i32.const 54))))
      (else (local.set $e (i32.sub (local.get $exp) (i32.const 1023)))))
    (local.set $m (f64.reinterpret_i64 (i64.or (i64.and (local.get $b) (i64.const 0x800fffffffffffff)) (i64.const 0x3ff0000000000000))))
    (if (f64.ge (local.get $m) (f64.const 1.4142135623730951))
      (then (local.set $m (f64.mul (local.get $m) (f64.const 0.5))) (local.set $e (i32.add (local.get $e) (i32.const 1)))))
    (call $__ts (local.get $m) (f64.const -1)) (local.set $nl) (local.set $nh)
    (call $__ts (local.get $m) (f64.const 1)) (local.set $dl) (local.set $dh)
    (call $__dddiv (local.get $nh) (local.get $nl) (local.get $dh) (local.get $dl)) (local.set $sl) (local.set $sh)
    (call $__ddm (local.get $sh) (local.get $sl) (local.get $sh) (local.get $sl)) (local.set $s2l) (local.set $s2h)
    (local.set $th (f64.const 1)) (local.set $tl (f64.const 0))
    (local.set $ph (f64.const 1)) (local.set $pl (f64.const 0))   ;; sum accumulator
    (local.set $k (i32.const 1))
    (block $done (loop $lp
      (br_if $done (i32.gt_u (local.get $k) (i32.const 18)))
      (call $__ddm (local.get $th) (local.get $tl) (local.get $s2h) (local.get $s2l)) (local.set $tl) (local.set $th)
      (call $__ddri (f64.convert_i32_s (i32.add (i32.mul (i32.const 2) (local.get $k)) (i32.const 1)))) (local.set $lml) (local.set $lmh)
      (call $__ddm (local.get $th) (local.get $tl) (local.get $lmh) (local.get $lml)) (local.set $lml) (local.set $lmh)
      (call $__dda (local.get $ph) (local.get $pl) (local.get $lmh) (local.get $lml)) (local.set $pl) (local.set $ph)
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (br $lp)))
    ;; logm = ddm(ddmd(s,2), sum)
    (call $__ddmd (local.get $sh) (local.get $sl) (f64.const 2)) (local.set $lml) (local.set $lmh)
    (call $__ddm (local.get $lmh) (local.get $lml) (local.get $ph) (local.get $pl)) (local.set $lml) (local.set $lmh)
    ;; el2 = ddmd([LN2H,LN2L], e)
    (call $__ddmd (f64.const 0.6931471805599453) (f64.const 2.3190468138462996e-17) (f64.convert_i32_s (local.get $e))) (local.set $ell) (local.set $elh)
    (call $__dda (local.get $elh) (local.get $ell) (local.get $lmh) (local.get $lml)))
  ;; ── Math.log ─────────────────────────────────────────────────────────────────
  (func $log (export "log") (param $x f64) (result f64)
    (local $rh f64) (local $rl f64)
    (if (f64.ne (local.get $x) (local.get $x)) (then (return (local.get $x))))
    (if (f64.lt (local.get $x) (f64.const 0)) (then (return (f64.sub (local.get $x) (local.get $x)))))
    (if (f64.eq (local.get $x) (f64.const 0)) (then (return (f64.const -inf))))
    (if (f64.eq (local.get $x) (f64.const inf)) (then (return (f64.const inf))))
    (call $__logdd (local.get $x)) (local.set $rl) (local.set $rh)
    (f64.add (local.get $rh) (local.get $rl)))
  ;; ── Math.log2 = log(x) * (1/ln2) in dd ───────────────────────────────────────
  (func $log2 (export "log2") (param $x f64) (result f64)
    (local $rh f64) (local $rl f64)
    (if (f64.ne (local.get $x) (local.get $x)) (then (return (local.get $x))))
    (if (f64.lt (local.get $x) (f64.const 0)) (then (return (f64.sub (local.get $x) (local.get $x)))))
    (if (f64.eq (local.get $x) (f64.const 0)) (then (return (f64.const -inf))))
    (if (f64.eq (local.get $x) (f64.const inf)) (then (return (f64.const inf))))
    (call $__logdd (local.get $x)) (local.set $rl) (local.set $rh)
    (call $__ddm (local.get $rh) (local.get $rl) (f64.const 1.4426950408889634) (f64.const 2.0355273740931033e-17)) (local.set $rl) (local.set $rh)
    (f64.add (local.get $rh) (local.get $rl)))
  ;; ── Math.log10 = log(x) * (1/ln10) in dd ─────────────────────────────────────
  (func $log10 (export "log10") (param $x f64) (result f64)
    (local $rh f64) (local $rl f64)
    (if (f64.ne (local.get $x) (local.get $x)) (then (return (local.get $x))))
    (if (f64.lt (local.get $x) (f64.const 0)) (then (return (f64.sub (local.get $x) (local.get $x)))))
    (if (f64.eq (local.get $x) (f64.const 0)) (then (return (f64.const -inf))))
    (if (f64.eq (local.get $x) (f64.const inf)) (then (return (f64.const inf))))
    (call $__logdd (local.get $x)) (local.set $rl) (local.set $rh)
    (call $__ddm (local.get $rh) (local.get $rl) (f64.const 0.4342944819032518) (f64.const 1.098319650216765e-17)) (local.set $rl) (local.set $rh)
    (f64.add (local.get $rh) (local.get $rl)))

  ;; ── Math.cbrt — exp(log(x)/3) initial guess + 3 Newton steps ────────────────
  (func $cbrt (export "cbrt") (param $x f64) (result f64)
    (local $neg i32)
    (local $y f64)
    (local.set $neg (i32.const 0))
    (if (f64.eq (local.get $x) (f64.const 0.0)) (then (return (f64.const 0.0))))
    (if (f64.gt (local.get $x) (f64.const 1.7976931348623157e308)) (then (return (local.get $x))))
    (if (f64.lt (local.get $x) (f64.const 0.0))
      (then
        (local.set $neg (i32.const 1))
        (local.set $x (f64.neg (local.get $x)))))
    (local.set $y (call $exp (f64.div (call $log (local.get $x)) (f64.const 3.0))))
    ;; Newton: y = (2y + x/y²) / 3
    (local.set $y (f64.div
      (f64.add (f64.mul (f64.const 2.0) (local.get $y))
               (f64.div (local.get $x) (f64.mul (local.get $y) (local.get $y))))
      (f64.const 3.0)))
    (local.set $y (f64.div
      (f64.add (f64.mul (f64.const 2.0) (local.get $y))
               (f64.div (local.get $x) (f64.mul (local.get $y) (local.get $y))))
      (f64.const 3.0)))
    (local.set $y (f64.div
      (f64.add (f64.mul (f64.const 2.0) (local.get $y))
               (f64.div (local.get $x) (f64.mul (local.get $y) (local.get $y))))
      (f64.const 3.0)))
    (if (i32.eq (local.get $neg) (i32.const 1))
      (then (local.set $y (f64.neg (local.get $y)))))
    (local.get $y)
  )

  ;; ── Math.sinh / cosh / tanh ──────────────────────────────────────────────────
  (func $sinh (export "sinh") (param $x f64) (result f64)
    (local $ep f64)
    (local.set $ep (call $exp (local.get $x)))
    (f64.mul (f64.const 0.5) (f64.sub (local.get $ep) (f64.div (f64.const 1.0) (local.get $ep))))
  )
  (func $cosh (export "cosh") (param $x f64) (result f64)
    (local $ep f64)
    (local.set $ep (call $exp (local.get $x)))
    (f64.mul (f64.const 0.5) (f64.add (local.get $ep) (f64.div (f64.const 1.0) (local.get $ep))))
  )
  (func $tanh (export "tanh") (param $x f64) (result f64)
    (local $e2x f64)
    (local.set $e2x (call $exp (f64.mul (f64.const 2.0) (local.get $x))))
    (f64.div
      (f64.sub (local.get $e2x) (f64.const 1.0))
      (f64.add (local.get $e2x) (f64.const 1.0)))
  )

  ;; ── Math.asinh / acosh / atanh ───────────────────────────────────────────────
  (func $asinh (export "asinh") (param $x f64) (result f64)
    (call $log
      (f64.add (local.get $x)
        (f64.sqrt (f64.add (f64.mul (local.get $x) (local.get $x)) (f64.const 1.0)))))
  )
  (func $acosh (export "acosh") (param $x f64) (result f64)
    (call $log
      (f64.add (local.get $x)
        (f64.sqrt (f64.sub (f64.mul (local.get $x) (local.get $x)) (f64.const 1.0)))))
  )
  (func $atanh (export "atanh") (param $x f64) (result f64)
    (f64.mul (f64.const 0.5)
      (f64.sub
        (call $log (f64.add (f64.const 1.0) (local.get $x)))
        (call $log (f64.sub (f64.const 1.0) (local.get $x)))))
  )

  ;; ── Math.expm1 — Taylor series for |x|<1, exp(x)-1 otherwise ────────────────
  (func $expm1 (export "expm1") (param $x f64) (result f64)
    (local $ax f64)
    (local $t f64)
    (local.set $ax (f64.abs (local.get $x)))
    (if (f64.lt (local.get $ax) (f64.const 2.220446049250313e-16)) (then (return (local.get $x))))
    (if (f64.ge (local.get $ax) (f64.const 1.0))
      (then (return (f64.sub (call $exp (local.get $x)) (f64.const 1.0)))))
    ;; Horner for x*(1 + x/2! + x²/3! + ... + x^7/8!) from innermost
    (local.set $t (f64.const 1.984126984126984e-4))
    (local.set $t (f64.add (f64.const 1.388888888888889e-3)  (f64.mul (local.get $x) (local.get $t))))
    (local.set $t (f64.add (f64.const 8.333333333333333e-3)  (f64.mul (local.get $x) (local.get $t))))
    (local.set $t (f64.add (f64.const 4.1666666666666664e-2) (f64.mul (local.get $x) (local.get $t))))
    (local.set $t (f64.add (f64.const 1.6666666666666666e-1) (f64.mul (local.get $x) (local.get $t))))
    (local.set $t (f64.add (f64.const 5.0e-1)               (f64.mul (local.get $x) (local.get $t))))
    (local.set $t (f64.add (f64.const 1.0)                  (f64.mul (local.get $x) (local.get $t))))
    (f64.mul (local.get $x) (local.get $t))
  )

  ;; ── Math.log1p — accurate log(1+x) for small x ───────────────────────────────
  (func $log1p (export "log1p") (param $x f64) (result f64)
    (if (f64.lt (f64.abs (local.get $x)) (f64.const 2.220446049250313e-16))
      (then (return (local.get $x))))
    (call $log (f64.add (f64.const 1.0) (local.get $x)))
  )
)
