// auto-generated by wasmtk bindgen — do not edit manually
// source: fnany-50
// deno-lint-ignore-file

export interface ModuleExports {
  getDoubler(): any;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  const _mem = exp["memory"] as WebAssembly.Memory;
  const _cabi_realloc = exp["cabi_realloc"] as ((ptr: number, oldSize: number, align: number, newSize: number) => number);
  function _writeStr(s: string): [number, number] {
    const b = new TextEncoder().encode(s);
    const ptr = _cabi_realloc(0, 0, 1, b.length);
    new Uint8Array(_mem.buffer).set(b, ptr);
    return [ptr, b.length];
  }
  const _dynNumber = exp["dynNumber"] as (n: number) => number;
  const _dynNumberValue = exp["dynNumberValue"] as (h: number) => number;
  const _dynString = exp["dynString"] as (p: number, l: number) => number;
  const _dynStrBytes = exp["dynStrBytes"] as (h: number) => number;
  const _dynStrLen = exp["dynStrLen"] as (h: number) => number;
  const _dynBool = exp["dynBool"] as (b: number) => number;
  const _dynToBool = exp["dynToBool"] as (h: number) => number;
  const _dynTag = exp["dynTag"] as (h: number) => number;
  const _dynNull = exp["dynNull"] as () => number;
  const _dynUndefined = exp["dynUndefined"] as () => number;
  const _dynArray = exp["dynArray"] as () => number;
  const _dynArrLen = exp["dynArrLen"] as (h: number) => number;
  const _dynArrGet = exp["dynArrGet"] as (h: number, i: number) => number;
  const _dynPush = exp["dynPush"] as (h: number, v: number) => void;
  const _dynObject = exp["dynObject"] as () => number;
  const _dynObjLen = exp["dynObjLen"] as (h: number) => number;
  const _dynObjKeyPtr = exp["dynObjKeyPtr"] as (h: number, i: number) => number;
  const _dynObjKeyLen = exp["dynObjKeyLen"] as (h: number, i: number) => number;
  const _dynObjValAt = exp["dynObjValAt"] as (h: number, i: number) => number;
  const _dynSet = exp["dynSet"] as (o: number, p: number, l: number, v: number) => void;
  const _dynApply = exp["dynApply"] as (fn: number, args: number) => number;
  const _dynGcPin = exp["dynGcPin"] as (h: number) => number;
  const _dynGcUnpin = exp["dynGcUnpin"] as (slot: number) => void;
  const _pinReg = new FinalizationRegistry((pin: number) => _dynGcUnpin(pin));
  const _dec = new TextDecoder();
  function _box(v: unknown): number {
    if (typeof v === "number") return _dynNumber(v);
    if (typeof v === "boolean") return _dynBool(v ? 1 : 0);
    if (typeof v === "string") { const [p, l] = _writeStr(v); return _dynString(p, l); }
    if (v === null) return _dynNull();
    if (v === undefined) return _dynUndefined();
    if (Array.isArray(v)) { const h = _dynArray(); for (const e of v) _dynPush(h, _box(e)); return h; }
    if (typeof v === "object") {
      const h = _dynObject(); const o = v as Record<string, unknown>;
      for (const k of Object.keys(o)) { const [p, l] = _writeStr(k); _dynSet(h, p, l, _box(o[k])); }
      return h;
    }
    return _dynNumber(0); // functions/symbols — not marshalled
  }
  function _unbox(h: number): unknown {
    switch (_dynTag(h)) {
      case 3: return _dynNumberValue(h);
      case 4: return _dec.decode(new Uint8Array(_mem.buffer, _dynStrBytes(h), _dynStrLen(h)));
      case 2: return _dynToBool(h) !== 0;
      case 1: return null;
      case 0: return undefined;
      case 5: { const n = _dynArrLen(h); const a: unknown[] = []; for (let i = 0; i < n; i++) a.push(_unbox(_dynArrGet(h, i))); return a; }
      case 6: {
        const n = _dynObjLen(h); const o: Record<string, unknown> = {};
        for (let i = 0; i < n; i++) {
          const k = _dec.decode(new Uint8Array(_mem.buffer, _dynObjKeyPtr(h, i), _dynObjKeyLen(h, i)));
          o[k] = _unbox(_dynObjValAt(h, i));
        }
        return o;
      }
      case 7: {
        const _pin = _dynGcPin(h);
        const _fn = ((...args: unknown[]): unknown => {
          const _a = _dynArray();
          for (const _x of args) _dynPush(_a, _box(_x));
          return _unbox(_dynApply(h, _a));
        }) as ((...a: unknown[]) => unknown) & { release(): void };
        _fn.release = () => _dynGcUnpin(_pin);
        _pinReg.register(_fn, _pin);
        return _fn;
      }
      default: return h; // unknown tag — opaque handle
    }
  }
  return {
    getDoubler(): any { return _unbox((exp["getDoubler"] as (...a: unknown[]) => unknown)() as number); },
  };
}
