// auto-generated by wasmtk bindgen — do not edit manually
// source: imports-50
// deno-lint-ignore-file

export interface ModuleExports {
  scale(x: number, factor: number): number;
  combine(a: number, b: number): number;
}

export interface ModuleImports {
  env?: {
    envMul?: (p0: number, p1: number) => number;
    envAdd?: (p0: number, p1: number) => number;
  };
}

export async function loadModule(
  source: string | URL | BufferSource,
  imports?: ModuleImports,
): Promise<ModuleExports> {
  const env: Record<string, unknown> = {};
  env["env_mul"] = (_a0, _a1: number) => (imports?.env?.envMul?.(_a0, _a1) ?? 0);
  env["env_add"] = (_a0, _a1: number) => (imports?.env?.envAdd?.(_a0, _a1) ?? 0);
  const importObj = { env };
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  return {
    scale(x: number, factor: number): number { return (exp["scale"] as (...a: unknown[]) => unknown)(x, factor) as number; },
    combine(a: number, b: number): number { return (exp["combine"] as (...a: unknown[]) => unknown)(a, b) as number; },
  };
}
