// auto-generated by wasmtk bindgen — do not edit manually
// source: strings-50
// deno-lint-ignore-file

export interface ModuleExports {
  greet(name: string): string;
  shout(msg: string): string;
  strLen(s: string): number;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  const _mem = exp["memory"] as WebAssembly.Memory;
  const _cabi_realloc = exp["cabi_realloc"] as ((ptr: number, oldSize: number, align: number, newSize: number) => number);
  function _writeStr(s: string): [number, number] {
    const b = new TextEncoder().encode(s);
    const ptr = _cabi_realloc(0, 0, 1, b.length);
    new Uint8Array(_mem.buffer).set(b, ptr);
    return [ptr, b.length];
  }
  return {
    greet(name: string): string {
      const _r = (exp["greet"] as (...a: unknown[]) => unknown)(..._writeStr(name)) as number;
      const _v = new DataView(_mem.buffer);
      const _s = new TextDecoder().decode(new Uint8Array(_mem.buffer, _v.getInt32(_r, true), _v.getInt32(_r + 4, true)));
      (exp["cabi_post_greet"] as ((p: number) => void))(_r);
      return _s;
    },
    shout(msg: string): string {
      const _r = (exp["shout"] as (...a: unknown[]) => unknown)(..._writeStr(msg)) as number;
      const _v = new DataView(_mem.buffer);
      const _s = new TextDecoder().decode(new Uint8Array(_mem.buffer, _v.getInt32(_r, true), _v.getInt32(_r + 4, true)));
      (exp["cabi_post_shout"] as ((p: number) => void))(_r);
      return _s;
    },
    strLen(s: string): number { return (exp["strLen"] as (...a: unknown[]) => unknown)(..._writeStr(s)) as number; },
  };
}
