// auto-generated by wasmtk bindgen — do not edit manually
// source: async-hybrid-core
// deno-lint-ignore-file

export interface ModuleExports {
  step1(x: number): number;
  process(data: number): number;
  scale(x: number): number;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  return {
    step1(x: number): number { return (exp["step1"] as (...a: unknown[]) => unknown)(x) as number; },
    process(data: number): number { return (exp["process"] as (...a: unknown[]) => unknown)(data) as number; },
    scale(x: number): number { return (exp["scale"] as (...a: unknown[]) => unknown)(x) as number; },
  };
}
