// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file


import { loadModule } from "./async_hybrid_core.bindings.ts";

const lib = await loadModule(new URL("./async_hybrid_core.wasm", import.meta.url));

// A hybrid fixture exercising ASYNC @wasm functions routed into the wasic core (Phase 13.5).
// async functions used to be skipped; now wasic compiles async/await, so they are routed via a
// synchronous unwrapping wrapper in the core module. The host calls them through `lib` as normal.




// Runtime-only host code — stays in TypeScript.
function describe(label: string, value: unknown): void {
  console.log(`${label}: ${value}`);
}

const r: i32 = await lib.process(4);
const s: f64 = await lib.scale(2.0);

describe("process(4)", r);
describe("scale(2.0)", s);
