// auto-generated by wasmtk bindgen — do not edit manually
// source: dynamic-partial-hybrid-core
// deno-lint-ignore-file

export interface ModuleExports {
  goodDynamic(n: number): number;
  plus1(x: number): number;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  return {
    goodDynamic(n: number): number { return (exp["goodDynamic"] as (...a: unknown[]) => unknown)(n) as number; },
    plus1(x: number): number { return (exp["plus1"] as (...a: unknown[]) => unknown)(x) as number; },
  };
}
