// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

export function goodDynamic(n: f64): f64 {
  const x: any = eval("6 * 7");
  return (x as f64) + n;
}

export function plus1(x: f64): f64 {
  return x + 1;
}
