// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

export function evalScaled(n: f64): f64 {
  const base: any = eval("6 * 7"); // 42, computed by the dynrt evaluator
  const scaled: any = base + n; // dynamic addition (any + f64)
  return scaled as f64; // unbox the result back to f64
}

export function double(x: f64): f64 {
  return x * 2;
}
