// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

export function greet(name: string): string {
  return "Hello, " + name + "!";
}

export function strLen(s: string): i32 {
  return s.length;
}
