// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file


import { loadModule } from "./strings_hybrid_core.bindings.ts";

const lib = await loadModule(new URL("./strings_hybrid_core.wasm", import.meta.url));

// Hybrid example with string params + async (skipped) function



// @wasm — async: should be skipped with a warning
async function fetchRemote(): Promise<string> {
  return "data";
}

// Runtime side
const msg = lib.greet("World");
const len = lib.strLen("test");
console.log(msg);
console.log("len:", len);
