// auto-generated by wasmtk bindgen — do not edit manually
// source: booleans-50
// deno-lint-ignore-file

export interface ModuleExports {
  isPositive(x: number): boolean;
  inRange(v: number, lo: number, hi: number): boolean;
  isEven(n: number): boolean;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  return {
    isPositive(x: number): boolean { return (exp["isPositive"] as (...a: unknown[]) => unknown)(x) !== 0; },
    inRange(v: number, lo: number, hi: number): boolean { return (exp["inRange"] as (...a: unknown[]) => unknown)(v, lo, hi) !== 0; },
    isEven(n: number): boolean { return (exp["isEven"] as (...a: unknown[]) => unknown)(n) !== 0; },
  };
}
