// auto-generated by wasmtk bindgen — do not edit manually
// source: hostfn-50
// deno-lint-ignore-file

export interface ModuleExports {
  applyTwice(fn: any, x: any): any;
  combine(fn: any, a: any, b: any): any;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const _hostFns: ((...a: unknown[]) => unknown)[] = [];
  let _hostCallImpl: (fnIdx: number, argsArr: number) => number = () => 0;
  let _hostPrintImpl: (ptr: number, len: number) => void = () => {};
  let _wasiMem: WebAssembly.Memory | undefined;
  const _wasiView = () => new DataView((_wasiMem as WebAssembly.Memory).buffer);
  const _wasiU8 = () => new Uint8Array((_wasiMem as WebAssembly.Memory).buffer);
  const _wasiBase = {
    fd_write(fd: number, iovs: number, iovsLen: number, nwritten: number): number {
      const v = _wasiView(), mem = _wasiU8();
      let written = 0, text = "";
      for (let i = 0; i < iovsLen; i++) {
        const p = v.getInt32(iovs + i * 8, true), l = v.getInt32(iovs + i * 8 + 4, true);
        text += new TextDecoder().decode(mem.subarray(p, p + l)); written += l;
      }
      const out = text.replace(/\n$/, "");
      if (fd === 2) console.error(out); else console.log(out);
      v.setInt32(nwritten, written, true); return 0;
    },
    random_get(buf: number, len: number): number {
      const mem = _wasiU8();
      for (let i = 0; i < len; i++) mem[buf + i] = (Math.random() * 256) | 0;
      return 0;
    },
    clock_time_get(_id: number, _prec: number, timePtr: number): number {
      _wasiView().setBigInt64(timePtr, BigInt(Date.now()) * 1000000n, true); return 0;
    },
    proc_exit(code: number): number { throw new Error("wasm proc_exit(" + code + ")"); },
  } as Record<string, (...a: number[]) => number>;
  const _wasi = new Proxy(_wasiBase, { get: (t, k: string) => k in t ? t[k] : () => 0 });

  const env: Record<string, unknown> = {};
  env["__host_call"] = (fnIdx: number, argsArr: number) => _hostCallImpl(fnIdx, argsArr);
  env["__host_print"] = (ptr: number, len: number) => _hostPrintImpl(ptr, len);
  const importObj = { env, wasi_snapshot_preview1: _wasi };
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  _wasiMem = exp["memory"] as WebAssembly.Memory | undefined;
  (exp["_initialize"] as (() => void) | undefined)?.();
  const _mem = exp["memory"] as WebAssembly.Memory;
  _hostPrintImpl = (ptr: number, len: number): void => {
    let _s = new TextDecoder().decode(new Uint8Array(_mem.buffer, ptr, len));
    if (_s.endsWith("\n")) _s = _s.slice(0, -1);
    console.log(_s);
  };
  const _cabi_realloc = exp["cabi_realloc"] as ((ptr: number, oldSize: number, align: number, newSize: number) => number);
  function _writeStr(s: string): [number, number] {
    const b = new TextEncoder().encode(s);
    const ptr = _cabi_realloc(0, 0, 1, b.length);
    new Uint8Array(_mem.buffer).set(b, ptr);
    return [ptr, b.length];
  }
  const _dynNumber = exp["dynNumber"] as (n: number) => number;
  const _dynNumberValue = exp["dynNumberValue"] as (h: number) => number;
  const _dynString = exp["dynString"] as (p: number, l: number) => number;
  const _dynStrBytes = exp["dynStrBytes"] as (h: number) => number;
  const _dynStrLen = exp["dynStrLen"] as (h: number) => number;
  const _dynBool = exp["dynBool"] as (b: number) => number;
  const _dynToBool = exp["dynToBool"] as (h: number) => number;
  const _dynTag = exp["dynTag"] as (h: number) => number;
  const _dynNull = exp["dynNull"] as () => number;
  const _dynUndefined = exp["dynUndefined"] as () => number;
  const _dynArray = exp["dynArray"] as () => number;
  const _dynArrLen = exp["dynArrLen"] as (h: number) => number;
  const _dynArrGet = exp["dynArrGet"] as (h: number, i: number) => number;
  const _dynPush = exp["dynPush"] as (h: number, v: number) => void;
  const _dynObject = exp["dynObject"] as () => number;
  const _dynObjLen = exp["dynObjLen"] as (h: number) => number;
  const _dynObjKeyPtr = exp["dynObjKeyPtr"] as (h: number, i: number) => number;
  const _dynObjKeyLen = exp["dynObjKeyLen"] as (h: number, i: number) => number;
  const _dynObjValAt = exp["dynObjValAt"] as (h: number, i: number) => number;
  const _dynSet = exp["dynSet"] as (o: number, p: number, l: number, v: number) => void;
  const _dynApply = exp["dynApply"] as (fn: number, args: number) => number;
  const _dynGcPin = exp["dynGcPin"] as (h: number) => number;
  const _dynGcUnpin = exp["dynGcUnpin"] as (slot: number) => void;
  const _pinReg = new FinalizationRegistry((pin: number) => _dynGcUnpin(pin));
  const _dynMakeHostFn = exp["dynMakeHostFn"] as (index: number) => number;
  const _dec = new TextDecoder();
  function _box(v: unknown): number {
    if (typeof v === "number") return _dynNumber(v);
    if (typeof v === "boolean") return _dynBool(v ? 1 : 0);
    if (typeof v === "string") { const [p, l] = _writeStr(v); return _dynString(p, l); }
    if (v === null) return _dynNull();
    if (v === undefined) return _dynUndefined();
    if (Array.isArray(v)) { const h = _dynArray(); for (const e of v) _dynPush(h, _box(e)); return h; }
    if (typeof v === "object") {
      const h = _dynObject(); const o = v as Record<string, unknown>;
      for (const k of Object.keys(o)) { const [p, l] = _writeStr(k); _dynSet(h, p, l, _box(o[k])); }
      return h;
    }
    if (typeof v === "function") {
      const _hi = _hostFns.length;
      _hostFns.push(v as (...a: unknown[]) => unknown);
      return _dynMakeHostFn(_hi);
    }
    return _dynNumber(0); // symbols / other — not marshalled
  }
  function _unbox(h: number): unknown {
    switch (_dynTag(h)) {
      case 3: return _dynNumberValue(h);
      case 4: return _dec.decode(new Uint8Array(_mem.buffer, _dynStrBytes(h), _dynStrLen(h)));
      case 2: return _dynToBool(h) !== 0;
      case 1: return null;
      case 0: return undefined;
      case 5: { const n = _dynArrLen(h); const a: unknown[] = []; for (let i = 0; i < n; i++) a.push(_unbox(_dynArrGet(h, i))); return a; }
      case 6: {
        const n = _dynObjLen(h); const o: Record<string, unknown> = {};
        for (let i = 0; i < n; i++) {
          const k = _dec.decode(new Uint8Array(_mem.buffer, _dynObjKeyPtr(h, i), _dynObjKeyLen(h, i)));
          o[k] = _unbox(_dynObjValAt(h, i));
        }
        return o;
      }
      case 7: {
        const _pin = _dynGcPin(h);
        const _fn = ((...args: unknown[]): unknown => {
          const _a = _dynArray();
          for (const _x of args) _dynPush(_a, _box(_x));
          return _unbox(_dynApply(h, _a));
        }) as ((...a: unknown[]) => unknown) & { release(): void };
        let _released = false;
        _fn.release = () => {
          if (_released) return;
          _released = true;
          _pinReg.unregister(_fn);
          _dynGcUnpin(_pin);
        };
        _pinReg.register(_fn, _pin, _fn); // 3rd arg = unregister token
        return _fn;
      }
      default: return h; // unknown tag — opaque handle
    }
  }
  _hostCallImpl = (fnIdx: number, argsArr: number): number => {
    const _f = _hostFns[fnIdx];
    if (!_f) return _dynUndefined();
    const _n = _dynArrLen(argsArr);
    const _js: unknown[] = [];
    for (let _i = 0; _i < _n; _i++) _js.push(_unbox(_dynArrGet(argsArr, _i)));
    return _box(_f(..._js));
  };
  return {
    applyTwice(fn: any, x: any): any { return _unbox((exp["applyTwice"] as (...a: unknown[]) => unknown)(_box(fn), _box(x)) as number); },
    combine(fn: any, a: any, b: any): any { return _unbox((exp["combine"] as (...a: unknown[]) => unknown)(_box(fn), _box(a), _box(b)) as number); },
  };
}
