// auto-generated by wasmtk bindgen — do not edit manually
// source: math-50
// deno-lint-ignore-file

export interface ModuleExports {
  add(a: number, b: number): number;
  multiply(a: number, b: number): number;
  square(x: number): number;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  return {
    add(a: number, b: number): number { return (exp["add"] as (...a: unknown[]) => unknown)(a, b) as number; },
    multiply(a: number, b: number): number { return (exp["multiply"] as (...a: unknown[]) => unknown)(a, b) as number; },
    square(x: number): number { return (exp["square"] as (...a: unknown[]) => unknown)(x) as number; },
  };
}
