// auto-generated by wasmtk bindgen — do not edit manually
// source: strings-50
// deno-lint-ignore-file

export interface ModuleExports {
  greet(name: string): string;
  shout(msg: string): string;
  strLen(s: string): number;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  let _wasiMem: WebAssembly.Memory | undefined;
  const _wasiView = () => new DataView((_wasiMem as WebAssembly.Memory).buffer);
  const _wasiU8 = () => new Uint8Array((_wasiMem as WebAssembly.Memory).buffer);
  const _wasiBase = {
    fd_write(fd: number, iovs: number, iovsLen: number, nwritten: number): number {
      const v = _wasiView(), mem = _wasiU8();
      let written = 0, text = "";
      for (let i = 0; i < iovsLen; i++) {
        const p = v.getInt32(iovs + i * 8, true), l = v.getInt32(iovs + i * 8 + 4, true);
        text += new TextDecoder().decode(mem.subarray(p, p + l)); written += l;
      }
      const out = text.replace(/\n$/, "");
      if (fd === 2) console.error(out); else console.log(out);
      v.setInt32(nwritten, written, true); return 0;
    },
    random_get(buf: number, len: number): number {
      const mem = _wasiU8();
      for (let i = 0; i < len; i++) mem[buf + i] = (Math.random() * 256) | 0;
      return 0;
    },
    clock_time_get(_id: number, _prec: number, timePtr: number): number {
      _wasiView().setBigInt64(timePtr, BigInt(Date.now()) * 1000000n, true); return 0;
    },
    proc_exit(code: number): number { throw new Error("wasm proc_exit(" + code + ")"); },
  } as Record<string, (...a: number[]) => number>;
  const _wasi = new Proxy(_wasiBase, { get: (t, k: string) => k in t ? t[k] : () => 0 });

  const importObj: Record<string, Record<string, unknown>> = { wasi_snapshot_preview1: _wasi };
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  _wasiMem = exp["memory"] as WebAssembly.Memory | undefined;
  (exp["_initialize"] as (() => void) | undefined)?.();
  const _mem = exp["memory"] as WebAssembly.Memory;
  const _cabi_realloc = exp["cabi_realloc"] as ((ptr: number, oldSize: number, align: number, newSize: number) => number);
  function _writeStr(s: string): [number, number] {
    const b = new TextEncoder().encode(s);
    const ptr = _cabi_realloc(0, 0, 1, b.length);
    new Uint8Array(_mem.buffer).set(b, ptr);
    return [ptr, b.length];
  }
  return {
    greet(name: string): string {
      const _r = (exp["greet"] as (...a: unknown[]) => unknown)(..._writeStr(name)) as number;
      const _v = new DataView(_mem.buffer);
      const _s = new TextDecoder().decode(new Uint8Array(_mem.buffer, _v.getInt32(_r, true), _v.getInt32(_r + 4, true)));
      (exp["cabi_post_greet"] as ((p: number) => void))(_r);
      return _s;
    },
    shout(msg: string): string {
      const _r = (exp["shout"] as (...a: unknown[]) => unknown)(..._writeStr(msg)) as number;
      const _v = new DataView(_mem.buffer);
      const _s = new TextDecoder().decode(new Uint8Array(_mem.buffer, _v.getInt32(_r, true), _v.getInt32(_r + 4, true)));
      (exp["cabi_post_shout"] as ((p: number) => void))(_r);
      return _s;
    },
    strLen(s: string): number { return (exp["strLen"] as (...a: unknown[]) => unknown)(..._writeStr(s)) as number; },
  };
}
