// auto-generated by wasmtk bindgen — do not edit manually
// source: anysig-lib
// deno-lint-ignore-file

export interface ModuleExports {
  identity(x: any): any;
  addOne(x: any): any;
  typeName(x: any): any;
  exclaim(s: any): any;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  const _mem = exp["memory"] as WebAssembly.Memory;
  const _cabi_realloc = exp["cabi_realloc"] as ((ptr: number, oldSize: number, align: number, newSize: number) => number);
  function _writeStr(s: string): [number, number] {
    const b = new TextEncoder().encode(s);
    const ptr = _cabi_realloc(0, 0, 1, b.length);
    new Uint8Array(_mem.buffer).set(b, ptr);
    return [ptr, b.length];
  }
  const _dynNumber = exp["dynNumber"] as (n: number) => number;
  const _dynNumberValue = exp["dynNumberValue"] as (h: number) => number;
  const _dynString = exp["dynString"] as (p: number, l: number) => number;
  const _dynStrBytes = exp["dynStrBytes"] as (h: number) => number;
  const _dynStrLen = exp["dynStrLen"] as (h: number) => number;
  const _dynBool = exp["dynBool"] as (b: number) => number;
  const _dynToBool = exp["dynToBool"] as (h: number) => number;
  const _dynTypeof = exp["dynTypeof"] as (h: number) => number;
  function _box(v: unknown): number {
    if (typeof v === "number") return _dynNumber(v);
    if (typeof v === "boolean") return _dynBool(v ? 1 : 0);
    if (typeof v === "string") { const [p, l] = _writeStr(v); return _dynString(p, l); }
    return _dynNumber(0); // null/undefined/object — not marshalled in v1
  }
  function _unbox(h: number): unknown {
    switch (_dynTypeof(h)) {
      case 3: return _dynNumberValue(h);
      case 4: return new TextDecoder().decode(new Uint8Array(_mem.buffer, _dynStrBytes(h), _dynStrLen(h)));
      case 2: return _dynToBool(h) !== 0;
      case 0: return undefined;
      default: return h; // object / function — opaque handle (v1)
    }
  }
  return {
    identity(x: any): any { return _unbox((exp["identity"] as (...a: unknown[]) => unknown)(_box(x)) as number); },
    addOne(x: any): any { return _unbox((exp["addOne"] as (...a: unknown[]) => unknown)(_box(x)) as number); },
    typeName(x: any): any { return _unbox((exp["typeName"] as (...a: unknown[]) => unknown)(_box(x)) as number); },
    exclaim(s: any): any { return _unbox((exp["exclaim"] as (...a: unknown[]) => unknown)(_box(s)) as number); },
  };
}
