(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "env" "sensor_calibrate" (func $sensor_calibrate (param f64)))
  (import "env" "display_show" (func $display_show (param i32)))
  (import "env" "display_clear" (func $display_clear))
  (import "env" "sensor_read" (func $sensor_read (result f64)))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 263))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )
  ;; Canonical ABI allocator — fresh allocation (ptr==0) delegates to $__malloc;
  ;; realloc requests (ptr!=0) return ptr unchanged (bump allocator has no free).
  (func $cabi_realloc (param $ptr i32) (param $old_size i32) (param $align i32) (param $new_size i32) (result i32)
    (select
      (call $__malloc (local.get $new_size))
      (local.get $ptr)
      (i32.eqz (local.get $ptr))
    )
  )
  (func $readAndDisplay (export "readAndDisplay")  
    (local $__iface_tmp i32)
    (call $sensor_calibrate (f64.const 0.5))
    (call $display_show (i32.const 42))
  )

  (func $clearAll (export "clearAll")  
    (local $__iface_tmp i32)
    (call $display_clear )
  )

  (func $readSensor (export "readSensor")  (result f64)
    (local $__iface_tmp i32)
    (return (call $sensor_read ))
  )
  (func $_start (export "_start")
    (local $__iface_tmp i32)
        (i32.store (i32.const 0) (i32.const 260))
          (i32.store (i32.const 4) (i32.const 3))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (call $proc_exit (i32.const 0))
  )
  (data (i32.const 260) "\33\33\0a")
)