(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 260))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )
  (func $testExternalCall (export "testExternalCall") (param $msgPtr i32) 
    (local $__iface_tmp i32)
    (;; logger.log(msgPtr);;)
  )
  (func $_start (export "_start")
    (call $proc_exit (i32.const 0))
  )
)