(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "env" "sensor_readInt" (func $sensor_readInt (result i32)))
  (import "env" "sensor_readFloat" (func $sensor_readFloat (result f64)))
  (import "env" "sensor_reset" (func $sensor_reset))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 263))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )
  (func $getSensorInt (export "getSensorInt")  (result i32)
    (local $__iface_tmp i32)
    (return (call $sensor_readInt ))
  )

  (func $getSensorFloat (export "getSensorFloat")  (result f64)
    (local $__iface_tmp i32)
    (return (call $sensor_readFloat ))
  )

  (func $resetSensor (export "resetSensor")  
    (local $__iface_tmp i32)
    (call $sensor_reset )
  )
  (func $_start (export "_start")
    (local $__iface_tmp i32)
        (i32.store (i32.const 0) (i32.const 260))
          (i32.store (i32.const 4) (i32.const 3))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (call $proc_exit (i32.const 0))
  )
  (data (i32.const 260) "\33\30\0a")
)