(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 352))
  (global $total (mut i32) (i32.const 0))
  (global $dynTotal (mut i32) (i32.const 0))
  (global $fsum (mut f64) (f64.const 0.0))
  (global $found (mut i32) (i32.const -1))
  (global $evenSum (mut i32) (i32.const 0))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )

  ;; ── i32 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  (func $__i32_to_str (param $val i32) (param $buf i32) (result i32)
    (local $start i32)
    (local $end i32)
    (local $tmp i32)
    (local $ch i32)
    (local $neg i32)
    (local $orig i32)
    (local.set $orig (local.get $buf))
    (local.set $start (local.get $buf))
    ;; Zero
    (if (i32.eqz (local.get $val))
      (then
        (i32.store8 (local.get $buf) (i32.const 48))
        (return (i32.const 1))
      )
    )
    ;; Negative
    (if (i32.lt_s (local.get $val) (i32.const 0))
      (then
        (i32.store8 (local.get $buf) (i32.const 45))
        (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
        (local.set $start (local.get $buf))
        (local.set $neg (i32.const 1))
        (local.set $val (i32.sub (i32.const 0) (local.get $val)))
      )
    )
    (local.set $end (local.get $buf))
    ;; Write digits in reverse
    (block $done
      (loop $loop
        (br_if $done (i32.eqz (local.get $val)))
        (i32.store8
          (local.get $end)
          (i32.add (i32.const 48) (i32.rem_u (local.get $val) (i32.const 10)))
        )
        (local.set $val (i32.div_u (local.get $val) (i32.const 10)))
        (local.set $end (i32.add (local.get $end) (i32.const 1)))
        (br $loop)
      )
    )
    ;; Reverse digit bytes in-place
    (local.set $tmp (local.get $start))
    (local.set $ch (i32.sub (local.get $end) (i32.const 1)))
    (block $rdone
      (loop $rloop
        (br_if $rdone (i32.ge_u (local.get $tmp) (local.get $ch)))
        (local.set $neg (i32.load8_u (local.get $tmp)))
        (i32.store8 (local.get $tmp) (i32.load8_u (local.get $ch)))
        (i32.store8 (local.get $ch) (local.get $neg))
        (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
        (local.set $ch (i32.sub (local.get $ch) (i32.const 1)))
        (br $rloop)
      )
    )
    ;; Return total length (including leading '-' if any)
    (i32.sub (local.get $end) (local.get $orig))
  )

  ;; ── f64 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  ;; Outputs the integer part plus up to 15 significant decimal digits.
  ;; Uses ×1e15 i64 arithmetic: 1e15 < 2^53 so the scaled fractional value
  ;; fits exactly in the representable integer range of f64, and the full
  ;; 15-digit result fits in i64. Trailing zeros are stripped from the output.
  ;; Values outside [-2147483648, 2147483647] for the integer part are clamped.
  (func $__f64_to_str (param $val f64) (param $buf i32) (result i32)
    (local $len i32)
    (local $ipart i32)
    (local $fpart i64)
    (local $flen i32)
    (local $fdigits i64)
    (local $ptr i32)
    (local.set $ptr (local.get $buf))
    ;; Handle negative
    (if (f64.lt (local.get $val) (f64.const 0))
      (then
        (i32.store8 (local.get $ptr) (i32.const 45))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        (local.set $val (f64.neg (local.get $val)))
      )
    )
    ;; Integer part
    (local.set $ipart (i32.trunc_f64_s (local.get $val)))
    (local.set $len (call $__i32_to_str (local.get $ipart) (local.get $ptr)))
    (local.set $ptr (i32.add (local.get $ptr) (local.get $len)))
    ;; Fractional part: multiply remainder by 1e15, round to nearest integer.
    ;; f64.nearest corrects truncation error from f64 values slightly below
    ;; their true decimal (e.g. 3.14159 stored as 3.14158999…).
    (local.set $fpart
      (i64.trunc_f64_s
        (f64.nearest
          (f64.mul
            (f64.sub (local.get $val) (f64.convert_i32_s (local.get $ipart)))
            (f64.const 1000000000000000)
          )
        )
      )
    )
    (if (i64.ne (local.get $fpart) (i64.const 0))
      (then
        ;; Decimal point
        (i32.store8 (local.get $ptr) (i32.const 46))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        ;; Write 15-digit fractional string then strip trailing zeros
        (local.set $fdigits (local.get $fpart))
        (local.set $flen (i32.const 15))
        (block $fdone
          (loop $floop
            (br_if $fdone (i32.eqz (local.get $flen)))
            (i32.store8
              (i32.add (local.get $ptr) (i32.sub (local.get $flen) (i32.const 1)))
              (i32.add (i32.const 48) (i32.wrap_i64 (i64.rem_u (local.get $fdigits) (i64.const 10))))
            )
            (local.set $fdigits (i64.div_u (local.get $fdigits) (i64.const 10)))
            (local.set $flen (i32.sub (local.get $flen) (i32.const 1)))
            (br $floop)
          )
        )
        ;; Strip trailing zeros
        (local.set $flen (i32.const 15))
        (block $strip
          (loop $striploop
            (br_if $strip (i32.eqz (local.get $flen)))
            (br_if $strip
              (i32.ne
                (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $flen) (i32.const 1))))
                (i32.const 48)
              )
            )
            (local.set $flen (i32.sub (local.get $flen) (i32.const 1)))
            (br $striploop)
          )
        )
        (local.set $ptr (i32.add (local.get $ptr) (local.get $flen)))
      )
    )
    ;; Return total length written
    (i32.sub (local.get $ptr) (local.get $buf))
  )

  ;; ── i64 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  (func $__i64_to_str (param $val i64) (param $buf i32) (result i32)
    (local $start i32)
    (local $end i32)
    (local $tmp i32)
    (local $ch i32)
    (local $neg i32)
    (local $digit i32)
    (local $orig i32)
    (local.set $orig (local.get $buf))
    (local.set $start (local.get $buf))
    ;; Zero
    (if (i64.eqz (local.get $val))
      (then
        (i32.store8 (local.get $buf) (i32.const 48))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 110))
        (return (i32.const 2))
      )
    )
    ;; Negative
    (if (i64.lt_s (local.get $val) (i64.const 0))
      (then
        (i32.store8 (local.get $buf) (i32.const 45))
        (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
        (local.set $start (local.get $buf))
        (local.set $neg (i32.const 1))
        (local.set $val (i64.sub (i64.const 0) (local.get $val)))
      )
    )
    (local.set $end (local.get $buf))
    ;; Write digits in reverse
    (block $done
      (loop $loop
        (br_if $done (i64.eqz (local.get $val)))
        (local.set $digit (i32.wrap_i64 (i64.rem_u (local.get $val) (i64.const 10))))
        (i32.store8
          (local.get $end)
          (i32.add (i32.const 48) (local.get $digit))
        )
        (local.set $val (i64.div_u (local.get $val) (i64.const 10)))
        (local.set $end (i32.add (local.get $end) (i32.const 1)))
        (br $loop)
      )
    )
    ;; Reverse digit bytes in-place
    (local.set $tmp (local.get $start))
    (local.set $ch (i32.sub (local.get $end) (i32.const 1)))
    (block $rdone
      (loop $rloop
        (br_if $rdone (i32.ge_u (local.get $tmp) (local.get $ch)))
        (local.set $neg (i32.load8_u (local.get $tmp)))
        (i32.store8 (local.get $tmp) (i32.load8_u (local.get $ch)))
        (i32.store8 (local.get $ch) (local.get $neg))
        (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
        (local.set $ch (i32.sub (local.get $ch) (i32.const 1)))
        (br $rloop)
      )
    )
    ;; Append 'n' suffix for bigint display
    (i32.store8 (local.get $end) (i32.const 110))
    (local.set $end (i32.add (local.get $end) (i32.const 1)))
    ;; Return total length (including leading '-' and trailing 'n')
    (i32.sub (local.get $end) (local.get $orig))
  )
  ;; Dynamic array grow_i32: malloc new block of newcap elements, copy data, return new ptr.
  (func $__dynarr_grow_i32 (param $arr i32) (param $newcap i32) (result i32)
    (local $newptr i32)
    (local $len i32)
    (local $i i32)
    (local.set $len (i32.load (local.get $arr)))
    (local.set $newptr (call $__malloc (i32.add (i32.const 8) (i32.shl (local.get $newcap) (i32.const 2)))))
    (i32.store (local.get $newptr) (local.get $len))
    (i32.store offset=4 (local.get $newptr) (local.get $newcap))
    (local.set $i (i32.const 0))
    (block $brk
      (loop $lp
        (br_if $brk (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store
          (i32.add (i32.add (local.get $newptr) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))
          (i32.load
            (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))
          )
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)
      )
    )
    (local.get $newptr)
  )

  ;; Dynamic array push_i32: grow if full, store val at end, increment length, return new arr ptr.
  (func $__dynarr_push_i32 (param $arr i32) (param $val i32) (result i32)
    (local $len i32)
    (local $cap i32)
    (local.set $len (i32.load (local.get $arr)))
    (local.set $cap (i32.load offset=4 (local.get $arr)))
    (if (i32.ge_u (local.get $len) (local.get $cap))
      (then
        (local.set $arr (call $__dynarr_grow_i32 (local.get $arr) (i32.shl (local.get $cap) (i32.const 1))))
      )
    )
    (i32.store
      (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (local.get $len) (i32.const 2)))
      (local.get $val)
    )
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (i32.store (local.get $arr) (local.get $len))
    (local.get $arr)
  )

  ;; Dynamic array pop_i32: decrement length, return last element. Traps if empty.
  (func $__dynarr_pop_i32 (param $arr i32) (result i32)
    (local $newlen i32)
    (if (i32.eqz (i32.load (local.get $arr))) (then (unreachable)))
    (local.set $newlen (i32.sub (i32.load (local.get $arr)) (i32.const 1)))
    (i32.store (local.get $arr) (local.get $newlen))
    (i32.load
      (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (local.get $newlen) (i32.const 2)))
    )
  )
  (func $sumDynamic  (result i32)
    (local $arr i32)
    (local $s i32)
    (local $item i32)
    (local $__forof_idx i32)
    (local $__iface_tmp i32)
    (local.set $arr (call $__malloc (i32.const 40)))
      (i32.store (local.get $arr) (i32.const 4))
      (i32.store offset=4 (local.get $arr) (i32.const 8))
      (i32.store offset=8 (local.get $arr) (i32.const 10))
      (i32.store offset=12 (local.get $arr) (i32.const 20))
      (i32.store offset=16 (local.get $arr) (i32.const 30))
      (i32.store offset=20 (local.get $arr) (i32.const 40))
    (local.set $arr (call $__dynarr_push_i32 (local.get $arr) (i32.const 0)))
    (drop (call $__dynarr_pop_i32 (local.get $arr)))
    (local.set $s (i32.const 0))
    (local.set $__forof_idx (i32.const 0))
    (block $break_0
      (loop $loop_0
        (br_if $break_0 (i32.ge_u (local.get $__forof_idx) (i32.load (local.get $arr))))
        (local.set $item (i32.load (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (local.get $__forof_idx) (i32.const 2)))))
        (block $cont_0
          (local.set $s (i32.add (local.get $s) (local.get $item)))
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_0)
      )
    )
    (return (local.get $s))
  )
  (func $_start (export "_start")
    (local $nums i32)
    (local $n i32)
    (local $__forof_idx i32)
    (local $dynNums i32)
    (local $x i32)
    (local $labels i32)
    (local $v i32)
    (local $floats i32)
    (local $fv f64)
    (local $data i32)
    (local $d i32)
    (local $evens i32)
    (local $e i32)
    (local $dynShort i32)
    (local $da i32)
    (local $db i32)
    (local $dynFull i32)
    (local $fa i32)
    (local $fb i32)
    (local $fc i32)
    (local $__iface_tmp i32)
    (local.set $nums (i32.const 260))
    (local.set $__forof_idx (i32.const 0))
    (block $break_1
      (loop $loop_1
        (br_if $break_1 (i32.ge_u (local.get $__forof_idx) (i32.const 3)))
        (local.set $n (i32.load (i32.add (i32.const 260) (i32.shl (local.get $__forof_idx) (i32.const 2)))))
        (block $cont_1
          (global.set $total (i32.add (global.get $total) (local.get $n)))
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_1)
      )
    )
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (global.get $total) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $dynNums (call $__malloc (i32.const 48)))
      (i32.store (local.get $dynNums) (i32.const 5))
      (i32.store offset=4 (local.get $dynNums) (i32.const 10))
      (i32.store offset=8 (local.get $dynNums) (i32.const 1))
      (i32.store offset=12 (local.get $dynNums) (i32.const 2))
      (i32.store offset=16 (local.get $dynNums) (i32.const 3))
      (i32.store offset=20 (local.get $dynNums) (i32.const 4))
      (i32.store offset=24 (local.get $dynNums) (i32.const 5))
    (local.set $dynNums (call $__dynarr_push_i32 (local.get $dynNums) (i32.const 6)))
    (local.set $__forof_idx (i32.const 0))
    (block $break_2
      (loop $loop_2
        (br_if $break_2 (i32.ge_u (local.get $__forof_idx) (i32.load (local.get $dynNums))))
        (local.set $x (i32.load (i32.add (i32.add (local.get $dynNums) (i32.const 8)) (i32.shl (local.get $__forof_idx) (i32.const 2)))))
        (block $cont_2
          (global.set $dynTotal (i32.add (global.get $dynTotal) (local.get $x)))
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_2)
      )
    )
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (global.get $dynTotal) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $labels (i32.const 272))
    (local.set $__forof_idx (i32.const 0))
    (block $break_3
      (loop $loop_3
        (br_if $break_3 (i32.ge_u (local.get $__forof_idx) (i32.const 3)))
        (local.set $v (i32.load (i32.add (i32.const 272) (i32.shl (local.get $__forof_idx) (i32.const 2)))))
        (block $cont_3
              (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $v) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_3)
      )
    )
    (local.set $floats (i32.const 284))
    (local.set $__forof_idx (i32.const 0))
    (block $break_4
      (loop $loop_4
        (br_if $break_4 (i32.ge_u (local.get $__forof_idx) (i32.const 3)))
        (local.set $fv (f64.load (i32.add (i32.const 284) (i32.shl (local.get $__forof_idx) (i32.const 3)))))
        (block $cont_4
          (global.set $fsum (f64.add (global.get $fsum) (local.get $fv)))
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_4)
      )
    )
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__f64_to_str (global.get $fsum) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $data (i32.const 308))
    (local.set $__forof_idx (i32.const 0))
    (block $break_5
      (loop $loop_5
        (br_if $break_5 (i32.ge_u (local.get $__forof_idx) (i32.const 5)))
        (local.set $d (i32.load (i32.add (i32.const 308) (i32.shl (local.get $__forof_idx) (i32.const 2)))))
        (block $cont_5
          (if (i32.eq (local.get $d) (i32.const 3))
            (then
            (global.set $found (local.get $d))
            (br $break_5)
            )
          )
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_5)
      )
    )
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (global.get $found) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $evens (i32.const 328))
    (local.set $__forof_idx (i32.const 0))
    (block $break_6
      (loop $loop_6
        (br_if $break_6 (i32.ge_u (local.get $__forof_idx) (i32.const 6)))
        (local.set $e (i32.load (i32.add (i32.const 328) (i32.shl (local.get $__forof_idx) (i32.const 2)))))
        (block $cont_6
          (if (i32.ne (i32.rem_s (local.get $e) (i32.const 2)) (i32.const 0))
            (then
            (br $cont_6)
            )
          )
          (global.set $evenSum (i32.add (global.get $evenSum) (local.get $e)))
        )
        (local.set $__forof_idx (i32.add (local.get $__forof_idx) (i32.const 1)))
        (br $loop_6)
      )
    )
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (global.get $evenSum) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (call $sumDynamic) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $dynShort (call $__malloc (i32.const 40)))
      (i32.store (local.get $dynShort) (i32.const 1))
      (i32.store offset=4 (local.get $dynShort) (i32.const 8))
      (i32.store offset=8 (local.get $dynShort) (i32.const 7))
    (local.set $dynShort (call $__dynarr_push_i32 (local.get $dynShort) (i32.const 0)))
    (drop (call $__dynarr_pop_i32 (local.get $dynShort)))
    (local.set $da (if (result i32) (i32.gt_u (i32.load (local.get $dynShort)) (i32.const 0)) (then (i32.load (i32.add (i32.add (local.get $dynShort) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2))))) (else (i32.const 10))))
      (local.set $db (if (result i32) (i32.gt_u (i32.load (local.get $dynShort)) (i32.const 1)) (then (i32.load (i32.add (i32.add (local.get $dynShort) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2))))) (else (i32.const 20))))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $da) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $db) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $dynFull (call $__malloc (i32.const 40)))
      (i32.store (local.get $dynFull) (i32.const 3))
      (i32.store offset=4 (local.get $dynFull) (i32.const 8))
      (i32.store offset=8 (local.get $dynFull) (i32.const 11))
      (i32.store offset=12 (local.get $dynFull) (i32.const 22))
      (i32.store offset=16 (local.get $dynFull) (i32.const 33))
    (local.set $dynFull (call $__dynarr_push_i32 (local.get $dynFull) (i32.const 0)))
    (drop (call $__dynarr_pop_i32 (local.get $dynFull)))
    (local.set $fa (if (result i32) (i32.gt_u (i32.load (local.get $dynFull)) (i32.const 0)) (then (i32.load (i32.add (i32.add (local.get $dynFull) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2))))) (else (i32.const 99))))
      (local.set $fb (if (result i32) (i32.gt_u (i32.load (local.get $dynFull)) (i32.const 1)) (then (i32.load (i32.add (i32.add (local.get $dynFull) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2))))) (else (i32.const 99))))
      (local.set $fc (if (result i32) (i32.gt_u (i32.load (local.get $dynFull)) (i32.const 2)) (then (i32.load (i32.add (i32.add (local.get $dynFull) (i32.const 8)) (i32.shl (i32.const 2) (i32.const 2))))) (else (i32.const 99))))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $fa) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $fb) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $fc) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (call $proc_exit (i32.const 0))
  )
  (data (i32.const 260) "\0a\00\00\00\14\00\00\00\1e\00\00\00")
  (data (i32.const 272) "\64\00\00\00\c8\00\00\00\2c\01\00\00")
  (data (i32.const 284) "\00\00\00\00\00\00\f8\3f\00\00\00\00\00\00\04\40\00\00\00\00\00\00\0c\40")
  (data (i32.const 308) "\01\00\00\00\02\00\00\00\03\00\00\00\04\00\00\00\05\00\00\00")
  (data (i32.const 328) "\01\00\00\00\02\00\00\00\03\00\00\00\04\00\00\00\05\00\00\00\06\00\00\00")
)