(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "env" "ops_add" (func $ops_add (param i32) (param i32) (result i32)))
  (import "env" "ops_scale" (func $ops_scale (param f64) (param f64) (result f64)))
  (import "env" "ops_negate" (func $ops_negate (param i32) (result i32)))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 263))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )
  (func $computeAdd (export "computeAdd") (param $a i32) (param $b i32) (result i32)
    (local $__iface_tmp i32)
    (return (call $ops_add (local.get $a) (local.get $b)))
  )

  (func $computeScale (export "computeScale") (param $x f64) (param $factor f64) (result f64)
    (local $__iface_tmp i32)
    (return (call $ops_scale (local.get $x) (local.get $factor)))
  )

  (func $computeNeg (export "computeNeg") (param $x i32) (result i32)
    (local $__iface_tmp i32)
    (return (call $ops_negate (local.get $x)))
  )
  (func $_start (export "_start")
    (local $__iface_tmp i32)
        (i32.store (i32.const 0) (i32.const 260))
          (i32.store (i32.const 4) (i32.const 3))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (call $proc_exit (i32.const 0))
  )
  (data (i32.const 260) "\34\39\0a")
)