(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 260))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )

  ;; ── i32 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  (func $__i32_to_str (param $val i32) (param $buf i32) (result i32)
    (local $start i32)
    (local $end i32)
    (local $tmp i32)
    (local $ch i32)
    (local $neg i32)
    (local $orig i32)
    (local.set $orig (local.get $buf))
    (local.set $start (local.get $buf))
    ;; Zero
    (if (i32.eqz (local.get $val))
      (then
        (i32.store8 (local.get $buf) (i32.const 48))
        (return (i32.const 1))
      )
    )
    ;; Negative
    (if (i32.lt_s (local.get $val) (i32.const 0))
      (then
        (i32.store8 (local.get $buf) (i32.const 45))
        (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
        (local.set $start (local.get $buf))
        (local.set $neg (i32.const 1))
        (local.set $val (i32.sub (i32.const 0) (local.get $val)))
      )
    )
    (local.set $end (local.get $buf))
    ;; Write digits in reverse
    (block $done
      (loop $loop
        (br_if $done (i32.eqz (local.get $val)))
        (i32.store8
          (local.get $end)
          (i32.add (i32.const 48) (i32.rem_u (local.get $val) (i32.const 10)))
        )
        (local.set $val (i32.div_u (local.get $val) (i32.const 10)))
        (local.set $end (i32.add (local.get $end) (i32.const 1)))
        (br $loop)
      )
    )
    ;; Reverse digit bytes in-place
    (local.set $tmp (local.get $start))
    (local.set $ch (i32.sub (local.get $end) (i32.const 1)))
    (block $rdone
      (loop $rloop
        (br_if $rdone (i32.ge_u (local.get $tmp) (local.get $ch)))
        (local.set $neg (i32.load8_u (local.get $tmp)))
        (i32.store8 (local.get $tmp) (i32.load8_u (local.get $ch)))
        (i32.store8 (local.get $ch) (local.get $neg))
        (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
        (local.set $ch (i32.sub (local.get $ch) (i32.const 1)))
        (br $rloop)
      )
    )
    ;; Return total length (including leading '-' if any)
    (i32.sub (local.get $end) (local.get $orig))
  )

  ;; ── f64 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  ;; Outputs the integer part plus up to 6 significant decimal digits.
  ;; Values outside [-2147483648, 2147483647] for the integer part are clamped.
  (func $__f64_to_str (param $val f64) (param $buf i32) (result i32)
    (local $len i32)
    (local $ipart i32)
    (local $fpart i64)
    (local $flen i32)
    (local $fdigits i32)
    (local $ptr i32)
    (local $zeros i32)
    (local.set $ptr (local.get $buf))
    ;; Handle negative
    (if (f64.lt (local.get $val) (f64.const 0))
      (then
        (i32.store8 (local.get $ptr) (i32.const 45))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        (local.set $val (f64.neg (local.get $val)))
      )
    )
    ;; Integer part
    (local.set $ipart (i32.trunc_f64_s (local.get $val)))
    (local.set $len (call $__i32_to_str (local.get $ipart) (local.get $ptr)))
    (local.set $ptr (i32.add (local.get $ptr) (local.get $len)))
    ;; Fractional part: multiply remainder by 1 000 000, take integer
    (local.set $fpart
      (i64.trunc_f64_s
        (f64.mul
          (f64.sub (local.get $val) (f64.convert_i32_s (local.get $ipart)))
          (f64.const 1000000)
        )
      )
    )
    (if (i64.ne (local.get $fpart) (i64.const 0))
      (then
        ;; Decimal point
        (i32.store8 (local.get $ptr) (i32.const 46))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        ;; Write 6-digit fractional string then strip trailing zeros
        (local.set $fdigits (i32.wrap_i64 (local.get $fpart)))
        ;; Write fractional digits in reverse into a 6-byte window
        (local.set $flen (i32.const 6))
        (block $fdone
          (loop $floop
            (br_if $fdone (i32.eqz (local.get $flen)))
            (i32.store8
              (i32.add (local.get $ptr) (i32.sub (local.get $flen) (i32.const 1)))
              (i32.add (i32.const 48) (i32.rem_u (local.get $fdigits) (i32.const 10)))
            )
            (local.set $fdigits (i32.div_u (local.get $fdigits) (i32.const 10)))
            (local.set $flen (i32.sub (local.get $flen) (i32.const 1)))
            (br $floop)
          )
        )
        ;; Count non-zero trailing digits to strip
        (local.set $flen (i32.const 6))
        (block $strip
          (loop $striploop
            (br_if $strip (i32.eqz (local.get $flen)))
            (br_if $strip
              (i32.ne
                (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $flen) (i32.const 1))))
                (i32.const 48)
              )
            )
            (local.set $flen (i32.sub (local.get $flen) (i32.const 1)))
            (br $striploop)
          )
        )
        (local.set $ptr (i32.add (local.get $ptr) (local.get $flen)))
      )
    )
    ;; Return total length written
    (i32.sub (local.get $ptr) (local.get $buf))
  )

  ;; ── i64 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  (func $__i64_to_str (param $val i64) (param $buf i32) (result i32)
    (local $start i32)
    (local $end i32)
    (local $tmp i32)
    (local $ch i32)
    (local $neg i32)
    (local $digit i32)
    (local $orig i32)
    (local.set $orig (local.get $buf))
    (local.set $start (local.get $buf))
    ;; Zero
    (if (i64.eqz (local.get $val))
      (then
        (i32.store8 (local.get $buf) (i32.const 48))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 110))
        (return (i32.const 2))
      )
    )
    ;; Negative
    (if (i64.lt_s (local.get $val) (i64.const 0))
      (then
        (i32.store8 (local.get $buf) (i32.const 45))
        (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
        (local.set $start (local.get $buf))
        (local.set $neg (i32.const 1))
        (local.set $val (i64.sub (i64.const 0) (local.get $val)))
      )
    )
    (local.set $end (local.get $buf))
    ;; Write digits in reverse
    (block $done
      (loop $loop
        (br_if $done (i64.eqz (local.get $val)))
        (local.set $digit (i32.wrap_i64 (i64.rem_u (local.get $val) (i64.const 10))))
        (i32.store8
          (local.get $end)
          (i32.add (i32.const 48) (local.get $digit))
        )
        (local.set $val (i64.div_u (local.get $val) (i64.const 10)))
        (local.set $end (i32.add (local.get $end) (i32.const 1)))
        (br $loop)
      )
    )
    ;; Reverse digit bytes in-place
    (local.set $tmp (local.get $start))
    (local.set $ch (i32.sub (local.get $end) (i32.const 1)))
    (block $rdone
      (loop $rloop
        (br_if $rdone (i32.ge_u (local.get $tmp) (local.get $ch)))
        (local.set $neg (i32.load8_u (local.get $tmp)))
        (i32.store8 (local.get $tmp) (i32.load8_u (local.get $ch)))
        (i32.store8 (local.get $ch) (local.get $neg))
        (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
        (local.set $ch (i32.sub (local.get $ch) (i32.const 1)))
        (br $rloop)
      )
    )
    ;; Append 'n' suffix for bigint display
    (i32.store8 (local.get $end) (i32.const 110))
    (local.set $end (i32.add (local.get $end) (i32.const 1)))
    ;; Return total length (including leading '-' and trailing 'n')
    (i32.sub (local.get $end) (local.get $orig))
  )
  ;; Dynamic array concat_i32: alloc new array = arrA ++ arrB.
  (func $__dynarr_concat_i32 (param $a i32) (param $b i32) (result i32)
    (local $lenA i32)
    (local $lenB i32)
    (local $newlen i32)
    (local $cap i32)
    (local $newptr i32)
    (local $i i32)
    (local.set $lenA (i32.load (local.get $a)))
    (local.set $lenB (i32.load (local.get $b)))
    (local.set $newlen (i32.add (local.get $lenA) (local.get $lenB)))
    (local.set $cap (local.get $newlen))
    (if (i32.lt_u (local.get $cap) (i32.const 8)) (then (local.set $cap (i32.const 8))))
    (local.set $newptr (call $__malloc
      (i32.add (i32.const 8) (i32.shl (local.get $cap) (i32.const 2)))))
    (i32.store (local.get $newptr) (local.get $newlen))
    (i32.store offset=4 (local.get $newptr) (local.get $cap))
    (local.set $i (i32.const 0))
    (block $doneA
      (loop $lpA
        (br_if $doneA (i32.ge_u (local.get $i) (local.get $lenA)))
        (i32.store
          (i32.add (i32.add (local.get $newptr) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))
          (i32.load (i32.add (i32.add (local.get $a) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lpA)
      )
    )
    (local.set $i (i32.const 0))
    (block $doneB
      (loop $lpB
        (br_if $doneB (i32.ge_u (local.get $i) (local.get $lenB)))
        (i32.store
          (i32.add (i32.add (local.get $newptr) (i32.const 8))
            (i32.shl (i32.add (local.get $i) (local.get $lenA)) (i32.const 2)))
          (i32.load (i32.add (i32.add (local.get $b) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lpB)
      )
    )
    (local.get $newptr)
  )
  (func $sumAll (param $nums i32) (result i32)
    (local $total i32)
    (local $i i32)
    (local $len i32)
    (local.set $total (i32.const 0))
    (local.set $i (i32.const 0))
    (local.set $len (i32.load (local.get $nums)))
    (block $break_0
      (loop $loop_0
        (br_if $break_0 (i32.eqz (i32.lt_s (local.get $i) (local.get $len))))
        (block $cont_0
          (local.set $total (i32.add (local.get $total) (i32.load (i32.add (i32.add (local.get $nums) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2))))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
        )
        (br $loop_0)
      )
    )
    (return (local.get $total))
  )

  (func $prefixedSum (param $prefix i32) (param $nums i32) (result i32)
    (local $total i32)
    (local $i i32)
    (local $len i32)
    (local.set $total (local.get $prefix))
    (local.set $i (i32.const 0))
    (local.set $len (i32.load (local.get $nums)))
    (block $break_1
      (loop $loop_1
        (br_if $break_1 (i32.eqz (i32.lt_s (local.get $i) (local.get $len))))
        (block $cont_1
          (local.set $total (i32.add (local.get $total) (i32.load (i32.add (i32.add (local.get $nums) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2))))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
        )
        (br $loop_1)
      )
    )
    (return (local.get $total))
  )

  (func $avgF (param $vals i32) (result f64)
    (local $sum f64)
    (local $i i32)
    (local $len i32)
    (local.set $sum (f64.const 0.0))
    (local.set $i (i32.const 0))
    (local.set $len (i32.load (local.get $vals)))
    (block $break_2
      (loop $loop_2
        (br_if $break_2 (i32.eqz (i32.lt_s (local.get $i) (local.get $len))))
        (block $cont_2
          (local.set $sum (f64.add (local.get $sum) (f64.load (i32.add (i32.add (local.get $vals) (i32.const 8)) (i32.shl (local.get $i) (i32.const 3))))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
        )
        (br $loop_2)
      )
    )
    (return (local.get $sum))
  )
  (func $_start (export "_start")
    (local $s1 i32)
    (local $s2 i32)
    (local $ps i32)
    (local $arr1 i32)
    (local $s3 i32)
    (local $a i32)
    (local $b i32)
    (local $merged i32)
    (local $c i32)
    (local $abc i32)
    (local $fsum f64)
    (local $__rest_ptr i32)
    (local $__iface_tmp i32)
    (local.set $__rest_ptr (call $__malloc (i32.const 40)))
      (i32.store (local.get $__rest_ptr) (i32.const 3))
      (i32.store offset=4 (local.get $__rest_ptr) (i32.const 8))
      (i32.store offset=8 (local.get $__rest_ptr) (i32.const 1))
      (i32.store offset=12 (local.get $__rest_ptr) (i32.const 2))
      (i32.store offset=16 (local.get $__rest_ptr) (i32.const 3))
      (call $sumAll (local.get $__rest_ptr))
      (local.set $s1)
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $s1) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $__rest_ptr (call $__malloc (i32.const 40)))
      (i32.store (local.get $__rest_ptr) (i32.const 4))
      (i32.store offset=4 (local.get $__rest_ptr) (i32.const 8))
      (i32.store offset=8 (local.get $__rest_ptr) (i32.const 10))
      (i32.store offset=12 (local.get $__rest_ptr) (i32.const 20))
      (i32.store offset=16 (local.get $__rest_ptr) (i32.const 30))
      (i32.store offset=20 (local.get $__rest_ptr) (i32.const 40))
      (call $sumAll (local.get $__rest_ptr))
      (local.set $s2)
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $s2) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $__rest_ptr (call $__malloc (i32.const 40)))
      (i32.store (local.get $__rest_ptr) (i32.const 3))
      (i32.store offset=4 (local.get $__rest_ptr) (i32.const 8))
      (i32.store offset=8 (local.get $__rest_ptr) (i32.const 1))
      (i32.store offset=12 (local.get $__rest_ptr) (i32.const 2))
      (i32.store offset=16 (local.get $__rest_ptr) (i32.const 3))
      (call $prefixedSum (i32.const 100) (local.get $__rest_ptr))
      (local.set $ps)
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $ps) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $arr1 (call $__malloc (i32.const 40)))
      (i32.store (local.get $arr1) (i32.const 3))
      (i32.store offset=4 (local.get $arr1) (i32.const 8))
      (i32.store offset=8 (local.get $arr1) (i32.const 5))
      (i32.store offset=12 (local.get $arr1) (i32.const 10))
      (i32.store offset=16 (local.get $arr1) (i32.const 15))
    (call $sumAll (local.get $arr1))
      (local.set $s3)
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (local.get $s3) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $a (call $__malloc (i32.const 40)))
      (i32.store (local.get $a) (i32.const 3))
      (i32.store offset=4 (local.get $a) (i32.const 8))
      (i32.store offset=8 (local.get $a) (i32.const 1))
      (i32.store offset=12 (local.get $a) (i32.const 2))
      (i32.store offset=16 (local.get $a) (i32.const 3))
    (local.set $b (call $__malloc (i32.const 40)))
      (i32.store (local.get $b) (i32.const 3))
      (i32.store offset=4 (local.get $b) (i32.const 8))
      (i32.store offset=8 (local.get $b) (i32.const 4))
      (i32.store offset=12 (local.get $b) (i32.const 5))
      (i32.store offset=16 (local.get $b) (i32.const 6))
    (local.set $merged (local.get $a))
      (local.set $merged (call $__dynarr_concat_i32 (local.get $merged) (local.get $b)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (i32.load (local.get $merged)) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (i32.load (i32.add (i32.add (local.get $merged) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2)))) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (i32.load (i32.add (i32.add (local.get $merged) (i32.const 8)) (i32.shl (i32.const 5) (i32.const 2)))) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $c (call $__malloc (i32.const 40)))
      (i32.store (local.get $c) (i32.const 2))
      (i32.store offset=4 (local.get $c) (i32.const 8))
      (i32.store offset=8 (local.get $c) (i32.const 7))
      (i32.store offset=12 (local.get $c) (i32.const 8))
    (local.set $abc (local.get $a))
      (local.set $abc (call $__dynarr_concat_i32 (local.get $abc) (local.get $b)))
      (local.set $abc (call $__dynarr_concat_i32 (local.get $abc) (local.get $c)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (i32.load (local.get $abc)) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (i32.load (i32.add (i32.add (local.get $abc) (i32.const 8)) (i32.shl (i32.const 6) (i32.const 2)))) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__i32_to_str (i32.load (i32.add (i32.add (local.get $abc) (i32.const 8)) (i32.shl (i32.const 7) (i32.const 2)))) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (local.set $__rest_ptr (call $__malloc (i32.const 72)))
      (i32.store (local.get $__rest_ptr) (i32.const 3))
      (i32.store offset=4 (local.get $__rest_ptr) (i32.const 8))
      (f64.store offset=8 (local.get $__rest_ptr) (f64.const 1.5))
      (f64.store offset=16 (local.get $__rest_ptr) (f64.const 2.5))
      (f64.store offset=24 (local.get $__rest_ptr) (f64.const 3.0))
      (call $avgF (local.get $__rest_ptr))
      (local.set $fsum)
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (call $__f64_to_str (local.get $fsum) (i32.const 132)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (call $proc_exit (i32.const 0))
  )
)