(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 396))
  (global $__str_ret_ptr (mut i32) (i32.const 0))
  (global $__str_ret_len (mut i32) (i32.const 0))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )

  ;; ── str_cmp: lexicographic byte comparison ─────────────────────────────────
  ;; Returns negative if a<b, 0 if a==b, positive if a>b.
  (func $__str_cmp
    (param $aptr i32) (param $alen i32) (param $bptr i32) (param $blen i32)
    (result i32)
    (local $i i32)
    (local $minlen i32)
    (local $ca i32)
    (local $cb i32)
    (local.set $minlen
      (if (result i32) (i32.lt_s (local.get $alen) (local.get $blen))
        (then (local.get $alen))
        (else (local.get $blen))
      )
    )
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $minlen)))
        (local.set $ca (i32.load8_u (i32.add (local.get $aptr) (local.get $i))))
        (local.set $cb (i32.load8_u (i32.add (local.get $bptr) (local.get $i))))
        (if (i32.ne (local.get $ca) (local.get $cb))
          (then (return (i32.sub (local.get $ca) (local.get $cb))))
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)
      )
    )
    (i32.sub (local.get $alen) (local.get $blen))
  )

  ;; ── str_gather: copy len bytes from src to dst (byte-copy loop, no bulk-memory) ──
  ;; Used by gather-buffer mode in console.log for strvar/boolvar segments.
  (func $__str_gather (param $src i32) (param $slen i32) (param $dst i32)
    (local $i i32)
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $slen)))
        (i32.store8
          (i32.add (local.get $dst) (local.get $i))
          (i32.load8_u (i32.add (local.get $src) (local.get $i)))
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)
      )
    )
  )

  ;; ── str_concat: heap-allocate new string = a ++ b ───────────────────────────
  ;; Copies bytes of a then b into a malloc'd buffer. Returns (ptr, len).
  ;; Old buffers become dead memory (bump allocator has no free).
  (func $__str_concat
    (param $aptr i32) (param $alen i32) (param $bptr i32) (param $blen i32)
    (result i32 i32)
    (local $newptr i32) (local $newlen i32) (local $i i32)
    (local.set $newlen (i32.add (local.get $alen) (local.get $blen)))
    (local.set $newptr (call $__malloc (local.get $newlen)))
    ;; copy a
    (local.set $i (i32.const 0))
    (block $done_a
      (loop $copy_a
        (br_if $done_a (i32.ge_u (local.get $i) (local.get $alen)))
        (i32.store8
          (i32.add (local.get $newptr) (local.get $i))
          (i32.load8_u (i32.add (local.get $aptr) (local.get $i)))
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $copy_a)
      )
    )
    ;; copy b
    (local.set $i (i32.const 0))
    (block $done_b
      (loop $copy_b
        (br_if $done_b (i32.ge_u (local.get $i) (local.get $blen)))
        (i32.store8
          (i32.add (local.get $newptr) (i32.add (local.get $alen) (local.get $i)))
          (i32.load8_u (i32.add (local.get $bptr) (local.get $i)))
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $copy_b)
      )
    )
    (local.get $newptr)
    (local.get $newlen)
  )

  ;; ── str_slice: return sub-range of existing string (no allocation) ───────────
  ;; Clamps start/end to [0, len]. Returns (ptr+start, end-start).
  (func $__str_slice
    (param $ptr i32) (param $len i32) (param $start i32) (param $end i32)
    (result i32 i32)
    (local $cs i32) (local $ce i32)
    ;; clamp start to [0, len]
    (local.set $cs
      (select (i32.const 0) (local.get $start) (i32.lt_s (local.get $start) (i32.const 0)))
    )
    (if (i32.gt_s (local.get $cs) (local.get $len))
      (then (local.set $cs (local.get $len)))
    )
    ;; clamp end to [cs, len]
    (local.set $ce
      (select (local.get $len) (local.get $end) (i32.gt_s (local.get $end) (local.get $len)))
    )
    (if (i32.lt_s (local.get $ce) (local.get $cs))
      (then (local.set $ce (local.get $cs)))
    )
    (i32.add (local.get $ptr) (local.get $cs))
    (i32.sub (local.get $ce) (local.get $cs))
  )

  ;; ── str_indexof: first occurrence of sub in str, or -1 ──────────────────────
  (func $__str_indexof
    (param $ptr i32) (param $len i32) (param $subptr i32) (param $sublen i32)
    (result i32)
    (local $i i32) (local $j i32) (local $max i32) (local $ok i32)
    ;; empty substring always found at position 0
    (if (i32.eqz (local.get $sublen)) (then (return (i32.const 0))))
    ;; if sub is longer than str, impossible
    (local.set $max (i32.sub (local.get $len) (local.get $sublen)))
    (if (i32.lt_s (local.get $max) (i32.const 0)) (then (return (i32.const -1))))
    (block $found_none
      (loop $outer
        (br_if $found_none (i32.gt_s (local.get $i) (local.get $max)))
        (local.set $j (i32.const 0))
        (local.set $ok (i32.const 1))
        (block $inner_done
          (loop $inner
            (br_if $inner_done (i32.ge_u (local.get $j) (local.get $sublen)))
            (if (i32.ne
              (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (local.get $j))))
              (i32.load8_u (i32.add (local.get $subptr) (local.get $j)))
            )
              (then
                (local.set $ok (i32.const 0))
                (br $inner_done)
              )
            )
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $inner)
          )
        )
        (if (local.get $ok) (then (return (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $outer)
      )
    )
    (i32.const -1)
  )

  ;; ── str_indexof_from: first occurrence of sub in str starting at 'from', or -1 ─
  (func $__str_indexof_from
    (param $ptr i32) (param $len i32) (param $subptr i32) (param $sublen i32) (param $from i32)
    (result i32)
    (local $i i32) (local $j i32) (local $max i32) (local $ok i32)
    (if (i32.eqz (local.get $sublen)) (then (return (local.get $from))))
    (local.set $max (i32.sub (local.get $len) (local.get $sublen)))
    (if (i32.lt_s (local.get $max) (i32.const 0)) (then (return (i32.const -1))))
    (local.set $i (select (i32.const 0) (local.get $from) (i32.lt_s (local.get $from) (i32.const 0))))
    (block $found_none
      (loop $outer
        (br_if $found_none (i32.gt_s (local.get $i) (local.get $max)))
        (local.set $j (i32.const 0))
        (local.set $ok (i32.const 1))
        (block $inner_done
          (loop $inner
            (br_if $inner_done (i32.ge_u (local.get $j) (local.get $sublen)))
            (if (i32.ne
              (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (local.get $j))))
              (i32.load8_u (i32.add (local.get $subptr) (local.get $j)))
            )
              (then
                (local.set $ok (i32.const 0))
                (br $inner_done)
              )
            )
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $inner)
          )
        )
        (if (local.get $ok) (then (return (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $outer)
      )
    )
    (i32.const -1)
  )

  ;; ── i32 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  (func $__i32_to_str (param $val i32) (param $buf i32) (result i32)
    (local $start i32)
    (local $end i32)
    (local $tmp i32)
    (local $ch i32)
    (local $neg i32)
    (local $orig i32)
    (local.set $orig (local.get $buf))
    (local.set $start (local.get $buf))
    ;; Zero
    (if (i32.eqz (local.get $val))
      (then
        (i32.store8 (local.get $buf) (i32.const 48))
        (return (i32.const 1))
      )
    )
    ;; Negative
    (if (i32.lt_s (local.get $val) (i32.const 0))
      (then
        (i32.store8 (local.get $buf) (i32.const 45))
        (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
        (local.set $start (local.get $buf))
        (local.set $neg (i32.const 1))
        (local.set $val (i32.sub (i32.const 0) (local.get $val)))
      )
    )
    (local.set $end (local.get $buf))
    ;; Write digits in reverse
    (block $done
      (loop $loop
        (br_if $done (i32.eqz (local.get $val)))
        (i32.store8
          (local.get $end)
          (i32.add (i32.const 48) (i32.rem_u (local.get $val) (i32.const 10)))
        )
        (local.set $val (i32.div_u (local.get $val) (i32.const 10)))
        (local.set $end (i32.add (local.get $end) (i32.const 1)))
        (br $loop)
      )
    )
    ;; Reverse digit bytes in-place
    (local.set $tmp (local.get $start))
    (local.set $ch (i32.sub (local.get $end) (i32.const 1)))
    (block $rdone
      (loop $rloop
        (br_if $rdone (i32.ge_u (local.get $tmp) (local.get $ch)))
        (local.set $neg (i32.load8_u (local.get $tmp)))
        (i32.store8 (local.get $tmp) (i32.load8_u (local.get $ch)))
        (i32.store8 (local.get $ch) (local.get $neg))
        (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
        (local.set $ch (i32.sub (local.get $ch) (i32.const 1)))
        (br $rloop)
      )
    )
    ;; Return total length (including leading '-' if any)
    (i32.sub (local.get $end) (local.get $orig))
  )

  ;; ── f64 powers of 10 helper (used by $__f64_to_str shortening loop) ─────────
  (func $__pow10_f64 (param $n i32) (result f64)
    (if (i32.le_s (local.get $n) (i32.const 0))  (then (return (f64.const 1))))
    (if (i32.eq  (local.get $n) (i32.const 1))   (then (return (f64.const 10))))
    (if (i32.eq  (local.get $n) (i32.const 2))   (then (return (f64.const 100))))
    (if (i32.eq  (local.get $n) (i32.const 3))   (then (return (f64.const 1000))))
    (if (i32.eq  (local.get $n) (i32.const 4))   (then (return (f64.const 10000))))
    (if (i32.eq  (local.get $n) (i32.const 5))   (then (return (f64.const 100000))))
    (if (i32.eq  (local.get $n) (i32.const 6))   (then (return (f64.const 1000000))))
    (if (i32.eq  (local.get $n) (i32.const 7))   (then (return (f64.const 10000000))))
    (if (i32.eq  (local.get $n) (i32.const 8))   (then (return (f64.const 100000000))))
    (if (i32.eq  (local.get $n) (i32.const 9))   (then (return (f64.const 1000000000))))
    (if (i32.eq  (local.get $n) (i32.const 10))  (then (return (f64.const 10000000000))))
    (if (i32.eq  (local.get $n) (i32.const 11))  (then (return (f64.const 100000000000))))
    (if (i32.eq  (local.get $n) (i32.const 12))  (then (return (f64.const 1000000000000))))
    (if (i32.eq  (local.get $n) (i32.const 13))  (then (return (f64.const 10000000000000))))
    (if (i32.eq  (local.get $n) (i32.const 14))  (then (return (f64.const 100000000000000))))
    (f64.const 1000000000000000)
  )

  ;; ── f64 → decimal string ──────────────────────────────────────────────────
  ;; Writes the shortest decimal representation of $val at $buf, returns byte count.
  ;; Step 1: ×1e15 + f64.nearest gives up to 15 fractional digits.
  ;; Step 2: "shortest round-trip" loop strips any digit whose removal still
  ;;         reconstructs the exact same f64 via f64(ipart)+f64(trial)/f64(10^k).
  ;;         This eliminates spurious trailing digits caused by ×1e15 rounding.
  ;; Values outside [-2147483648, 2147483647] for the integer part are clamped.
  (func $__f64_to_str (param $val f64) (param $buf i32) (result i32)
    (local $len i32)
    (local $ipart i64)
    (local $fpart i64)
    (local $flen i32)
    (local $fdigits i64)
    (local $ptr i32)
    (local $cur_fpart i64)
    (local $cur_len i32)
    (local $trial i64)
    (local $recon f64)
    (local.set $ptr (local.get $buf))
    ;; Handle negative
    (if (f64.lt (local.get $val) (f64.const 0))
      (then
        (i32.store8 (local.get $ptr) (i32.const 45))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        (local.set $val (f64.neg (local.get $val)))
      )
    )
    ;; Integer part — use i64 to support values beyond i32 range (up to ~9.2e18)
    ;; Subtract 1 from i64_to_str result to exclude the 'n' bigint suffix it appends.
    (local.set $ipart (i64.trunc_f64_s (local.get $val)))
    (local.set $len (i32.sub (call $__i64_to_str (local.get $ipart) (local.get $ptr)) (i32.const 1)))
    (local.set $ptr (i32.add (local.get $ptr) (local.get $len)))
    ;; Step 1: ×1e15, round to nearest integer → up to 15 fractional digits.
    (local.set $fpart
      (i64.trunc_f64_s
        (f64.nearest
          (f64.mul
            (f64.sub (local.get $val) (f64.convert_i64_s (local.get $ipart)))
            (f64.const 1000000000000000)
          )
        )
      )
    )
    ;; Step 2: shorten — strip digits from the right as long as the decimal
    ;; still round-trips to the original f64.  Powers of 10 in [1,1e15] are
    ;; exact in f64 (≤50 significant bits), so the reconstruction arithmetic
    ;; is reliable and the loop never produces a false positive.
    (local.set $cur_fpart (local.get $fpart))
    (local.set $cur_len   (i32.const 15))
    (block $shorten_done
      (loop $shorten_loop
        (br_if $shorten_done (i32.le_s (local.get $cur_len) (i32.const 1)))
        (local.set $trial (i64.div_u (local.get $cur_fpart) (i64.const 10)))
        (local.set $recon
          (f64.add
            (f64.convert_i64_s (local.get $ipart))
            (f64.div
              (f64.convert_i64_s (local.get $trial))
              (call $__pow10_f64 (i32.sub (local.get $cur_len) (i32.const 1)))
            )
          )
        )
        (if (f64.ne (local.get $recon) (local.get $val))
          (then (br $shorten_done))
        )
        (local.set $cur_fpart (local.get $trial))
        (local.set $cur_len   (i32.sub (local.get $cur_len) (i32.const 1)))
        (br $shorten_loop)
      )
    )
    (local.set $fpart (local.get $cur_fpart))
    (if (i64.ne (local.get $fpart) (i64.const 0))
      (then
        ;; Decimal point
        (i32.store8 (local.get $ptr) (i32.const 46))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        ;; Write $cur_len-digit fractional string (least significant digit first)
        (local.set $fdigits (local.get $fpart))
        (local.set $flen    (local.get $cur_len))
        (block $fdone
          (loop $floop
            (br_if $fdone (i32.eqz (local.get $flen)))
            (i32.store8
              (i32.add (local.get $ptr) (i32.sub (local.get $flen) (i32.const 1)))
              (i32.add (i32.const 48) (i32.wrap_i64 (i64.rem_u (local.get $fdigits) (i64.const 10))))
            )
            (local.set $fdigits (i64.div_u (local.get $fdigits) (i64.const 10)))
            (local.set $flen    (i32.sub   (local.get $flen)    (i32.const 1)))
            (br $floop)
          )
        )
        ;; Strip trailing zeros
        (local.set $flen (local.get $cur_len))
        (block $strip
          (loop $striploop
            (br_if $strip (i32.eqz (local.get $flen)))
            (br_if $strip
              (i32.ne
                (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $flen) (i32.const 1))))
                (i32.const 48)
              )
            )
            (local.set $flen (i32.sub (local.get $flen) (i32.const 1)))
            (br $striploop)
          )
        )
        (local.set $ptr (i32.add (local.get $ptr) (local.get $flen)))
      )
    )
    ;; Return total length written
    (i32.sub (local.get $ptr) (local.get $buf))
  )

  ;; ── i64 → decimal string ──────────────────────────────────────────────────
  ;; Writes the decimal representation of $val at $buf, returns byte count.
  (func $__i64_to_str (param $val i64) (param $buf i32) (result i32)
    (local $start i32)
    (local $end i32)
    (local $tmp i32)
    (local $ch i32)
    (local $neg i32)
    (local $digit i32)
    (local $orig i32)
    (local.set $orig (local.get $buf))
    (local.set $start (local.get $buf))
    ;; Zero
    (if (i64.eqz (local.get $val))
      (then
        (i32.store8 (local.get $buf) (i32.const 48))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 110))
        (return (i32.const 2))
      )
    )
    ;; Negative
    (if (i64.lt_s (local.get $val) (i64.const 0))
      (then
        (i32.store8 (local.get $buf) (i32.const 45))
        (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
        (local.set $start (local.get $buf))
        (local.set $neg (i32.const 1))
        (local.set $val (i64.sub (i64.const 0) (local.get $val)))
      )
    )
    (local.set $end (local.get $buf))
    ;; Write digits in reverse
    (block $done
      (loop $loop
        (br_if $done (i64.eqz (local.get $val)))
        (local.set $digit (i32.wrap_i64 (i64.rem_u (local.get $val) (i64.const 10))))
        (i32.store8
          (local.get $end)
          (i32.add (i32.const 48) (local.get $digit))
        )
        (local.set $val (i64.div_u (local.get $val) (i64.const 10)))
        (local.set $end (i32.add (local.get $end) (i32.const 1)))
        (br $loop)
      )
    )
    ;; Reverse digit bytes in-place
    (local.set $tmp (local.get $start))
    (local.set $ch (i32.sub (local.get $end) (i32.const 1)))
    (block $rdone
      (loop $rloop
        (br_if $rdone (i32.ge_u (local.get $tmp) (local.get $ch)))
        (local.set $neg (i32.load8_u (local.get $tmp)))
        (i32.store8 (local.get $tmp) (i32.load8_u (local.get $ch)))
        (i32.store8 (local.get $ch) (local.get $neg))
        (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
        (local.set $ch (i32.sub (local.get $ch) (i32.const 1)))
        (br $rloop)
      )
    )
    ;; Append 'n' suffix for bigint display
    (i32.store8 (local.get $end) (i32.const 110))
    (local.set $end (i32.add (local.get $end) (i32.const 1)))
    ;; Return total length (including leading '-' and trailing 'n')
    (i32.sub (local.get $end) (local.get $orig))
  )
  ;; Dynamic array grow_string: malloc new block of newcap elements, copy data, return new ptr.
  (func $__dynarr_grow_string (param $arr i32) (param $newcap i32) (result i32)
    (local $newptr i32)
    (local $len i32)
    (local $i i32)
    (local.set $len (i32.load (local.get $arr)))
    (local.set $newptr (call $__malloc (i32.add (i32.const 8) (i32.shl (local.get $newcap) (i32.const 3)))))
    (i32.store (local.get $newptr) (local.get $len))
    (i32.store offset=4 (local.get $newptr) (local.get $newcap))
    (local.set $i (i32.const 0))
    (block $brk
      (loop $lp
        (br_if $brk (i32.ge_u (local.get $i) (local.get $len)))
        (f64.store
          (i32.add (i32.add (local.get $newptr) (i32.const 8)) (i32.shl (local.get $i) (i32.const 3)))
          (f64.load
            (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (local.get $i) (i32.const 3)))
          )
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)
      )
    )
    (local.get $newptr)
  )

  ;; Dynamic string array push_string: grow if full, store (ptr,len) at end, return new arr ptr.
  (func $__dynarr_push_string (param $arr i32) (param $ptr i32) (param $len i32) (result i32)
    (local $elemLen i32)
    (local $cap i32)
    (local $base i32)
    (local.set $elemLen (i32.load (local.get $arr)))
    (local.set $cap (i32.load offset=4 (local.get $arr)))
    (if (i32.ge_u (local.get $elemLen) (local.get $cap))
      (then
        (local.set $arr (call $__dynarr_grow_string (local.get $arr) (i32.shl (local.get $cap) (i32.const 1))))
      )
    )
    (local.set $base (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (local.get $elemLen) (i32.const 3))))
    (i32.store (local.get $base) (local.get $ptr))
    (i32.store offset=4 (local.get $base) (local.get $len))
    (i32.store (local.get $arr) (i32.add (local.get $elemLen) (i32.const 1)))
    (local.get $arr)
  )
  (func $contains (param $s_ptr i32) (param $s_len i32) (param $sub_ptr i32) (param $sub_len i32) (result i32)
    (local $__iface_tmp i32)
    (return (i32.ge_s (call $__str_indexof (local.get $s_ptr) (local.get $s_len) (local.get $sub_ptr) (local.get $sub_len)) (i32.const 0)))
  )

  (func $count (param $s_ptr i32) (param $s_len i32) (param $sub_ptr i32) (param $sub_len i32) (result f64)
    (local $n f64)
    (local $pos f64)
    (local $idx f64)
    (local $__iface_tmp i32)
    (if (i32.eq (local.get $sub_len) (i32.const 0))
      (then
      (return (f64.add (f64.convert_i32_s (local.get $s_len)) (f64.const 1)))
      )
    )
    (local.set $n (f64.const 0))
    (local.set $pos (f64.const 0))
    (block $break_0
      (loop $loop_0
        (br_if $break_0 (i32.eqz (i32.const 1)))
        (block $cont_0
          (local.set $idx (f64.convert_i32_s (call $__str_indexof_from (local.get $s_ptr) (local.get $s_len) (local.get $sub_ptr) (local.get $sub_len) (i32.trunc_f64_s (local.get $pos)))))
          (if (f64.lt (local.get $idx) (f64.const 0))
            (then
            (br $break_0)
            )
          )
          (local.set $n (f64.add (local.get $n) (f64.const 1)))
          (local.set $pos (f64.add (local.get $idx) (f64.convert_i32_s (local.get $sub_len))))
        )
        (br $loop_0)
      )
    )
    (return (local.get $n))
  )

  (func $hasPrefix (param $s_ptr i32) (param $s_len i32) (param $prefix_ptr i32) (param $prefix_len i32) (result i32)
    (local $__iface_tmp i32)
    (local $__str_op_ptr i32)
    (local $__str_op_len i32)
    (return (i32.and (i32.ge_s (local.get $s_len) (local.get $prefix_len)) (i32.eqz (call $__str_cmp (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.const 0) (local.get $prefix_len)) (local.get $prefix_ptr) (local.get $prefix_len)))))
  )

  (func $hasSuffix (param $s_ptr i32) (param $s_len i32) (param $suffix_ptr i32) (param $suffix_len i32) (result i32)
    (local $__iface_tmp i32)
    (local $__str_op_ptr i32)
    (local $__str_op_len i32)
    (return (i32.and (i32.ge_s (local.get $s_len) (local.get $suffix_len)) (i32.eqz (call $__str_cmp (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.sub (local.get $s_len) (local.get $suffix_len)) (local.get $s_len)) (local.get $suffix_ptr) (local.get $suffix_len)))))
  )

  (func $strIndex (param $s_ptr i32) (param $s_len i32) (param $sub_ptr i32) (param $sub_len i32) (result f64)
    (local $__iface_tmp i32)
    (return (f64.convert_i32_s (call $__str_indexof (local.get $s_ptr) (local.get $s_len) (local.get $sub_ptr) (local.get $sub_len))))
  )

  (func $join (param $arr i32) (param $sep_ptr i32) (param $sep_len i32) 
    (local $r_ptr i32)
    (local $r_len i32)
    (local $i f64)
    (local $__ret_str_ptr i32)
    (local $__ret_str_len i32)
    (local.set $r_ptr (i32.const 260))
      (local.set $r_len (i32.const 0))
    (local.set $i (f64.const 0))
    (block $break_1
      (loop $loop_1
        (br_if $break_1 (i32.eqz (f64.lt (local.get $i) (f64.convert_i32_s (i32.load (local.get $arr))))))
        (block $cont_1
          (if (f64.gt (local.get $i) (f64.const 0))
            (then
            (local.set $r_ptr (local.get $r_ptr))
      (local.set $r_len (local.get $r_len))
      (call $__str_concat (local.get $r_ptr) (local.get $r_len) (local.get $sep_ptr) (local.get $sep_len))
      (local.set $r_len)
      (local.set $r_ptr)
            )
          )
          (local.set $r_ptr (local.get $r_ptr))
      (local.set $r_len (local.get $r_len))
      (call $__str_concat (local.get $r_ptr) (local.get $r_len) (i32.load (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (i32.trunc_f64_s (local.get $i)) (i32.const 3)))) (i32.load offset=4 (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (i32.trunc_f64_s (local.get $i)) (i32.const 3)))))
      (local.set $r_len)
      (local.set $r_ptr)
        )
        (local.set $i (f64.add (local.get $i) (f64.const 1)))
        (br $loop_1)
      )
    )
    (local.set $__ret_str_ptr (local.get $r_ptr))
      (local.set $__ret_str_len (local.get $r_len))
      (global.set $__str_ret_ptr (local.get $__ret_str_ptr))
      (global.set $__str_ret_len (local.get $__ret_str_len))
      (return)
  )

  (func $repeat (param $s_ptr i32) (param $s_len i32) (param $n f64) 
    (local $r_ptr i32)
    (local $r_len i32)
    (local $i f64)
    (local $__ret_str_ptr i32)
    (local $__ret_str_len i32)
    (local.set $r_ptr (i32.const 260))
      (local.set $r_len (i32.const 0))
    (local.set $i (f64.const 0))
    (block $break_2
      (loop $loop_2
        (br_if $break_2 (i32.eqz (f64.lt (local.get $i) (local.get $n))))
        (block $cont_2
          (local.set $r_ptr (local.get $r_ptr))
      (local.set $r_len (local.get $r_len))
      (call $__str_concat (local.get $r_ptr) (local.get $r_len) (local.get $s_ptr) (local.get $s_len))
      (local.set $r_len)
      (local.set $r_ptr)
        )
        (local.set $i (f64.add (local.get $i) (f64.const 1)))
        (br $loop_2)
      )
    )
    (local.set $__ret_str_ptr (local.get $r_ptr))
      (local.set $__ret_str_len (local.get $r_len))
      (global.set $__str_ret_ptr (local.get $__ret_str_ptr))
      (global.set $__str_ret_len (local.get $__ret_str_len))
      (return)
  )

  (func $replaceAll (param $s_ptr i32) (param $s_len i32) (param $old_ptr i32) (param $old_len i32) (param $nw_ptr i32) (param $nw_len i32) 
    (local $r_ptr i32)
    (local $r_len i32)
    (local $pos f64)
    (local $idx f64)
    (local $__iface_tmp i32)
    (local $__ret_str_ptr i32)
    (local $__ret_str_len i32)
    (local $__str_op_ptr i32)
    (local $__str_op_len i32)
    (local.set $r_ptr (i32.const 260))
      (local.set $r_len (i32.const 0))
    (local.set $pos (f64.const 0))
    (block $break_3
      (loop $loop_3
        (br_if $break_3 (i32.eqz (i32.const 1)))
        (block $cont_3
          (local.set $idx (f64.convert_i32_s (call $__str_indexof_from (local.get $s_ptr) (local.get $s_len) (local.get $old_ptr) (local.get $old_len) (i32.trunc_f64_s (local.get $pos)))))
          (if (f64.lt (local.get $idx) (f64.const 0))
            (then
            (local.set $r_ptr (local.get $r_ptr))
      (local.set $r_len (local.get $r_len))
      (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.trunc_f64_s (local.get $pos)) (local.get $s_len))
      (local.set $__str_op_len)
      (local.set $__str_op_ptr)
      (call $__str_concat (local.get $r_ptr) (local.get $r_len) (local.get $__str_op_ptr) (local.get $__str_op_len))
      (local.set $r_len)
      (local.set $r_ptr)
            (br $break_3)
            )
          )
          (local.set $r_ptr (local.get $r_ptr))
      (local.set $r_len (local.get $r_len))
      (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.trunc_f64_s (local.get $pos)) (i32.trunc_f64_s (local.get $idx)))
      (local.set $__str_op_len)
      (local.set $__str_op_ptr)
      (call $__str_concat (local.get $r_ptr) (local.get $r_len) (local.get $__str_op_ptr) (local.get $__str_op_len))
      (local.set $r_len)
      (local.set $r_ptr)
      (call $__str_concat (local.get $r_ptr) (local.get $r_len) (local.get $nw_ptr) (local.get $nw_len))
      (local.set $r_len)
      (local.set $r_ptr)
          (local.set $pos (f64.add (local.get $idx) (f64.convert_i32_s (local.get $old_len))))
        )
        (br $loop_3)
      )
    )
    (local.set $__ret_str_ptr (local.get $r_ptr))
      (local.set $__ret_str_len (local.get $r_len))
      (global.set $__str_ret_ptr (local.get $__ret_str_ptr))
      (global.set $__str_ret_len (local.get $__ret_str_len))
      (return)
  )

  (func $replace (param $s_ptr i32) (param $s_len i32) (param $old_ptr i32) (param $old_len i32) (param $nw_ptr i32) (param $nw_len i32) 
    (local $idx f64)
    (local $__iface_tmp i32)
    (local $__ret_str_ptr i32)
    (local $__ret_str_len i32)
    (local $__str_op_ptr i32)
    (local $__str_op_len i32)
    (local.set $idx (f64.convert_i32_s (call $__str_indexof (local.get $s_ptr) (local.get $s_len) (local.get $old_ptr) (local.get $old_len))))
    (if (f64.lt (local.get $idx) (f64.const 0))
      (then
      (local.set $__ret_str_ptr (local.get $s_ptr))
      (local.set $__ret_str_len (local.get $s_len))
      (global.set $__str_ret_ptr (local.get $__ret_str_ptr))
      (global.set $__str_ret_len (local.get $__ret_str_len))
      (return)
      )
    )
    (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.const 0) (i32.trunc_f64_s (local.get $idx)))
      (local.set $__str_op_len)
      (local.set $__str_op_ptr)
      (local.set $__ret_str_ptr (local.get $__str_op_ptr))
      (local.set $__ret_str_len (local.get $__str_op_len))
      (call $__str_concat (local.get $__ret_str_ptr) (local.get $__ret_str_len) (local.get $nw_ptr) (local.get $nw_len))
      (local.set $__ret_str_len)
      (local.set $__ret_str_ptr)
      (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.trunc_f64_s (f64.add (local.get $idx) (f64.convert_i32_s (local.get $old_len)))) (local.get $s_len))
      (local.set $__str_op_len)
      (local.set $__str_op_ptr)
      (call $__str_concat (local.get $__ret_str_ptr) (local.get $__ret_str_len) (local.get $__str_op_ptr) (local.get $__str_op_len))
      (local.set $__ret_str_len)
      (local.set $__ret_str_ptr)
      (global.set $__str_ret_ptr (local.get $__ret_str_ptr))
      (global.set $__str_ret_len (local.get $__ret_str_len))
      (return)
  )

  (func $split (param $s_ptr i32) (param $s_len i32) (param $sep_ptr i32) (param $sep_len i32) (result i32)
    (local $parts i32)
    (local $pos f64)
    (local $idx f64)
    (local $__str_push_ptr i32)
    (local $__str_push_len i32)
    (local $__iface_tmp i32)
    (local $__str_op_ptr i32)
    (local $__str_op_len i32)
    (local.set $parts (call $__malloc (i32.const 72)))
      (i32.store (local.get $parts) (i32.const 0))
      (i32.store offset=4 (local.get $parts) (i32.const 8))
    (local.set $pos (f64.const 0))
    (block $break_4
      (loop $loop_4
        (br_if $break_4 (i32.eqz (i32.const 1)))
        (block $cont_4
          (local.set $idx (f64.convert_i32_s (call $__str_indexof_from (local.get $s_ptr) (local.get $s_len) (local.get $sep_ptr) (local.get $sep_len) (i32.trunc_f64_s (local.get $pos)))))
          (if (f64.lt (local.get $idx) (f64.const 0))
            (then
            (local.set $parts (call $__dynarr_push_string (local.get $parts) (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.trunc_f64_s (local.get $pos)) (local.get $s_len)) ))
            (br $break_4)
            )
          )
          (local.set $parts (call $__dynarr_push_string (local.get $parts) (call $__str_slice (local.get $s_ptr) (local.get $s_len) (i32.trunc_f64_s (local.get $pos)) (i32.trunc_f64_s (local.get $idx))) ))
          (local.set $pos (f64.add (local.get $idx) (f64.convert_i32_s (local.get $sep_len))))
        )
        (br $loop_4)
      )
    )
    (return (local.get $parts))
  )

  (func $strArrStr (param $arr i32) 
    (local $s_ptr i32)
    (local $s_len i32)
    (local $i f64)
    (local $__ret_str_ptr i32)
    (local $__ret_str_len i32)
    (local.set $s_ptr (i32.const 260))
      (local.set $s_len (i32.const 1))
    (local.set $i (f64.const 0))
    (block $break_5
      (loop $loop_5
        (br_if $break_5 (i32.eqz (f64.lt (local.get $i) (f64.convert_i32_s (i32.load (local.get $arr))))))
        (block $cont_5
          (if (f64.gt (local.get $i) (f64.const 0))
            (then
            (local.set $s_ptr (local.get $s_ptr))
      (local.set $s_len (local.get $s_len))
      (call $__str_concat (local.get $s_ptr) (local.get $s_len) (i32.const 261) (i32.const 1))
      (local.set $s_len)
      (local.set $s_ptr)
            )
          )
          (local.set $s_ptr (local.get $s_ptr))
      (local.set $s_len (local.get $s_len))
      (call $__str_concat (local.get $s_ptr) (local.get $s_len) (i32.load (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (i32.trunc_f64_s (local.get $i)) (i32.const 3)))) (i32.load offset=4 (i32.add (i32.add (local.get $arr) (i32.const 8)) (i32.shl (i32.trunc_f64_s (local.get $i)) (i32.const 3)))))
      (local.set $s_len)
      (local.set $s_ptr)
        )
        (local.set $i (f64.add (local.get $i) (f64.const 1)))
        (br $loop_5)
      )
    )
    (local.set $__ret_str_ptr (local.get $s_ptr))
      (local.set $__ret_str_len (local.get $s_len))
      (call $__str_concat (local.get $__ret_str_ptr) (local.get $__ret_str_len) (i32.const 262) (i32.const 1))
      (local.set $__ret_str_len)
      (local.set $__ret_str_ptr)
      (global.set $__str_ret_ptr (local.get $__ret_str_ptr))
      (global.set $__str_ret_len (local.get $__ret_str_len))
      (return)
  )
  (func $_start (export "_start")
    (local $__iface_tmp i32)
        (i32.store (i32.const 0) (i32.const 269))
          (i32.store (i32.const 4) (i32.const 12))
          (i32.store (i32.const 8) (if (result i32) (call $contains (i32.const 263) (i32.const 4) (i32.const 267) (i32.const 2)) (then (i32.const 281)) (else (i32.const 285))))
          (i32.store (i32.const 12) (if (result i32) (call $contains (i32.const 263) (i32.const 4) (i32.const 267) (i32.const 2)) (then (i32.const 4)) (else (i32.const 5))))
          (i32.store (i32.const 16) (i32.const 290))
          (i32.store (i32.const 20) (i32.const 1))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 3)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 67))
          (i32.store8 (i32.const 133) (i32.const 111))
          (i32.store8 (i32.const 134) (i32.const 117))
          (i32.store8 (i32.const 135) (i32.const 110))
          (i32.store8 (i32.const 136) (i32.const 116))
          (i32.store8 (i32.const 137) (i32.const 58))
          (i32.store8 (i32.const 138) (i32.const 32))
          (i32.store8 (i32.const 139) (i32.const 32))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (call $__f64_to_str (call $count (i32.const 263) (i32.const 4) (i32.const 291) (i32.const 1)) (i32.const 144))))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 294))
          (i32.store (i32.const 4) (i32.const 12))
          (i32.store (i32.const 8) (if (result i32) (call $hasPrefix (i32.const 263) (i32.const 4) (i32.const 292) (i32.const 2)) (then (i32.const 281)) (else (i32.const 285))))
          (i32.store (i32.const 12) (if (result i32) (call $hasPrefix (i32.const 263) (i32.const 4) (i32.const 292) (i32.const 2)) (then (i32.const 4)) (else (i32.const 5))))
          (i32.store (i32.const 16) (i32.const 290))
          (i32.store (i32.const 20) (i32.const 1))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 3)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 308))
          (i32.store (i32.const 4) (i32.const 12))
          (i32.store (i32.const 8) (if (result i32) (call $hasSuffix (i32.const 263) (i32.const 4) (i32.const 306) (i32.const 2)) (then (i32.const 281)) (else (i32.const 285))))
          (i32.store (i32.const 12) (if (result i32) (call $hasSuffix (i32.const 263) (i32.const 4) (i32.const 306) (i32.const 2)) (then (i32.const 4)) (else (i32.const 5))))
          (i32.store (i32.const 16) (i32.const 290))
          (i32.store (i32.const 20) (i32.const 1))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 3)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 73))
          (i32.store8 (i32.const 133) (i32.const 110))
          (i32.store8 (i32.const 134) (i32.const 100))
          (i32.store8 (i32.const 135) (i32.const 101))
          (i32.store8 (i32.const 136) (i32.const 120))
          (i32.store8 (i32.const 137) (i32.const 58))
          (i32.store8 (i32.const 138) (i32.const 32))
          (i32.store8 (i32.const 139) (i32.const 32))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (call $__f64_to_str (call $strIndex (i32.const 263) (i32.const 4) (i32.const 320) (i32.const 1)) (i32.const 144))))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 74))
          (i32.store8 (i32.const 133) (i32.const 111))
          (i32.store8 (i32.const 134) (i32.const 105))
          (i32.store8 (i32.const 135) (i32.const 110))
          (i32.store8 (i32.const 136) (i32.const 58))
          (i32.store8 (i32.const 137) (i32.const 32))
          (i32.store8 (i32.const 138) (i32.const 32))
          (i32.store8 (i32.const 139) (i32.const 32))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (call $join (i32.const 323) (i32.const 347) (i32.const 1))
          (call $__str_gather (global.get $__str_ret_ptr) (global.get $__str_ret_len) (i32.const 144))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (global.get $__str_ret_len)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 82))
          (i32.store8 (i32.const 133) (i32.const 101))
          (i32.store8 (i32.const 134) (i32.const 112))
          (i32.store8 (i32.const 135) (i32.const 101))
          (i32.store8 (i32.const 136) (i32.const 97))
          (i32.store8 (i32.const 137) (i32.const 116))
          (i32.store8 (i32.const 138) (i32.const 58))
          (i32.store8 (i32.const 139) (i32.const 32))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (call $repeat (i32.const 321) (i32.const 1) (f64.const 5))
          (call $__str_gather (global.get $__str_ret_ptr) (global.get $__str_ret_len) (i32.const 144))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (global.get $__str_ret_len)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 82))
          (i32.store8 (i32.const 133) (i32.const 101))
          (i32.store8 (i32.const 134) (i32.const 112))
          (i32.store8 (i32.const 135) (i32.const 108))
          (i32.store8 (i32.const 136) (i32.const 97))
          (i32.store8 (i32.const 137) (i32.const 99))
          (i32.store8 (i32.const 138) (i32.const 101))
          (i32.store8 (i32.const 139) (i32.const 58))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (call $replaceAll (i32.const 348) (i32.const 3) (i32.const 351) (i32.const 1) (i32.const 352) (i32.const 1))
          (call $__str_gather (global.get $__str_ret_ptr) (global.get $__str_ret_len) (i32.const 144))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (global.get $__str_ret_len)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 82))
          (i32.store8 (i32.const 133) (i32.const 101))
          (i32.store8 (i32.const 134) (i32.const 112))
          (i32.store8 (i32.const 135) (i32.const 108))
          (i32.store8 (i32.const 136) (i32.const 97))
          (i32.store8 (i32.const 137) (i32.const 99))
          (i32.store8 (i32.const 138) (i32.const 101))
          (i32.store8 (i32.const 139) (i32.const 58))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (call $replace (i32.const 348) (i32.const 3) (i32.const 351) (i32.const 1) (i32.const 352) (i32.const 1))
          (call $__str_gather (global.get $__str_ret_ptr) (global.get $__str_ret_len) (i32.const 144))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (global.get $__str_ret_len)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 132))
          (i32.store (i32.const 4) (i32.const 0))
          (i32.store8 (i32.const 132) (i32.const 83))
          (i32.store8 (i32.const 133) (i32.const 112))
          (i32.store8 (i32.const 134) (i32.const 108))
          (i32.store8 (i32.const 135) (i32.const 105))
          (i32.store8 (i32.const 136) (i32.const 116))
          (i32.store8 (i32.const 137) (i32.const 58))
          (i32.store8 (i32.const 138) (i32.const 32))
          (i32.store8 (i32.const 139) (i32.const 32))
          (i32.store8 (i32.const 140) (i32.const 32))
          (i32.store8 (i32.const 141) (i32.const 32))
          (i32.store8 (i32.const 142) (i32.const 32))
          (i32.store8 (i32.const 143) (i32.const 32))
          (call $strArrStr (call $split (i32.const 353) (i32.const 9) (i32.const 347) (i32.const 1)))
          (call $__str_gather (global.get $__str_ret_ptr) (global.get $__str_ret_len) (i32.const 144))
          (i32.store (i32.const 4) (i32.add (i32.const 12) (global.get $__str_ret_len)))
          (i32.store8 (i32.add (i32.const 132) (i32.load (i32.const 4))) (i32.const 10))
          (i32.store (i32.const 4) (i32.add (i32.load (i32.const 4)) (i32.const 1)))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 362))
          (i32.store (i32.const 4) (i32.const 17))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
        (i32.store (i32.const 0) (i32.const 379))
          (i32.store (i32.const 4) (i32.const 17))
          (drop (call $fd_write
            (i32.const 1)
            (i32.const 0)
            (i32.const 1)
            (i32.const 128)))
    (call $proc_exit (i32.const 0))
  )
  (data (i32.const 260) "")
  (data (i32.const 260) "\5b")
  (data (i32.const 261) "\20")
  (data (i32.const 262) "\5d")
  (data (i32.const 263) "\74\65\73\74")
  (data (i32.const 267) "\65\73")
  (data (i32.const 269) "\43\6f\6e\74\61\69\6e\73\3a\20\20\20")
  (data (i32.const 281) "\74\72\75\65")
  (data (i32.const 285) "\66\61\6c\73\65")
  (data (i32.const 290) "\0a")
  (data (i32.const 291) "\74")
  (data (i32.const 292) "\74\65")
  (data (i32.const 294) "\48\61\73\50\72\65\66\69\78\3a\20\20")
  (data (i32.const 306) "\73\74")
  (data (i32.const 308) "\48\61\73\53\75\66\66\69\78\3a\20\20")
  (data (i32.const 320) "\65")
  (data (i32.const 321) "\61")
  (data (i32.const 322) "\62")
  (data (i32.const 347) "\2d")
  (data (i32.const 348) "\66\6f\6f")
  (data (i32.const 351) "\6f")
  (data (i32.const 352) "\30")
  (data (i32.const 353) "\61\2d\62\2d\63\2d\64\2d\65")
  (data (i32.const 362) "\54\6f\4c\6f\77\65\72\3a\20\20\20\20\74\65\73\74\0a")
  (data (i32.const 379) "\54\6f\55\70\70\65\72\3a\20\20\20\20\54\45\53\54\0a")
  (data (i32.const 323) "\02\00\00\00\02\00\00\00\41\01\00\00\01\00\00\00\42\01\00\00\01\00\00\00")
)