// Embeds the Tier-1 stdlib capability libraries (Set/Map/Date/JSON/RegExp) into
// src/wasm/caps_bytes.ts as a registry of { prefix, bytes, wit }. Drives the virtual
// `wasmtk:<cap>` import resolution + feature-level tree-shake (stdlib-bundling brief §7-#4).
//
// Each capability's authoritative source is its modc fixture under
// tests/wasm_wasi_bundle/<cap>_bundle/<cap>_lib_modc.ts. Recompile those via
//   wasmtk modc tests/wasm_wasi_bundle/<cap>_bundle/<cap>_lib_modc.ts
// (or run scripts/build_caps.ts) before regenerating, so the embedded bytes match
// the current compiler.
//
// Usage: deno run --allow-read --allow-write scripts/gen_caps_bytes.ts

import { dirname, fromFileUrl, join } from "jsr:@std/path";

const scriptDir = dirname(fromFileUrl(import.meta.url));
const root = join(scriptDir, "..");

// capability id → bundle dir / file base. The id is what users import: `wasmtk:set`.
const CAPS: { id: string; dir: string; base: string }[] = [
  { id: "set", dir: "set_bundle", base: "set_lib_modc" },
  { id: "map", dir: "map_bundle", base: "map_lib_modc" },
  { id: "date", dir: "date_bundle", base: "date_lib_modc" },
  { id: "json", dir: "json_bundle", base: "json_lib_modc" },
  { id: "regex", dir: "regex_bundle", base: "regex_lib_modc" },
];

const parts: string[] = [];
for (const cap of CAPS) {
  const wasmPath = join(root, "tests", "wasm_wasi_bundle", cap.dir, `${cap.base}.wasm`);
  const witPath = join(root, "tests", "wasm_wasi_bundle", cap.dir, `${cap.base}.wit`);
  const bytes = await Deno.readFile(wasmPath);
  const wit = await Deno.readTextFile(witPath);
  const hex = Array.from(bytes).map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ");
  parts.push(
    `  ${cap.id}: {\n` +
      `    prefix: "${cap.id}",\n` +
      `    wit: ${JSON.stringify(wit)},\n` +
      `    bytes: new Uint8Array([${hex}]),\n` +
      `  },`,
  );
  console.log(`  ${cap.id}: ${bytes.length} bytes`);
}

const out = `// AUTO-GENERATED by scripts/gen_caps_bytes.ts — do not edit manually.
// Regenerate: deno run --allow-read --allow-write scripts/gen_caps_bytes.ts
//
// Embedded Tier-1 stdlib capability libraries, resolved by the virtual \`wasmtk:<cap>\`
// import specifier and merged on demand (only when a program imports them).

/** One embedded capability library: its merge prefix, raw modc \`.wasm\` bytes, and \`.wit\` text. */
export interface CapabilityDef {
  /** Merge prefix (also the capability id and the \`wasmtk:<id>\` specifier suffix). */
  prefix: string;
  /** Sibling \`.wit\` text — supplies logical signatures (string params) for the merge. */
  wit: string;
  /** modc-compiled module bytes. */
  bytes: Uint8Array;
}

/** capability id → definition. Keys are the suffixes accepted after \`wasmtk:\`. */
export const CAPABILITIES: Record<string, CapabilityDef> = {
${parts.join("\n")}
};
`;

const outPath = join(root, "src", "wasm", "caps_bytes.ts");
await Deno.writeTextFile(outPath, out);
console.log(`✅ Wrote ${outPath}`);
