// Reads src/wasm/mathlib.wasm and writes src/wasm/mathlib_bytes.ts as a
// Uint8Array constant. Run this after recompiling mathlib.wat.
//
// Usage: deno run --allow-read --allow-write scripts/gen_mathlib_bytes.ts

import { join, dirname, fromFileUrl } from "jsr:@std/path";

const scriptDir = dirname(fromFileUrl(import.meta.url));
const root = join(scriptDir, "..");
const wasmPath = join(root, "src", "wasm", "mathlib.wasm");
const outPath  = join(root, "src", "wasm", "mathlib_bytes.ts");

const bytes = await Deno.readFile(wasmPath);
const hex = Array.from(bytes)
  .map(b => "0x" + b.toString(16).padStart(2, "0"))
  .join(", ");

const header = [
  `// AUTO-GENERATED by scripts/gen_mathlib_bytes.ts — do not edit manually.`,
  `// Recompile: wasmtk convert src/wasm/mathlib.wat`,
  `// Regenerate: deno run --allow-read --allow-write scripts/gen_mathlib_bytes.ts`,
  `// ${bytes.length} bytes`,
].join("\n");

const content = `${header}\nexport const MATHLIB_BYTES = new Uint8Array([${hex}]);\n`;

await Deno.writeTextFile(outPath, content);
console.log(`✅ Wrote ${bytes.length} bytes → ${outPath}`);
