// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

async function step1__impl(x: i32): Promise<i32> {
  return x + 1;
}
export function step1(x: i32): i32 {
  return await step1__impl(x);
}

async function process__impl(data: i32): Promise<i32> {
  const a: i32 = await step1__impl(data);
  return a * 10;
}
export function process(data: i32): i32 {
  return await process__impl(data);
}

async function scale__impl(x: f64): Promise<f64> {
  return x * 2.5;
}
export function scale(x: f64): f64 {
  return await scale__impl(x);
}
