// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file


import { loadModule } from "./dynamic_partial_hybrid_core.bindings.ts";

const lib = await loadModule(new URL("./dynamic_partial_hybrid_core.wasm", import.meta.url));

// #14 fallback refinement — one GOOD dynamic body (eval+any, compiles) and one BAD (undefined call).
// Only `badDynamic` should fall back to the host; `goodDynamic` + `plus1` stay in the WASM core.

export function badDynamic(n: f64): f64 {
  const o: any = eval("'x'");
  return notAFunction(o) as f64; // undefined → fails to compile → fall back to host
}


const a: f64 = lib.goodDynamic(8); // 50
const b: f64 = lib.plus1(41); // 42
console.log("goodDynamic(8) =", a);
console.log("plus1(41) =", b);
