// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file


import { loadModule } from "./dynamic_fallback_hybrid_core.bindings.ts";

const lib = await loadModule(new URL("./dynamic_fallback_hybrid_core.wasm", import.meta.url));

// #14.3.4 fallback — a dynamic-bodied function that wasic+dynrt CANNOT compile (calls an undefined
// function) must fall back to the TS host instead of failing the whole build; the static `plus1`
// still routes to WASM.
export function brokenDynamic(n: f64): f64 {
  const o: any = eval("'x'");
  return notAFunction(o) as f64; // undefined function → core compile fails → fallback to host
}


const r: f64 = lib.plus1(41);
console.log("plus1(41) =", r);
