// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file


import { loadModule } from "./math_hybrid_core.bindings.ts";

const lib = await loadModule(new URL("./math_hybrid_core.wasm", import.meta.url));

// A mixed TypeScript + WASM example.
// Functions annotated with // @wasm are compiled to WASM; the rest stays TypeScript.




// Runtime-only: uses template literals, console.log — stays in TypeScript
function describe(label: string, value: unknown): void {
  console.log(`${label}: ${value}`);
}

// Main entry point — calls @wasm functions through lib after hybrid split
const x = lib.add(10, 32);
const y = lib.multiply(3.0, 1.5);
const even = lib.isEven(x);

describe("add(10, 32)", x);
describe("multiply(3.0, 1.5)", y);
describe("isEven(42)", even);
