// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

export function add(a: i32, b: i32): i32 {
  return a + b;
}

export function multiply(a: f64, b: f64): f64 {
  return a * b;
}

export function isEven(n: i32): bool {
  return (n % 2) === 0;
}
