// auto-generated by wasmtk bindgen — do not edit manually
// source: strings-hybrid-core
// deno-lint-ignore-file

export interface ModuleExports {
  greet(name: string): string;
  strLen(s: string): number;
}

export async function loadModule(
  source: string | URL | BufferSource,
): Promise<ModuleExports> {
  const importObj: Record<string, Record<string, unknown>> = {};
  let raw: ArrayBuffer;
  if (source instanceof ArrayBuffer) {
    raw = source;
  } else if (ArrayBuffer.isView(source)) {
    raw = (source as Uint8Array).buffer as ArrayBuffer;
  } else {
    raw = await (await fetch(String(source))).arrayBuffer();
  }
  const { instance } = await WebAssembly.instantiate(raw, importObj);
  const exp = instance.exports as Record<string, unknown>;
  const _mem = exp["memory"] as WebAssembly.Memory;
  const _malloc = exp["__malloc"] as ((n: number) => number);
  function _writeStr(s: string): [number, number] {
    const b = new TextEncoder().encode(s);
    const ptr = _malloc(b.length);
    new Uint8Array(_mem.buffer).set(b, ptr);
    return [ptr, b.length];
  }
  const _strRetPtr = exp["__str_ret_ptr"] as WebAssembly.Global;
  const _strRetLen = exp["__str_ret_len"] as WebAssembly.Global;
  function _readStr(): string {
    const p = (_strRetPtr as unknown as { value: number }).value as number;
    const l = (_strRetLen as unknown as { value: number }).value as number;
    return new TextDecoder().decode(new Uint8Array(_mem.buffer, p, l));
  }
  return {
    greet(name: string): string {
      (exp["greet"] as (...a: unknown[]) => unknown)(..._writeStr(name));
      return _readStr();
    },
    strLen(s: string): number { return (exp["strLen"] as (...a: unknown[]) => unknown)(..._writeStr(s)) as number; },
  };
}
