/**
 * @module dync
 * @description Full-dynamic-compile entry — the `javyc` replacement (#14 Route A, 2h).
 *
 * Compiles an ENTIRE TypeScript/JavaScript file into a self-contained WASI module by routing its
 * source through wasmtk's OWN dynamic runtime (`wasmtk:dynrt`, the boxed-value interpreter embedded in
 * the compiler) — no external Javy/QuickJS binary and no ~500 KB embedded engine. The whole program is
 * embedded as a string and executed by the interpreter at module start; `console.log`/`error`/`warn`
 * print to stdout via the runtime's host-print import.
 *
 * This is for fully-dynamic programs (`any`, dynamic objects, `eval`, etc.) that `wasic` cannot compile
 * statically. For statically-typed TypeScript prefer `wasic` (smaller, faster, fully validated).
 *
 * Scope (v1): a single self-contained file. The interpreter understands the dynrt language subset
 * (see cmem/dynrt-design.md) — top-level statements, functions/closures/classes, the Array/String/
 * Object/Math/JSON/Map/Set/RegExp stdlib, generators, async/await, and `console.log`. Out of scope:
 * `import`/`export` of other modules and interactive `prompt` (no host stdin in the interpreter).
 */

import { basename, dirname } from "@std/path";
import { rt } from "./rt.ts";
import { compileWasiTs } from "./wasic.ts";

/**
 * Encodes arbitrary source text as base64. The whole program is embedded in the generated wasic
 * driver as a base64 string literal: the base64 alphabet (`A-Za-z0-9+/=`) contains none of `{` `}`
 * `;` `"` or newline, so wasic's (line-based, not fully string-aware) source scanner never mis-counts
 * a brace or splits a statement inside the embedded payload. The runtime decodes it back to the raw
 * UTF-8 source before interpreting. (UTF-8 first, so non-ASCII source round-trips byte-exactly.)
 */
function encodeSourceBase64(src: string): string {
  const bytes = new TextEncoder().encode(src);
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

/**
 * Compiles `path` (a .ts/.js file) into a self-contained WASI `.wasm` via the embedded dynamic runtime.
 *
 * @param path    Path to the source file.
 * @param outPath Optional output `.wasm` path (defaults to `<dir>/<name>.wasm`).
 */
export async function compileDyn(path: string, outPath?: string): Promise<void> {
  const name = basename(path).replace(/\.[^/.]+$/, "");
  const srcDir = dirname(path);
  const wasmOut = outPath ?? `${srcDir}/${name}.wasm`;

  let src: string;
  try {
    src = await rt.readTextFile(path);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`❌ dync: cannot read ${path}: ${msg}`);
    rt.exit(1);
    return;
  }

  const b64 = encodeSourceBase64(src);
  // The generated wasic driver: import the runtime by name (auto-merges only the dynrt capability),
  // make a fresh global environment, then decode + run the whole program through the interpreter.
  const driver = `// @auto-generated by \`wasmtk dync\` — do not edit. Routes ${
    basename(path)
  } through wasmtk:dynrt.
type i32 = number;
import { dynObject, dynRunB64 } from "wasmtk:dynrt";
const __dyn_b64: string = "${b64}";
const __dyn_env: i32 = dynObject();
dynRunB64(__dyn_b64, __dyn_env);
`;

  // The driver has no relative imports (only the virtual `wasmtk:dynrt`), so its location is
  // irrelevant — write it alongside the output, compile, then remove the scaffold.
  const driverPath = `${srcDir}/${name}.__dync.ts`;
  await rt.writeTextFile(driverPath, driver);
  try {
    // A dync module is a whole-program WASI command with no exports — its WIT would be an empty
    // world, so skip generating it (emitWit: false) to save a step.
    const result = await compileWasiTs(driverPath, wasmOut, { emitWit: false });
    if (!result.success) {
      if (result.error) console.error(`❌ dync: ${result.error}`);
      rt.exit(1);
      return;
    }
    console.log(`✅ dync (own dynamic runtime): ${wasmOut}`);
  } finally {
    try {
      await rt.remove(driverPath);
    } catch { /* best-effort scaffold cleanup */ }
  }
}
