/**
 * @module hybrid
 * @description Splits a TypeScript file into a wasic-compiled WASM core and a TypeScript runner.
 *
 * Any function annotated with `// @wasm` on the immediately preceding line is:
 *   1. Extracted into a generated `<base>_core.ts` module file.
 *   2. Compiled to WASM via `wasmtk modc` (library mode, no _start).
 *   3. Described by a `.wit` interface (auto-generated by Phase 41).
 *   4. Bound via `wasmtk bindgen` into a `<base>_core.bindings.ts` type-safe loader.
 *
 * A `<base>_runner.ts` file is then generated containing:
 *   - All non-annotated code from the original file (unchanged).
 *   - An import of `loadModule` from the generated bindings.
 *   - A top-level `const lib = await loadModule(...)` declaration.
 *   - Every call site that previously called an `@wasm` function rewritten to `lib.funcName(...)`.
 *
 * CLI:
 *   wasmtk hybrid <file.ts> [-o outdir]
 *
 * Constraints (prototype):
 *   - `// @wasm` must appear on the line directly before the function declaration.
 *   - Only named `function` declarations are supported (no arrow functions, no classes).
 *   - Async functions are skipped with a warning — wasic cannot compile them.
 *   - All param/return types should be wasic-compatible; incompatible types produce a warning
 *     but the function is still extracted (wasic will report an error at compile time).
 *   - Call-site rewriting uses regex; method calls (`obj.funcName(...)`) are not rewritten.
 *   - The generated runner uses top-level `await` (Deno ES module native support).
 */

import { basename, dirname, join } from "@std/path";
import { rt } from "./rt.ts";
import { compileModule } from "./modc.ts";
import { runBindgen } from "./bindgen.ts";

// ── types ────────────────────────────────────────────────────────────────────

/** A `// @wasm`-annotated function extracted from a hybrid TypeScript source file. */
export interface WasmFunc {
  /** The function's declared name. */
  name: string;
  /** Complete function source text, guaranteed to start with `export `. */
  text: string;
  /** 0-indexed line of the `// @wasm` annotation (or the function declaration when no directive). */
  lineStart: number;
  /** 0-indexed last line of the function body (its matching close brace). */
  lineEnd: number;
  /** Phase 13.5: `async function` — routed via a synchronous unwrapping wrapper in the core module. */
  isAsync?: boolean;
}

/** Result of `parseHybridFile()`: the extracted WASM functions, remaining TypeScript source, and any warnings. */
export interface ParseResult {
  /** The `// @wasm`-annotated (or auto-routed) functions extracted for WASM compilation. */
  wasmFuncs: WasmFunc[];
  /** Original source with the extracted functions (and their directive comments) removed. */
  remainingSrc: string;
  /** Diagnostic warnings emitted during parsing (e.g. skipped async or non-wasic-typed functions). */
  warnings: string[];
}

// wasic-compatible primitive type names
const WASIC_PRIMITIVES = new Set([
  "i32",
  "i64",
  "f32",
  "f64",
  "bool",
  "boolean",
  "string",
  "void",
  "never",
  "number", // maps to f64 in wasic
]);

/** Returns `true` if `t` is a wasic-compatible primitive type name (e.g. `"i32"`, `"string"`, `"bool[]"`). */
export function isWasicType(t: string): boolean {
  const clean = t.trim().replace(/\s/g, "");
  if (WASIC_PRIMITIVES.has(clean)) return true;
  if (clean.endsWith("[]")) return WASIC_PRIMITIVES.has(clean.slice(0, -2));
  return false;
}

/**
 * Static-routability analysis of a function declaration line for `--auto` mode (Brief #6).
 * A function is WASM-routable iff every parameter carries a wasic-compatible type annotation and
 * the return type is wasic-compatible. Untyped params or `any`/object/dynamic types make it
 * non-routable → it stays in the TypeScript host.
 *
 * Phase 13.5 (async lift): an `async` function IS routable when it returns `Promise<T>` with a
 * wasic-compatible `T` (or `void`). `promiseInner` is the unwrapped `T` (or `"void"`); the core
 * module routes it via a synchronous unwrapping wrapper (see `generateCoreModule`). Async without a
 * `Promise<…>` annotation is non-routable (the inner type can't be determined).
 */
export function analyzeSignature(
  decl: string,
): { isAsync: boolean; routable: boolean; reason?: string; promiseInner?: string } {
  const isAsync = /^\s*(?:export\s+)?async\s+function\b/.test(decl);
  const paramSection = decl.match(/\(([^)]*)\)/)?.[1] ?? "";
  const returnType = decl.match(/\)\s*:\s*([^{]+)/)?.[1]?.trim();
  const params = paramSection.split(",").map((p) => p.trim()).filter(Boolean);
  for (const p of params) {
    const t = p.split(":")[1]?.trim();
    if (!t) return { isAsync, routable: false, reason: `untyped parameter '${p}'` };
    if (!isWasicType(t)) return { isAsync, routable: false, reason: `parameter type '${t}'` };
  }
  // Return type: a bare wasic type, or (Phase 13.5) Promise<T> with a wasic-compatible / void T.
  let promiseInner: string | undefined;
  if (returnType) {
    const pm = returnType.match(/^Promise\s*<\s*(.+?)\s*>$/);
    if (pm) {
      promiseInner = pm[1].trim();
      if (promiseInner !== "void" && !isWasicType(promiseInner)) {
        return { isAsync, routable: false, reason: `Promise inner type '${promiseInner}'` };
      }
    } else if (!isWasicType(returnType)) {
      return { isAsync, routable: false, reason: `return type '${returnType}'` };
    }
  }
  if (isAsync && promiseInner === undefined) {
    return { isAsync, routable: false, reason: "async without Promise<T> return annotation" };
  }
  return { isAsync, routable: true, promiseInner };
}

// ── parser ───────────────────────────────────────────────────────────────────

/**
 * Walk forward from openLine until the opening brace's matching close brace.
 * String literals (`"`, `'`, `` ` ``) and comments (`//`, block) are treated as
 * opaque so a brace inside them (e.g. a `"}"` in a string) doesn't skew the depth
 * count and truncate the function. (Nested template literals — a backtick inside
 * a `${…}` interpolation — are the one residual edge; they're rare in wasic-
 * compilable bodies.)
 */
function findCloseBrace(lines: string[], openLine: number): number {
  let depth = 0;
  let seen = false;
  let inBlockComment = false;
  let strCh = ""; // "", '"', "'", or "`" when inside a string/template (opaque)
  for (let i = openLine; i < lines.length; i++) {
    const line = lines[i];
    for (let c = 0; c < line.length; c++) {
      const ch = line[c];
      const next = line[c + 1];
      if (inBlockComment) {
        if (ch === "*" && next === "/") {
          inBlockComment = false;
          c++;
        }
        continue;
      }
      if (strCh) {
        if (ch === "\\") c++; // skip the escaped char
        else if (ch === strCh) strCh = "";
        continue;
      }
      if (ch === "/" && next === "/") break; // line comment: rest of line is opaque
      if (ch === "/" && next === "*") {
        inBlockComment = true;
        c++;
        continue;
      }
      if (ch === '"' || ch === "'" || ch === "`") {
        strCh = ch;
        continue;
      }
      if (ch === "{") {
        depth++;
        seen = true;
      } else if (ch === "}" && seen) {
        if (--depth === 0) return i;
      }
    }
  }
  return lines.length - 1;
}

/**
 * True if the `(` at `openParen` begins a method/function parameter list whose
 * closing `)` is immediately followed by `{` — i.e. a definition (`name(args) {`),
 * not a call. Used so a routed function name reused as an object method shorthand
 * (`{ add(x, y) { … } }`) is not rewritten into `{ lib.add(x, y) { … } }`.
 * Skips string literals inside the argument list so a `)` in a string arg doesn't
 * throw off the paren match.
 */
function isMethodDefinition(src: string, openParen: number): boolean {
  let depth = 0;
  let strCh = "";
  let i = openParen;
  for (; i < src.length; i++) {
    const ch = src[i];
    if (strCh) {
      if (ch === "\\") i++;
      else if (ch === strCh) strCh = "";
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") strCh = ch;
    else if (ch === "(") depth++;
    else if (ch === ")") {
      if (--depth === 0) {
        i++;
        break;
      }
    }
  }
  while (i < src.length && /\s/.test(src[i])) i++;
  return src[i] === "{";
}

/**
 * Rewrite bare `name(` call sites to `lib.name(` for each routed function,
 * skipping: string literals, comments, member accesses (`obj.name(`), word-prefix
 * collisions (`myName(`), and object method-shorthand definitions (`{ name() {`).
 * A lightweight context-aware scan — not a full AST parse — but it covers the
 * cases a naive regex would corrupt (a routed name inside a template string or a
 * comment, or reused as an object method name).
 */
function rewriteWasmCalls(src: string, names: Set<string>): string {
  const isWord = (c: string | undefined) => c !== undefined && /[A-Za-z0-9_$]/.test(c);
  let out = "";
  let i = 0;
  const n = src.length;
  let inLineComment = false;
  let inBlockComment = false;
  let strCh = "";
  while (i < n) {
    const ch = src[i];
    const next = src[i + 1];
    if (inLineComment) {
      out += ch;
      if (ch === "\n") inLineComment = false;
      i++;
      continue;
    }
    if (inBlockComment) {
      out += ch;
      if (ch === "*" && next === "/") {
        out += next;
        i += 2;
        inBlockComment = false;
        continue;
      }
      i++;
      continue;
    }
    if (strCh) {
      out += ch;
      if (ch === "\\" && next !== undefined) {
        out += next;
        i += 2;
        continue;
      }
      if (ch === strCh) strCh = "";
      i++;
      continue;
    }
    if (ch === "/" && next === "/") {
      inLineComment = true;
      out += ch;
      i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      inBlockComment = true;
      out += ch + next;
      i += 2;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      strCh = ch;
      out += ch;
      i++;
      continue;
    }
    // Code context: try to match an identifier at a word boundary that is not a
    // member access (`.name`) or a word-prefix continuation.
    if (isWord(ch) && !isWord(src[i - 1]) && src[i - 1] !== ".") {
      let j = i;
      while (j < n && isWord(src[j])) j++;
      const ident = src.slice(i, j);
      let k = j;
      while (k < n && (src[k] === " " || src[k] === "\t")) k++;
      if (names.has(ident) && src[k] === "(" && !isMethodDefinition(src, k)) {
        out += "lib." + ident;
      } else {
        out += ident;
      }
      i = j;
      continue;
    }
    out += ch;
    i++;
  }
  return out;
}

/**
 * Parse a TypeScript source file and extract all `// @wasm`-annotated functions.
 * Returns the extracted functions and the remaining source with those functions removed.
 */
export function parseHybridFile(
  src: string,
  opts: { auto?: boolean; excludeDynamicBody?: boolean; excludeFns?: Set<string> } = {},
): ParseResult {
  const auto = opts.auto === true;
  const lines = src.split("\n");
  const wasmFuncs: WasmFunc[] = [];
  const warnings: string[] = [];
  const skipLines = new Set<number>();

  for (let i = 0; i < lines.length; i++) {
    // Only consider MODULE-LEVEL function declarations (column 0) so nested/indented
    // helpers inside other functions are never extracted independently.
    const fnMatch = lines[i].match(/^(?:export\s+)?(?:async\s+)?function\s+(\w+)/);
    if (!fnMatch) continue;
    const name = fnMatch[1];

    // Directive on the nearest preceding non-blank line: // @wasm force-includes,
    // // @js / // @host / // @ts force-excludes.
    let p = i - 1;
    while (p >= 0 && lines[p].trim() === "") p--;
    const prev = p >= 0 ? lines[p].trim() : "";
    const forceWasm = prev === "// @wasm";
    const forceHost = prev === "// @js" || prev === "// @host" || prev === "// @ts";

    const sig = analyzeSignature(lines[i]);

    // Decide routing. Annotation mode: only // @wasm functions. Auto mode: every
    // statically-routable function, unless force-excluded; // @wasm still forces include.
    let route: boolean;
    if (auto) route = forceWasm || (sig.routable && !forceHost);
    else route = forceWasm;

    // #14 follow-up (fallback refinement): a per-function exclusion set keeps specifically-named
    // functions in the host (used to move ONLY the dynamic bodies that failed to compile, instead of
    // all of them — see runHybrid's per-function fallback probe).
    if (opts.excludeFns?.has(name)) route = false;

    if (!route) continue;

    // Phase 13.5: async functions are now routable (wasic compiles async/await + Promise combinators).
    // An async fn without a Promise<T> annotation is non-routable — skip even an explicit // @wasm,
    // since the core module can't determine the unwrapped return type for its sync wrapper.
    if (sig.isAsync && sig.promiseInner === undefined) {
      warnings.push(
        `⚠  hybrid: skipping async '${name}' — needs a Promise<T> return annotation to route to WASM`,
      );
      continue;
    }
    // A force-included function with non-wasic types: keep it (wasic reports the real error)
    // but surface why it looked non-routable.
    if (forceWasm && !sig.routable && sig.reason) {
      warnings.push(
        `⚠  hybrid: '${name}' forced // @wasm but ${sig.reason} may not be wasic-compatible`,
      );
    }

    const endLine = findCloseBrace(lines, i);
    let text = lines.slice(i, endLine + 1).join("\n");

    // #14.3.4 fallback: when the full core failed to compile, keep functions with a DYNAMIC body
    // (using `any` / `eval`, which lower to the dynrt runtime) in the TS HOST — full JavaScript runs
    // them natively. Their typed signature still marshals normally either way; this only changes
    // WHERE they run. (Functions with an `any`-typed SIGNATURE were never routed — the host is the
    // natural place for them, since marshalling a boxed handle across the bindgen boundary is a
    // separate follow-up.)
    if (opts.excludeDynamicBody && /\bany\b|\beval\s*\(/.test(text)) {
      continue; // leave in remainingSrc (host)
    }

    if (!text.trimStart().startsWith("export ")) text = "export " + text.trimStart();

    wasmFuncs.push({ name, text, lineStart: i, lineEnd: endLine, isAsync: sig.isAsync });
    // Remove the function body and, when present, its directive comment line.
    // (forceHost functions already `continue`d above, so only forceWasm reaches here.)
    const startSkip = forceWasm ? p : i;
    for (let j = startSkip; j <= endLine; j++) skipLines.add(j);
  }

  const remainingSrc = lines.filter((_, idx) => !skipLines.has(idx)).join("\n");
  return { wasmFuncs, remainingSrc, warnings };
}

// ── generators ───────────────────────────────────────────────────────────────

/** Extract bare parameter names from a `(a: i32, b: f64)` parameter section. */
function paramNames(paramSection: string): string[] {
  return paramSection.split(",").map((p) => p.split(":")[0].trim()).filter(Boolean);
}

/**
 * Generate the core wasic module source from the extracted @wasm functions.
 *
 * Phase 13.5 (async lift): a routed `async function f(p): Promise<T>` cannot be exposed to the host
 * directly — compiled by modc it returns a *promise pointer* (i32), not the value. So each async fn
 * is rewritten to an internal `f__impl` (calls to other routed async fns inside any async body are
 * renamed to their `__impl` too, so the async call graph stays promise-typed), and a SYNCHRONOUS
 * exported wrapper `f` is emitted that `await`s `f__impl` and returns the unwrapped value (`T`). Under
 * wasic's eager model the body settles synchronously, so the wrapper returns a real value the host can
 * use via the normal bindgen path. `Promise<void>` wrappers just invoke the impl (no value to return).
 */
export function generateCoreModule(wasmFuncs: WasmFunc[]): string {
  const parts = [
    `// auto-generated by wasmtk hybrid — do not edit manually`,
    `// deno-lint-ignore-file`,
    ``,
  ];
  // Rename map: every routed async fn name → `<name>__impl`, applied to async bodies so intra-module
  // async calls reach the promise-returning impl (not the value-returning wrapper).
  const asyncNames = wasmFuncs.filter((f) => f.isAsync).map((f) => f.name);
  const renameImplCalls = (text: string): string => {
    let out = text;
    for (const an of asyncNames) {
      out = out.replace(new RegExp(`(?<![."'\`\\w])${an}\\s*\\(`, "g"), `${an}__impl(`);
    }
    return out;
  };

  for (const fn of wasmFuncs) {
    if (!fn.isAsync) {
      parts.push(fn.text);
      parts.push("");
      continue;
    }
    // Parse the async signature from the (export-prefixed) declaration.
    const sigM = fn.text.match(
      /export\s+async\s+function\s+\w+\s*\(([^)]*)\)\s*:\s*Promise\s*<\s*(.+?)\s*>/,
    );
    const params = sigM?.[1] ?? "";
    const inner = (sigM?.[2] ?? "void").trim();
    const args = paramNames(params).join(", ");
    // Internal impl: strip the leading `export`, rename the decl + intra-body async calls to `__impl`.
    const implText = renameImplCalls(fn.text.replace(/^export\s+/, ""));
    parts.push(implText);
    // Synchronous exported wrapper the host calls.
    if (inner === "void") {
      parts.push(`export function ${fn.name}(${params}): void {`);
      parts.push(`  ${fn.name}__impl(${args});`);
      parts.push(`}`);
    } else {
      parts.push(`export function ${fn.name}(${params}): ${inner} {`);
      parts.push(`  return await ${fn.name}__impl(${args});`);
      parts.push(`}`);
    }
    parts.push("");
  }
  return parts.join("\n");
}

/**
 * Generate the TypeScript runner from the non-@wasm source.
 *
 * - Adds an import of `loadModule` from the generated bindings.
 * - Injects `const lib = await loadModule(...)` after all import statements.
 * - Rewrites bare `funcName(` call sites to `lib.funcName(`.
 *   Method calls (`obj.funcName(`) are intentionally left unchanged.
 */
export function generateRunner(
  remainingSrc: string,
  wasmFuncNames: string[],
  bindingsRelPath: string,
  wasmRelPath: string,
): string {
  // Rewrite call sites: funcName( → lib.funcName( via a context-aware scan that
  // skips strings, comments, member accesses, word-prefix collisions, and object
  // method-shorthand definitions (see rewriteWasmCalls).
  const patched = rewriteWasmCalls(remainingSrc, new Set(wasmFuncNames));

  // Find where the LAST import statement ENDS, so we inject after it. A single-line
  // regex would match only the first line of a multi-line import (`import {\n …\n} from
  // "x";`) and splice the loader mid-statement — so walk each import to its terminating
  // line (a `from "…"` clause, a bare side-effect string, or a trailing `;`).
  const patchedLines = patched.split("\n");
  let lastImportEnd = -1;
  for (let i = 0; i < patchedLines.length; i++) {
    if (!/^\s*import\b/.test(patchedLines[i])) continue;
    let j = i;
    while (
      j < patchedLines.length &&
      !/\bfrom\s+['"][^'"]*['"]\s*;?\s*$/.test(patchedLines[j]) && // named/default/namespace import
      !/^\s*import\s+['"][^'"]*['"]\s*;?\s*$/.test(patchedLines[j]) && // bare side-effect import
      !/;\s*$/.test(patchedLines[j]) // fallback: statement-terminating semicolon
    ) j++;
    lastImportEnd = Math.min(j, patchedLines.length - 1);
    i = lastImportEnd;
  }

  // Inject the binding import + loadModule call
  const injection = [
    `import { loadModule } from "${bindingsRelPath}";`,
    ``,
    `const lib = await loadModule(new URL("${wasmRelPath}", import.meta.url));`,
  ];
  patchedLines.splice(lastImportEnd + 1, 0, "", ...injection, "");

  return [
    `// auto-generated by wasmtk hybrid — do not edit manually`,
    `// deno-lint-ignore-file`,
    ``,
    ...patchedLines,
  ].join("\n");
}

// ── pipeline ─────────────────────────────────────────────────────────────────

/**
 * Run the full hybrid pipeline on a TypeScript source file:
 *   parse → generate core module → modc compile → bindgen → generate runner
 */
export async function runHybrid(
  inputPath: string,
  opts: { outDir?: string; auto?: boolean } = {},
): Promise<void> {
  const src = await rt.readTextFile(inputPath);
  const dir = dirname(inputPath);
  const base = basename(inputPath, ".ts");
  const outDir = opts.outDir ?? dir;

  let { wasmFuncs, remainingSrc, warnings } = parseHybridFile(src, { auto: opts.auto });

  for (const w of warnings) console.warn(w);

  if (wasmFuncs.length === 0) {
    if (opts.auto) {
      console.warn(
        `⚠  hybrid --auto: no statically-typed functions to route to WASM in ${inputPath}`,
      );
      console.warn(`   A function is routed to WASM when it is non-async and every parameter +`);
      console.warn(`   return type is wasic-compatible (i32/i64/f32/f64/bool/string/number/…).`);
    } else {
      console.warn(`⚠  hybrid: no // @wasm functions found in ${inputPath}`);
      console.warn(`   Annotate functions with // @wasm, or use --auto to route by type:`);
      console.warn(`     // @wasm`);
      console.warn(`     export function add(a: i32, b: i32): i32 { return a + b; }`);
    }
    return;
  }

  const funcNames = wasmFuncs.map((f) => f.name);
  console.log(
    `   hybrid${opts.auto ? " --auto" : ""}: ${funcNames.length} WASM function(s): ${
      funcNames.join(", ")
    }`,
  );

  // Step 1+2 — write the generated core module and compile it with modc (emits .wasm + .wit).
  // #14.3.4: try-compile / fall-back-to-host. Functions whose bodies use `any` / `eval` now lower to
  // the merged dynrt runtime; if some dynamic body exceeds what wasic+dynrt can compile, the whole
  // core fails — so on failure we re-route the dynamic-bodied functions to the TS HOST (full JS) and
  // recompile the static remainder. Static-only programs hit neither branch (identical behavior).
  const coreTsPath = join(outDir, `${base}_core.ts`);
  const coreWitPath = join(outDir, `${base}_core.wit`);

  // modc prints a diagnostic and returns (it does NOT throw) on a compile abort, so detect failure by
  // whether the .wit was (re)produced. Remove a stale one first so the check is reliable.
  const compileCore = async (funcs: WasmFunc[]): Promise<boolean> => {
    try {
      await rt.remove(coreWitPath);
    } catch { /* not present */ }
    await rt.writeTextFile(coreTsPath, generateCoreModule(funcs));
    try {
      await compileModule(coreTsPath);
    } catch { /* fall through to the file-existence check */ }
    try {
      await rt.stat(coreWitPath);
      return true;
    } catch {
      return false;
    }
  };

  // Compile a candidate set to a SEPARATE probe module (so it can't clobber the real core), used to
  // find WHICH dynamic function fails; cleans up its own artifacts.
  const probeCompiles = async (funcs: WasmFunc[]): Promise<boolean> => {
    const probeTs = join(outDir, `${base}_probe.ts`);
    const probeWit = join(outDir, `${base}_probe.wit`);
    try {
      await rt.remove(probeWit);
    } catch { /* not present */ }
    await rt.writeTextFile(probeTs, generateCoreModule(funcs));
    try {
      await compileModule(probeTs);
    } catch { /* fall through */ }
    let ok = false;
    try {
      await rt.stat(probeWit);
      ok = true;
    } catch { /* failed */ }
    for (const ext of [".ts", ".wasm", ".wat", ".wit"]) {
      try {
        await rt.remove(join(outDir, `${base}_probe${ext}`));
      } catch { /* best-effort cleanup */ }
    }
    return ok;
  };

  const emitHostOnly = async (): Promise<void> => {
    const runnerOnlyPath = join(outDir, `${base}_runner.ts`);
    await rt.writeTextFile(runnerOnlyPath, remainingSrc);
    console.log(`   hybrid: no WASM-routable functions remain — runner is host-only`);
    console.log(`   hybrid: runner   → ${runnerOnlyPath}`);
  };

  if (!(await compileCore(wasmFuncs))) {
    // #14 follow-up (fallback refinement): probe each DYNAMIC (any/eval) function against the static
    // context to find the specific culprits, and move ONLY those to the host — keeping the dynamic
    // functions that DO compile in the WASM core (the 14.3.4 fallback moved them all).
    const isDynamic = (fn: WasmFunc) => /\bany\b|\beval\s*\(/.test(fn.text);
    const dynamics = wasmFuncs.filter(isDynamic);
    if (dynamics.length === 0) {
      throw new Error(`hybrid: core module failed to compile (and no dynamic body to fall back)`);
    }
    const statics = wasmFuncs.filter((f) => !isDynamic(f));
    const bad = new Set<string>();
    for (const d of dynamics) {
      if (!(await probeCompiles([...statics, d]))) bad.add(d.name);
    }
    // No single culprit (e.g. dynamic-calls-dynamic): coarsen to moving all dynamic bodies to host.
    if (bad.size === 0) { for (const d of dynamics) bad.add(d.name); }
    console.warn(
      `⚠  hybrid: ${bad.size} dynamic function(s) did not compile to WASM — keeping them in the TS ` +
        `host (fallback): ${[...bad].join(", ")}`,
    );
    const reparsed = parseHybridFile(src, { auto: opts.auto, excludeFns: bad });
    wasmFuncs = reparsed.wasmFuncs;
    remainingSrc = reparsed.remainingSrc;
    if (wasmFuncs.length === 0) {
      await emitHostOnly();
      return;
    }
    if (!(await compileCore(wasmFuncs))) {
      // Survivors still fail (a static fn depends on a moved dynamic) — coarsen: ALL dynamics → host.
      const reparsed2 = parseHybridFile(src, { auto: opts.auto, excludeDynamicBody: true });
      wasmFuncs = reparsed2.wasmFuncs;
      remainingSrc = reparsed2.remainingSrc;
      if (wasmFuncs.length === 0) {
        await emitHostOnly();
        return;
      }
      if (!(await compileCore(wasmFuncs))) {
        throw new Error(`hybrid: static core failed to compile after fallback`);
      }
    }
    console.log(
      `   hybrid: core     → ${coreTsPath} (${bad.size} dynamic function(s) kept in host)`,
    );
  } else {
    console.log(`   hybrid: core     → ${coreTsPath}`);
  }

  // Step 3 — generate TypeScript bindings from the .wit
  await runBindgen(coreWitPath);

  // Step 4 — write runner. Recompute the routed names from the FINAL wasmFuncs (the fallback may
  // have moved some back to the host) so only the names actually in the core are rewritten to `lib.`.
  const routedNames = wasmFuncs.map((f) => f.name);
  const runnerPath = join(outDir, `${base}_runner.ts`);
  await rt.writeTextFile(
    runnerPath,
    generateRunner(
      remainingSrc,
      routedNames,
      `./${base}_core.bindings.ts`,
      `./${base}_core.wasm`,
    ),
  );
  console.log(`   hybrid: runner   → ${runnerPath}`);
  console.log(`   hybrid: done — run with: deno run --allow-read ${runnerPath}`);
}
