/**
 * @module hybrid
 * @description Splits a TypeScript file into a wasic-compiled WASM core and a TypeScript runner.
 *
 * Any function annotated with `// @wasm` on the immediately preceding line is:
 *   1. Extracted into a generated `<base>_core.ts` module file.
 *   2. Compiled to WASM via `wasmtk modc` (library mode, no _start).
 *   3. Described by a `.wit` interface (auto-generated by Phase 41).
 *   4. Bound via `wasmtk bindgen` into a `<base>_core.bindings.ts` type-safe loader.
 *
 * A `<base>_runner.ts` file is then generated containing:
 *   - All non-annotated code from the original file (unchanged).
 *   - An import of `loadModule` from the generated bindings.
 *   - A top-level `const lib = await loadModule(...)` declaration.
 *   - Every call site that previously called an `@wasm` function rewritten to `lib.funcName(...)`.
 *
 * CLI:
 *   wasmtk hybrid <file.ts> [-o outdir]
 *
 * Constraints (prototype):
 *   - `// @wasm` must appear on the line directly before the function declaration.
 *   - Only named `function` declarations are supported (no arrow functions, no classes).
 *   - Async functions are skipped with a warning — wasic cannot compile them.
 *   - All param/return types should be wasic-compatible; incompatible types produce a warning
 *     but the function is still extracted (wasic will report an error at compile time).
 *   - Call-site rewriting uses regex; method calls (`obj.funcName(...)`) are not rewritten.
 *   - The generated runner uses top-level `await` (Deno ES module native support).
 */

import { basename, dirname, join } from "@std/path";
import { rt } from "./rt.ts";
import { compileModule } from "./modc.ts";
import { runBindgen } from "./bindgen.ts";

// ── types ────────────────────────────────────────────────────────────────────

/** A `// @wasm`-annotated function extracted from a hybrid TypeScript source file. */
export interface WasmFunc {
  name: string;
  text: string;      // complete function source text, guaranteed to start with "export "
  lineStart: number; // 0-indexed line of the // @wasm annotation
  lineEnd: number;   // 0-indexed last line of the function body
}

/** Result of `parseHybridFile()`: the extracted WASM functions, remaining TypeScript source, and any warnings. */
export interface ParseResult {
  wasmFuncs: WasmFunc[];
  remainingSrc: string; // original source with @wasm functions (and their annotations) removed
  warnings: string[];
}

// wasic-compatible primitive type names
const WASIC_PRIMITIVES = new Set([
  "i32", "i64", "f32", "f64",
  "bool", "boolean",
  "string",
  "void", "never",
  "number", // maps to f64 in wasic
]);

/** Returns `true` if `t` is a wasic-compatible primitive type name (e.g. `"i32"`, `"string"`, `"bool[]"`). */
export function isWasicType(t: string): boolean {
  const clean = t.trim().replace(/\s/g, "");
  if (WASIC_PRIMITIVES.has(clean)) return true;
  if (clean.endsWith("[]")) return WASIC_PRIMITIVES.has(clean.slice(0, -2));
  return false;
}

/**
 * Static-routability analysis of a function declaration line for `--auto` mode (Brief #6).
 * A function is WASM-routable iff it is NOT async, every parameter carries a wasic-compatible
 * type annotation, and the return type (if present) is wasic-compatible. Untyped params or
 * `any`/object/dynamic types make it non-routable → it stays in the TypeScript host.
 */
export function analyzeSignature(
  decl: string,
): { isAsync: boolean; routable: boolean; reason?: string } {
  const isAsync = /^\s*(?:export\s+)?async\s+function\b/.test(decl);
  if (isAsync) return { isAsync, routable: false, reason: "async" };
  const paramSection = decl.match(/\(([^)]*)\)/)?.[1] ?? "";
  const returnType = decl.match(/\)\s*:\s*([\w[\]|]+)/)?.[1];
  const params = paramSection.split(",").map((p) => p.trim()).filter(Boolean);
  for (const p of params) {
    const t = p.split(":")[1]?.trim();
    if (!t) return { isAsync, routable: false, reason: `untyped parameter '${p}'` };
    if (!isWasicType(t)) return { isAsync, routable: false, reason: `parameter type '${t}'` };
  }
  if (returnType && !isWasicType(returnType)) {
    return { isAsync, routable: false, reason: `return type '${returnType}'` };
  }
  return { isAsync, routable: true };
}

// ── parser ───────────────────────────────────────────────────────────────────

/** Walk forward from openLine until the opening brace's matching close brace. */
function findCloseBrace(lines: string[], openLine: number): number {
  let depth = 0;
  let seen = false;
  for (let i = openLine; i < lines.length; i++) {
    for (const ch of lines[i]) {
      if (ch === "{") { depth++; seen = true; }
      else if (ch === "}" && seen) {
        if (--depth === 0) return i;
      }
    }
  }
  return lines.length - 1;
}

/**
 * Parse a TypeScript source file and extract all `// @wasm`-annotated functions.
 * Returns the extracted functions and the remaining source with those functions removed.
 */
export function parseHybridFile(
  src: string,
  opts: { auto?: boolean } = {},
): ParseResult {
  const auto = opts.auto === true;
  const lines = src.split("\n");
  const wasmFuncs: WasmFunc[] = [];
  const warnings: string[] = [];
  const skipLines = new Set<number>();

  for (let i = 0; i < lines.length; i++) {
    // Only consider MODULE-LEVEL function declarations (column 0) so nested/indented
    // helpers inside other functions are never extracted independently.
    const fnMatch = lines[i].match(/^(?:export\s+)?(?:async\s+)?function\s+(\w+)/);
    if (!fnMatch) continue;
    const name = fnMatch[1];

    // Directive on the nearest preceding non-blank line: // @wasm force-includes,
    // // @js / // @host / // @ts force-excludes.
    let p = i - 1;
    while (p >= 0 && lines[p].trim() === "") p--;
    const prev = p >= 0 ? lines[p].trim() : "";
    const forceWasm = prev === "// @wasm";
    const forceHost = prev === "// @js" || prev === "// @host" || prev === "// @ts";

    const sig = analyzeSignature(lines[i]);

    // Decide routing. Annotation mode: only // @wasm functions. Auto mode: every
    // statically-routable function, unless force-excluded; // @wasm still forces include.
    let route: boolean;
    if (auto) route = forceWasm || (sig.routable && !forceHost);
    else route = forceWasm;

    if (!route) continue;

    // Async can never be compiled by wasic — even an explicit // @wasm cannot override that.
    if (sig.isAsync) {
      warnings.push(`⚠  hybrid: skipping '${name}' — async functions cannot be compiled by wasic`);
      continue;
    }
    // A force-included function with non-wasic types: keep it (wasic reports the real error)
    // but surface why it looked non-routable.
    if (forceWasm && !sig.routable && sig.reason) {
      warnings.push(`⚠  hybrid: '${name}' forced // @wasm but ${sig.reason} may not be wasic-compatible`);
    }

    const endLine = findCloseBrace(lines, i);
    let text = lines.slice(i, endLine + 1).join("\n");
    if (!text.trimStart().startsWith("export ")) text = "export " + text.trimStart();

    wasmFuncs.push({ name, text, lineStart: i, lineEnd: endLine });
    // Remove the function body and, when present, its directive comment line.
    const startSkip = (forceWasm || forceHost) ? p : i;
    for (let j = startSkip; j <= endLine; j++) skipLines.add(j);
  }

  const remainingSrc = lines.filter((_, idx) => !skipLines.has(idx)).join("\n");
  return { wasmFuncs, remainingSrc, warnings };
}

// ── generators ───────────────────────────────────────────────────────────────

/** Generate the core wasic module source from the extracted @wasm functions. */
export function generateCoreModule(wasmFuncs: WasmFunc[]): string {
  const parts = [
    `// auto-generated by wasmtk hybrid — do not edit manually`,
    `// deno-lint-ignore-file`,
    ``,
  ];
  for (const fn of wasmFuncs) {
    parts.push(fn.text);
    parts.push("");
  }
  return parts.join("\n");
}

/**
 * Generate the TypeScript runner from the non-@wasm source.
 *
 * - Adds an import of `loadModule` from the generated bindings.
 * - Injects `const lib = await loadModule(...)` after all import statements.
 * - Rewrites bare `funcName(` call sites to `lib.funcName(`.
 *   Method calls (`obj.funcName(`) are intentionally left unchanged.
 */
export function generateRunner(
  remainingSrc: string,
  wasmFuncNames: string[],
  bindingsRelPath: string,
  wasmRelPath: string,
): string {
  // Rewrite call sites: funcName( → lib.funcName(
  // Negative lookbehind blocks: method calls (obj.funcName), word prefixes (myFuncName),
  // and string/comment contexts ("funcName(, 'funcName(, `funcName().
  let patched = remainingSrc;
  for (const name of wasmFuncNames) {
    patched = patched.replace(
      new RegExp(`(?<![."'\`\\w])${name}\\s*\\(`, "g"),
      `lib.${name}(`,
    );
  }

  // Find the last import line so we can inject after it
  const patchedLines = patched.split("\n");
  let lastImportIdx = -1;
  for (let i = 0; i < patchedLines.length; i++) {
    if (/^\s*import\s/.test(patchedLines[i])) lastImportIdx = i;
  }

  // Inject the binding import + loadModule call
  const injection = [
    `import { loadModule } from "${bindingsRelPath}";`,
    ``,
    `const lib = await loadModule(new URL("${wasmRelPath}", import.meta.url));`,
  ];
  patchedLines.splice(lastImportIdx + 1, 0, "", ...injection, "");

  return [
    `// auto-generated by wasmtk hybrid — do not edit manually`,
    `// deno-lint-ignore-file`,
    ``,
    ...patchedLines,
  ].join("\n");
}

// ── pipeline ─────────────────────────────────────────────────────────────────

/**
 * Run the full hybrid pipeline on a TypeScript source file:
 *   parse → generate core module → modc compile → bindgen → generate runner
 */
export async function runHybrid(
  inputPath: string,
  opts: { outDir?: string; auto?: boolean } = {},
): Promise<void> {
  const src = await rt.readTextFile(inputPath);
  const dir = dirname(inputPath);
  const base = basename(inputPath, ".ts");
  const outDir = opts.outDir ?? dir;

  const { wasmFuncs, remainingSrc, warnings } = parseHybridFile(src, { auto: opts.auto });

  for (const w of warnings) console.warn(w);

  if (wasmFuncs.length === 0) {
    if (opts.auto) {
      console.warn(`⚠  hybrid --auto: no statically-typed functions to route to WASM in ${inputPath}`);
      console.warn(`   A function is routed to WASM when it is non-async and every parameter +`);
      console.warn(`   return type is wasic-compatible (i32/i64/f32/f64/bool/string/number/…).`);
    } else {
      console.warn(`⚠  hybrid: no // @wasm functions found in ${inputPath}`);
      console.warn(`   Annotate functions with // @wasm, or use --auto to route by type:`);
      console.warn(`     // @wasm`);
      console.warn(`     export function add(a: i32, b: i32): i32 { return a + b; }`);
    }
    return;
  }

  const funcNames = wasmFuncs.map((f) => f.name);
  console.log(`   hybrid${opts.auto ? " --auto" : ""}: ${funcNames.length} WASM function(s): ${funcNames.join(", ")}`);

  // Step 1 — write generated core module
  const coreTsPath = join(outDir, `${base}_core.ts`);
  await rt.writeTextFile(coreTsPath, generateCoreModule(wasmFuncs));
  console.log(`   hybrid: core     → ${coreTsPath}`);

  // Step 2 — compile core module with modc (emits .wasm + .wit)
  await compileModule(coreTsPath);

  // Step 3 — generate TypeScript bindings from the .wit
  const coreWitPath = join(outDir, `${base}_core.wit`);
  await runBindgen(coreWitPath);

  // Step 4 — write runner
  const runnerPath = join(outDir, `${base}_runner.ts`);
  await rt.writeTextFile(
    runnerPath,
    generateRunner(
      remainingSrc,
      funcNames,
      `./${base}_core.bindings.ts`,
      `./${base}_core.wasm`,
    ),
  );
  console.log(`   hybrid: runner   → ${runnerPath}`);
  console.log(`   hybrid: done — run with: deno run --allow-read ${runnerPath}`);
}
