/**
 * @module witgen
 * @description `.wit` auto-emission for any `.wasm` wasmtk writes through an OPTIMISE or WAT→WASM
 * step (owner decision 2026-09-28): the Go and Zig producers, `wasmbundle`, `convert x.wat`, and
 * `wasic x.wat`. The TypeScript compiler (`wasic`/`modc` on `.ts`) already writes a RICHER `.wit`
 * from source types and is not routed here.
 *
 * A binary carries only CORE types, so this `.wit` is derived from core signatures: `i32→s32`,
 * `i64→s64`, `f32`, `f64`. A string that crosses as `(ptr, len)` shows up as two `s32`s. It is the
 * honest floor of what the module's interface is, and the header says so. An export whose signature
 * has no WIT form (v128, references, multiple results) or whose name is not a WIT identifier is left
 * out and LISTED in a comment, never silently dropped.
 *
 * Never clobbers a better file: an existing `.wit` is replaced only when it is one of THESE generated
 * files (its first line is `GENERATED_HEADER`). A `wasic`-generated or hand-written `.wit` (Go's
 * `strlib.wit` declares `string`s) is kept, and that is reported.
 */

import binaryen from "./binaryen.ts";
import { basename } from "@std/path";
import { rt } from "./rt.ts";

/** First line of every `.wit` this module writes; its presence is what allows a rewrite. */
export const GENERATED_HEADER =
  "// Generated by wasmtk from core wasm signatures — do not edit manually";

/** Same rule as `wasic`'s `toKebabCase`, so names line up with its `.wit` and bindgen's resolution. */
function toKebabCase(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/_/g, "-").toLowerCase();
}

/** A WIT identifier: kebab words, each starting with a letter. */
const WIT_ID = /^[a-z][a-z0-9]*(-[a-z][a-z0-9]*)*$/;

/** Exports that are runtime plumbing, not the module's interface (as `wasmtk info` treats them). */
/**
 * TinyGo's libc/float runtime exports: present in every TinyGo module, not the author's API.
 * Measured on the Go fixtures 2026-09-28 (`strlib`, `mathleaf`).
 */
const TOOLCHAIN_RUNTIME_EXPORTS = new Set([
  "malloc",
  "free",
  "calloc",
  "realloc",
  "fminimum",
  "fminimumf",
  "fmaximum",
  "fmaximumf",
]);

function isInternalExport(name: string): boolean {
  return name === "_start" || name === "_initialize" || name === "abort" || name.startsWith("__") ||
    name.startsWith("cabi_") || name.startsWith("asyncify_") || name.includes("config-schema") ||
    TOOLCHAIN_RUNTIME_EXPORTS.has(name);
}

function coreToWit(t: number): string | null {
  if (t === binaryen.i32) return "s32";
  if (t === binaryen.i64) return "s64";
  if (t === binaryen.f32) return "f32";
  if (t === binaryen.f64) return "f64";
  return null; // v128, references, …
}

/** A function's WIT signature from its core type, or the reason it has none. */
function witSig(params: number, results: number): { sig: string } | { why: string } {
  const ps = binaryen.expandType(params) as number[];
  const rs = binaryen.expandType(results) as number[];
  if (rs.length > 1) return { why: "multiple results" };
  const pw = ps.map(coreToWit);
  const rw = rs.map(coreToWit);
  if (pw.includes(null) || rw.includes(null)) {
    return { why: "a core type with no WIT form (v128/reference)" };
  }
  const paramStr = pw.map((t, i) => `p${i}: ${t}`).join(", ");
  return { sig: `func(${paramStr})${rw.length ? ` -> ${rw[0]}` : ""}` };
}

/**
 * Derive a `.wit` from a module's exported functions. `name` becomes the package/world
 * (kebab-cased). Non-WASI function IMPORTS are listed by name in a comment, not described: the
 * backend's public API enumerates exports with signatures but not imports, and reaching its
 * internal IR for them would couple us to a shape it does not publish.
 */
export function witFromWasm(bytes: Uint8Array, name: string): string {
  const pkg = toKebabCase(name);
  const exports: string[] = [];
  const skipped: string[] = [];
  const hostImports = WebAssembly.Module.imports(new WebAssembly.Module(bytes as BufferSource))
    .filter((i) => i.kind === "function" && i.module !== "wasi_snapshot_preview1")
    .map((i) => `${i.module}.${i.name}`);
  const module = binaryen.readBinary(bytes);
  try {
    for (let i = 0; i < module.getNumExports(); i++) {
      const exp = binaryen.getExportInfo(module.getExportByIndex(i));
      if (exp.kind !== binaryen.ExternalFunction || isInternalExport(exp.name)) continue;
      const info = binaryen.getFunctionInfo(module.getFunction(exp.value));
      const id = toKebabCase(exp.name);
      const s = witSig(info.params, info.results);
      if (!WIT_ID.test(id)) skipped.push(`export ${exp.name}: not a WIT identifier`);
      else if ("why" in s) skipped.push(`export ${exp.name}: ${s.why}`);
      else exports.push(`  export ${id}: ${s.sig};`);
    }
  } finally {
    module.dispose();
  }
  return [
    GENERATED_HEADER,
    "// Core types only: a string or record crosses as (ptr, len)/pointers and shows as s32s here.",
    ...skipped.map((s) => `// skipped ${s}`),
    ...(hostImports.length
      ? [
        `// host imports (types not derived; provide them to the loader): ${
          hostImports.join(", ")
        }`,
      ]
      : []),
    `package local:${pkg};`,
    ``,
    `world ${pkg} {`,
    ...exports,
    `}`,
    ``,
  ].join("\n");
}

/**
 * Write `<wasmPath minus .wasm>.wit` from the FINISHED module on disk (after any optimisation), unless
 * a better `.wit` is already there (see the module doc). Never throws: a `.wit` is a by-product, so a
 * failure is WARNED and the build it rides on is not failed. `task` names the step, for the log.
 */
export async function emitWitBeside(wasmPath: string, task: string): Promise<void> {
  const witPath = wasmPath.replace(/\.wasm$/i, "") + ".wit";
  try {
    const bytes = await rt.readFile(wasmPath);
    let existing: string | null = null;
    try {
      existing = await rt.readTextFile(witPath);
    } catch { /* absent */ }
    if (existing !== null && !existing.startsWith(GENERATED_HEADER)) {
      console.log(`  ↪ kept existing ${basename(witPath)} (not generated from core signatures)`);
      return;
    }
    const name = basename(wasmPath).replace(/\.wasm$/i, "");
    const text = witFromWasm(bytes, name);
    // Nothing to describe (a program exporting only `_start`): write nothing. An empty-world `.wit`
    // is noise, the same judgement that stopped `dync` writing one (2026-07-28).
    if (!/^ {2}export |^\/\/ skipped |^\/\/ host imports/m.test(text)) {
      console.log(`  ↪ no .wit for ${basename(wasmPath)}: it exports no interface`);
      return;
    }
    await rt.writeTextFile(witPath, text);
    console.log(`  ↪ WIT (${task}, core types): ${witPath}`);
  } catch (e) {
    console.warn(`  ⚠️  could not emit ${witPath}: ${e instanceof Error ? e.message : e}`);
  }
}
