(module
  (memory (export "memory") 2)
  (global $__heap_ptr (mut i32) (i32.const 260))
  (global $INITIAL_CAP i32 (i32.const 8))
  ;; Bump allocator — advances __heap_ptr and returns the old value
  (func $__malloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $__heap_ptr))
    (global.set $__heap_ptr (i32.add (local.get $ptr) (local.get $size)))
    (local.get $ptr)
  )
  ;; Canonical ABI allocator — fresh allocation (ptr==0) delegates to $__malloc;
  ;; realloc requests (ptr!=0) return ptr unchanged (bump allocator has no free).
  (func $cabi_realloc (param $ptr i32) (param $old_size i32) (param $align i32) (param $new_size i32) (result i32)
    (select
      (call $__malloc (local.get $new_size))
      (local.get $ptr)
      (i32.eqz (local.get $ptr))
    )
  )
  (func $allocSlots (param $n i32) (result i32)
    (local $a i32)
    (local.set $a (call $__malloc (i32.add (i32.const 8) (i32.shl (local.get $n) (i32.const 2)))))
      (i32.store (local.get $a) (local.get $n))
    (return (local.get $a))
  )

  (func $setNew (export "setNew")  (result i32)
    (local $header i32)
    (local.set $header (call $__malloc (i32.const 24)))
      (i32.store (local.get $header) (i32.const 4))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2))) (i32.const 0))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2))) (global.get $INITIAL_CAP))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 2) (i32.const 2))) (call $allocSlots (global.get $INITIAL_CAP)))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 3) (i32.const 2))) (call $allocSlots (global.get $INITIAL_CAP)))
    (return (local.get $header))
  )

  (func $setGrow (param $h i32) 
    (local $header i32)
    (local $oldCap i32)
    (local $oldKeys i32)
    (local $oldUsed i32)
    (local $newCap i32)
    (local $newKeysPtr i32)
    (local $newUsedPtr i32)
    (local $newKeys i32)
    (local $newUsed i32)
    (local $mask i32)
    (local $i i32)
    (local $k i32)
    (local $idx i32)
    (local.set $header (local.get $h))
    (local.set $oldCap (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2)))))
    (local.set $oldKeys (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 2) (i32.const 2)))))
    (local.set $oldUsed (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 3) (i32.const 2)))))
    (local.set $newCap (i32.mul (local.get $oldCap) (i32.const 2)))
    (local.set $newKeysPtr (call $allocSlots (local.get $newCap)))
    (local.set $newUsedPtr (call $allocSlots (local.get $newCap)))
    (local.set $newKeys (local.get $newKeysPtr))
    (local.set $newUsed (local.get $newUsedPtr))
    (local.set $mask (i32.sub (local.get $newCap) (i32.const 1)))
    (local.set $i (i32.const 0))
    (block $break_0
      (loop $loop_0
        (br_if $break_0 (i32.eqz (i32.lt_s (local.get $i) (local.get $oldCap))))
        (block $cont_0
          (if (i32.ne (i32.load (i32.add (i32.add (local.get $oldUsed) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))) (i32.const 0))
            (then
            (local.set $k (i32.load (i32.add (i32.add (local.get $oldKeys) (i32.const 8)) (i32.shl (local.get $i) (i32.const 2)))))
            (local.set $idx (i32.and (local.get $k) (local.get $mask)))
            (block $break_1
              (loop $loop_1
                (br_if $break_1 (i32.eqz (i32.ne (i32.load (i32.add (i32.add (local.get $newUsed) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2)))) (i32.const 0))))
                (block $cont_1
                  (local.set $idx (i32.and (i32.add (local.get $idx) (i32.const 1)) (local.get $mask)))
                )
                (br $loop_1)
              )
            )
            (i32.store (i32.add (i32.add (local.get $newKeys) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2))) (local.get $k))
            (i32.store (i32.add (i32.add (local.get $newUsed) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2))) (i32.const 1))
            )
          )
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
        )
        (br $loop_0)
      )
    )
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2))) (local.get $newCap))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 2) (i32.const 2))) (local.get $newKeysPtr))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 3) (i32.const 2))) (local.get $newUsedPtr))
  )

  (func $setAdd (export "setAdd") (param $h i32) (param $key i32) 
    (local $pre i32)
    (local $header i32)
    (local $cap i32)
    (local $keys i32)
    (local $used i32)
    (local $mask i32)
    (local $idx i32)
    (local $__str_op_ptr i32)
    (local $__str_op_len i32)
    (local.set $pre (local.get $h))
    (if (i32.gt_s (i32.mul (i32.add (i32.load (i32.add (i32.add (local.get $pre) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2)))) (i32.const 1)) (i32.const 2)) (i32.load (i32.add (i32.add (local.get $pre) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2)))))
      (then
      (call $setGrow (local.get $h))
      )
    )
    (local.set $header (local.get $h))
    (local.set $cap (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2)))))
    (local.set $keys (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 2) (i32.const 2)))))
    (local.set $used (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 3) (i32.const 2)))))
    (local.set $mask (i32.sub (local.get $cap) (i32.const 1)))
    (local.set $idx (i32.and (local.get $key) (local.get $mask)))
    (block $break_2
      (loop $loop_2
        (br_if $break_2 (i32.eqz (i32.ne (i32.load (i32.add (i32.add (local.get $used) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2)))) (i32.const 0))))
        (block $cont_2
          (if (i32.eq (i32.load (i32.add (i32.add (local.get $keys) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2)))) (local.get $key))
            (then
            (return)
            )
          )
          (local.set $idx (i32.and (i32.add (local.get $idx) (i32.const 1)) (local.get $mask)))
        )
        (br $loop_2)
      )
    )
    (i32.store (i32.add (i32.add (local.get $keys) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2))) (local.get $key))
    (i32.store (i32.add (i32.add (local.get $used) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2))) (i32.const 1))
    (i32.store (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2))) (i32.add (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2)))) (i32.const 1)))
  )

  (func $setHas (export "setHas") (param $h i32) (param $key i32) (result i32)
    (local $header i32)
    (local $cap i32)
    (local $keys i32)
    (local $used i32)
    (local $mask i32)
    (local $idx i32)
    (local.set $header (local.get $h))
    (local.set $cap (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 1) (i32.const 2)))))
    (local.set $keys (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 2) (i32.const 2)))))
    (local.set $used (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 3) (i32.const 2)))))
    (local.set $mask (i32.sub (local.get $cap) (i32.const 1)))
    (local.set $idx (i32.and (local.get $key) (local.get $mask)))
    (block $break_3
      (loop $loop_3
        (br_if $break_3 (i32.eqz (i32.ne (i32.load (i32.add (i32.add (local.get $used) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2)))) (i32.const 0))))
        (block $cont_3
          (if (i32.eq (i32.load (i32.add (i32.add (local.get $keys) (i32.const 8)) (i32.shl (local.get $idx) (i32.const 2)))) (local.get $key))
            (then
            (return (i32.const 1))
            )
          )
          (local.set $idx (i32.and (i32.add (local.get $idx) (i32.const 1)) (local.get $mask)))
        )
        (br $loop_3)
      )
    )
    (return (i32.const 0))
  )

  (func $setSize (export "setSize") (param $h i32) (result i32)
    (local $header i32)
    (local.set $header (local.get $h))
    (return (i32.load (i32.add (i32.add (local.get $header) (i32.const 8)) (i32.shl (i32.const 0) (i32.const 2)))))
  )
)